/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AddFileToLinkRequest } from '../../models/add-file-to-link-request';
import { LinkDetail } from '../../models/link-detail';

export interface AddFileToLink$Params {
  id: string;
      body: AddFileToLinkRequest
}

export function addFileToLink(http: HttpClient, rootUrl: string, params: AddFileToLink$Params, context?: HttpContext): Observable<StrictHttpResponse<LinkDetail>> {
  const rb = new RequestBuilder(rootUrl, addFileToLink.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LinkDetail>;
    })
  );
}

addFileToLink.PATH = '/api/v1/links/{id}/files';
