/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreatePersonalAccessTokenRequest } from '../../models/create-personal-access-token-request';
import { CreatePersonalAccessTokenResponse } from '../../models/create-personal-access-token-response';

export interface CreatePersonalAccessToken$Params {
      body: CreatePersonalAccessTokenRequest
}

export function createPersonalAccessToken(http: HttpClient, rootUrl: string, params: CreatePersonalAccessToken$Params, context?: HttpContext): Observable<StrictHttpResponse<CreatePersonalAccessTokenResponse>> {
  const rb = new RequestBuilder(rootUrl, createPersonalAccessToken.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CreatePersonalAccessTokenResponse>;
    })
  );
}

createPersonalAccessToken.PATH = '/api/v1/settings/tokens';
