/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateMailAccountRequest } from '../../models/create-mail-account-request';
import { MailAccount } from '../../models/mail-account';

export interface CreateMailAccount$Params {
      body: CreateMailAccountRequest
}

export function createMailAccount(http: HttpClient, rootUrl: string, params: CreateMailAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<MailAccount>> {
  const rb = new RequestBuilder(rootUrl, createMailAccount.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MailAccount>;
    })
  );
}

createMailAccount.PATH = '/api/v1/settings/mail/accounts';
