/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateMailRuleRequest } from '../../models/create-mail-rule-request';
import { MailRule } from '../../models/mail-rule';

export interface CreateMailRule$Params {
      body: CreateMailRuleRequest
}

export function createMailRule(http: HttpClient, rootUrl: string, params: CreateMailRule$Params, context?: HttpContext): Observable<StrictHttpResponse<MailRule>> {
  const rb = new RequestBuilder(rootUrl, createMailRule.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MailRule>;
    })
  );
}

createMailRule.PATH = '/api/v1/settings/mail/rules';
