/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DownloadPublicLinkDatei$Params {
  accessToken: string;
  dateiId: string;

/**
 * Plain-text code used to unlock the link when one is configured
 */
  'X-Datei-Link-Code'?: string;
}

export function downloadPublicLinkDatei(http: HttpClient, rootUrl: string, params: DownloadPublicLinkDatei$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, downloadPublicLinkDatei.PATH, 'get');
  if (params) {
    rb.path('accessToken', params.accessToken, {});
    rb.path('dateiId', params.dateiId, {});
    rb.header('X-Datei-Link-Code', params['X-Datei-Link-Code'], {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'application/octet-stream', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

downloadPublicLinkDatei.PATH = '/api/v1/public/links/{accessToken}/dateien/{dateiId}/download';
