/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnableMfaRequest } from '../../models/enable-mfa-request';
import { EnableMfaResponse } from '../../models/enable-mfa-response';

export interface EnableMfa$Params {
      body: EnableMfaRequest
}

export function enableMfa(http: HttpClient, rootUrl: string, params: EnableMfa$Params, context?: HttpContext): Observable<StrictHttpResponse<EnableMfaResponse>> {
  const rb = new RequestBuilder(rootUrl, enableMfa.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EnableMfaResponse>;
    })
  );
}

enableMfa.PATH = '/api/v1/settings/mfa/enable';
