/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MfaRecoveryCodesStatusResponse } from '../../models/mfa-recovery-codes-status-response';

export interface GetMfaRecoveryCodesStatus$Params {
}

export function getMfaRecoveryCodesStatus(http: HttpClient, rootUrl: string, params?: GetMfaRecoveryCodesStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<MfaRecoveryCodesStatusResponse>> {
  const rb = new RequestBuilder(rootUrl, getMfaRecoveryCodesStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MfaRecoveryCodesStatusResponse>;
    })
  );
}

getMfaRecoveryCodesStatus.PATH = '/api/v1/settings/mfa/recovery-codes/status';
