/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MailAccount } from '../../models/mail-account';

export interface GetMailAccount$Params {
  accountId: string;
}

export function getMailAccount(http: HttpClient, rootUrl: string, params: GetMailAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<MailAccount>> {
  const rb = new RequestBuilder(rootUrl, getMailAccount.PATH, 'get');
  if (params) {
    rb.path('accountId', params.accountId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MailAccount>;
    })
  );
}

getMailAccount.PATH = '/api/v1/settings/mail/accounts/{accountId}';
