/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FilePathItem } from '../../models/file-path-item';

export interface GetFilePath$Params {

/**
 * File ID
 */
  id: string;
}

export function getFilePath(http: HttpClient, rootUrl: string, params: GetFilePath$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FilePathItem>>> {
  const rb = new RequestBuilder(rootUrl, getFilePath.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FilePathItem>>;
    })
  );
}

getFilePath.PATH = '/api/v1/files/{id}/path';
