/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LoginConfigResponse } from '../../models/login-config-response';

export interface GetLoginConfig$Params {
}

export function getLoginConfig(http: HttpClient, rootUrl: string, params?: GetLoginConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<LoginConfigResponse>> {
  const rb = new RequestBuilder(rootUrl, getLoginConfig.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LoginConfigResponse>;
    })
  );
}

getLoginConfig.PATH = '/api/v1/auth/login/config';
