/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetFileThumbnail$Params {

/**
 * File ID
 */
  id: string;
  'If-None-Match'?: string;
}

export function getFileThumbnail(http: HttpClient, rootUrl: string, params: GetFileThumbnail$Params, context?: HttpContext): Observable<StrictHttpResponse<any>> {
  const rb = new RequestBuilder(rootUrl, getFileThumbnail.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('If-None-Match', params['If-None-Match'], {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: 'image/jpeg', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<any>;
    })
  );
}

getFileThumbnail.PATH = '/api/v1/files/{id}/thumbnail';
