/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListEmailsResponse } from '../../models/list-emails-response';

export interface ListEmails$Params {
}

export function listEmails(http: HttpClient, rootUrl: string, params?: ListEmails$Params, context?: HttpContext): Observable<StrictHttpResponse<ListEmailsResponse>> {
  const rb = new RequestBuilder(rootUrl, listEmails.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListEmailsResponse>;
    })
  );
}

listEmails.PATH = '/api/v1/settings/emails';
