/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListPersonalAccessTokensResponse } from '../../models/list-personal-access-tokens-response';

export interface ListPersonalAccessTokens$Params {
}

export function listPersonalAccessTokens(http: HttpClient, rootUrl: string, params?: ListPersonalAccessTokens$Params, context?: HttpContext): Observable<StrictHttpResponse<ListPersonalAccessTokensResponse>> {
  const rb = new RequestBuilder(rootUrl, listPersonalAccessTokens.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListPersonalAccessTokensResponse>;
    })
  );
}

listPersonalAccessTokens.PATH = '/api/v1/settings/tokens';
