/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListMailRulesResponse } from '../../models/list-mail-rules-response';

export interface ListAllMailRules$Params {

/**
 * Maximum number of results
 */
  limit?: number;

/**
 * Number of results to skip
 */
  offset?: number;
}

export function listAllMailRules(http: HttpClient, rootUrl: string, params?: ListAllMailRules$Params, context?: HttpContext): Observable<StrictHttpResponse<ListMailRulesResponse>> {
  const rb = new RequestBuilder(rootUrl, listAllMailRules.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListMailRulesResponse>;
    })
  );
}

listAllMailRules.PATH = '/api/v1/settings/mail/rules';
