/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListAdminUsersResponse } from '../../models/list-admin-users-response';

export interface ListUsersAdmin$Params {

/**
 * Maximum number of results
 */
  limit?: number;

/**
 * Number of results to skip
 */
  offset?: number;
}

export function listUsersAdmin(http: HttpClient, rootUrl: string, params?: ListUsersAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<ListAdminUsersResponse>> {
  const rb = new RequestBuilder(rootUrl, listUsersAdmin.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListAdminUsersResponse>;
    })
  );
}

listUsersAdmin.PATH = '/api/v1/admin/users';
