/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListPublicLinkDateienResponse } from '../../models/list-public-link-dateien-response';

export interface ListPublicLinkDateien$Params {

/**
 * When set, list children of this folder (must be inside the link's shared scope); when omitted, list the top-level shared dateien
 */
  parentId?: string;
}

export function listPublicLinkDateien(http: HttpClient, rootUrl: string, params?: ListPublicLinkDateien$Params, context?: HttpContext): Observable<StrictHttpResponse<ListPublicLinkDateienResponse>> {
  const rb = new RequestBuilder(rootUrl, listPublicLinkDateien.PATH, 'get');
  if (params) {
    rb.query('parentId', params.parentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListPublicLinkDateienResponse>;
    })
  );
}

listPublicLinkDateien.PATH = '/api/v1/public/dateien';
