/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListTrashResponse } from '../../models/list-trash-response';

export interface ListTrash$Params {

/**
 * Browse contents of a specific trashed directory. Omit to list root-level trashed items.
 */
  parentId?: string;

/**
 * Maximum number of results
 */
  limit?: number;

/**
 * Number of results to skip
 */
  offset?: number;
}

export function listTrash(http: HttpClient, rootUrl: string, params?: ListTrash$Params, context?: HttpContext): Observable<StrictHttpResponse<ListTrashResponse>> {
  const rb = new RequestBuilder(rootUrl, listTrash.PATH, 'get');
  if (params) {
    rb.query('parentId', params.parentId, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListTrashResponse>;
    })
  );
}

listTrash.PATH = '/api/v1/trash';
