/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListFilesResponse } from '../../models/list-files-response';

export interface ListTrashChildren$Params {
  fileId: string;

/**
 * Maximum number of results
 */
  limit?: number;

/**
 * Number of results to skip
 */
  offset?: number;
}

export function listTrashChildren(http: HttpClient, rootUrl: string, params: ListTrashChildren$Params, context?: HttpContext): Observable<StrictHttpResponse<ListFilesResponse>> {
  const rb = new RequestBuilder(rootUrl, listTrashChildren.PATH, 'get');
  if (params) {
    rb.path('fileId', params.fileId, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListFilesResponse>;
    })
  );
}

listTrashChildren.PATH = '/api/v1/trash/{fileId}/children';
