/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListEmailsResponse } from '../../models/list-emails-response';

export interface ListUserEmailsAdmin$Params {
  id: string;
}

export function listUserEmailsAdmin(http: HttpClient, rootUrl: string, params: ListUserEmailsAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<ListEmailsResponse>> {
  const rb = new RequestBuilder(rootUrl, listUserEmailsAdmin.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListEmailsResponse>;
    })
  );
}

listUserEmailsAdmin.PATH = '/api/v1/admin/users/{id}/emails';
