/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListLinksResponse } from '../../models/list-links-response';

export interface ListLinks$Params {

/**
 * Filter by link status; omit to return all
 */
  status?: 'active' | 'expired' | 'revoked';

/**
 * Maximum number of results
 */
  limit?: number;

/**
 * Number of results to skip
 */
  offset?: number;
}

export function listLinks(http: HttpClient, rootUrl: string, params?: ListLinks$Params, context?: HttpContext): Observable<StrictHttpResponse<ListLinksResponse>> {
  const rb = new RequestBuilder(rootUrl, listLinks.PATH, 'get');
  if (params) {
    rb.query('status', params.status, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListLinksResponse>;
    })
  );
}

listLinks.PATH = '/api/v1/links';
