/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListDateiResponse } from '../../models/list-datei-response';

export interface ListDatei$Params {

/**
 * Parent directory ID (omit for root)
 */
  parentId?: string;

/**
 * Maximum number of results
 */
  limit?: number;

/**
 * Number of results to skip
 */
  offset?: number;
}

export function listDatei(http: HttpClient, rootUrl: string, params?: ListDatei$Params, context?: HttpContext): Observable<StrictHttpResponse<ListDateiResponse>> {
  const rb = new RequestBuilder(rootUrl, listDatei.PATH, 'get');
  if (params) {
    rb.query('parentId', params.parentId, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListDateiResponse>;
    })
  );
}

listDatei.PATH = '/api/v1/datei';
