/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ListPublicLinkFilesResponse } from '../../models/list-public-link-files-response';

export interface ListPublicLinkFiles$Params {

/**
 * When set, list children of this folder (must be inside the link's shared scope); when omitted, list the top-level shared files
 */
  parentId?: string;
}

export function listPublicLinkFiles(http: HttpClient, rootUrl: string, params?: ListPublicLinkFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<ListPublicLinkFilesResponse>> {
  const rb = new RequestBuilder(rootUrl, listPublicLinkFiles.PATH, 'get');
  if (params) {
    rb.query('parentId', params.parentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ListPublicLinkFilesResponse>;
    })
  );
}

listPublicLinkFiles.PATH = '/api/v1/public/files';
