/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegenerateMfaRecoveryCodesRequest } from '../../models/regenerate-mfa-recovery-codes-request';
import { RegenerateMfaRecoveryCodesResponse } from '../../models/regenerate-mfa-recovery-codes-response';

export interface RegenerateMfaRecoveryCodes$Params {
      body: RegenerateMfaRecoveryCodesRequest
}

export function regenerateMfaRecoveryCodes(http: HttpClient, rootUrl: string, params: RegenerateMfaRecoveryCodes$Params, context?: HttpContext): Observable<StrictHttpResponse<RegenerateMfaRecoveryCodesResponse>> {
  const rb = new RequestBuilder(rootUrl, regenerateMfaRecoveryCodes.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegenerateMfaRecoveryCodesResponse>;
    })
  );
}

regenerateMfaRecoveryCodes.PATH = '/api/v1/settings/mfa/recovery-codes/regenerate';
