/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SetupMfaResponse } from '../../models/setup-mfa-response';

export interface SetupMfa$Params {
}

export function setupMfa(http: HttpClient, rootUrl: string, params?: SetupMfa$Params, context?: HttpContext): Observable<StrictHttpResponse<SetupMfaResponse>> {
  const rb = new RequestBuilder(rootUrl, setupMfa.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SetupMfaResponse>;
    })
  );
}

setupMfa.PATH = '/api/v1/settings/mfa/setup';
