/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UnlockPublicLinkRequest } from '../../models/unlock-public-link-request';
import { UnlockPublicLinkResponse } from '../../models/unlock-public-link-response';

export interface UnlockPublicLink$Params {
  key: string;
      body?: UnlockPublicLinkRequest
}

export function unlockPublicLink(http: HttpClient, rootUrl: string, params: UnlockPublicLink$Params, context?: HttpContext): Observable<StrictHttpResponse<UnlockPublicLinkResponse>> {
  const rb = new RequestBuilder(rootUrl, unlockPublicLink.PATH, 'post');
  if (params) {
    rb.path('key', params.key, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UnlockPublicLinkResponse>;
    })
  );
}

unlockPublicLink.PATH = '/api/v1/public/links/{key}/unlock';
