/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MailRule } from '../../models/mail-rule';
import { UpdateMailRuleRequest } from '../../models/update-mail-rule-request';

export interface UpdateMailRule$Params {
  ruleId: string;
      body: UpdateMailRuleRequest
}

export function updateMailRule(http: HttpClient, rootUrl: string, params: UpdateMailRule$Params, context?: HttpContext): Observable<StrictHttpResponse<MailRule>> {
  const rb = new RequestBuilder(rootUrl, updateMailRule.PATH, 'put');
  if (params) {
    rb.path('ruleId', params.ruleId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MailRule>;
    })
  );
}

updateMailRule.PATH = '/api/v1/settings/mail/rules/{ruleId}';
