/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DateiResponse } from '../../models/datei-response';
import { UpdateDateiRequest } from '../../models/update-datei-request';

export interface UpdateDatei$Params {

/**
 * Datei ID
 */
  id: string;
      body: UpdateDateiRequest
}

export function updateDatei(http: HttpClient, rootUrl: string, params: UpdateDatei$Params, context?: HttpContext): Observable<StrictHttpResponse<DateiResponse>> {
  const rb = new RequestBuilder(rootUrl, updateDatei.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DateiResponse>;
    })
  );
}

updateDatei.PATH = '/api/v1/datei/{id}';
