/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { File } from '../../models/file';
import { UpdateFileRequest } from '../../models/update-file-request';

export interface UpdateFile$XWwwFormUrlencoded$Params {

/**
 * File ID
 */
  id: string;
      body: UpdateFileRequest
}

export function updateFile$XWwwFormUrlencoded(http: HttpClient, rootUrl: string, params: UpdateFile$XWwwFormUrlencoded$Params, context?: HttpContext): Observable<StrictHttpResponse<File>> {
  const rb = new RequestBuilder(rootUrl, updateFile$XWwwFormUrlencoded.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/x-www-form-urlencoded');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<File>;
    })
  );
}

updateFile$XWwwFormUrlencoded.PATH = '/api/v1/files/{id}';
