post:
  operationId: ConfirmResetPassword
  summary: Set a new password using a password reset token
  x-required-action: reset-password
  security:
    - bearerHttpAuthentication: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../components/schemas/ConfirmResetPasswordRequest.yaml'
  responses:
    '204':
      description: Password reset successful
    '400':
      description: Invalid input
    '403':
      description: Invalid or expired reset token
