post:
  operationId: ConfirmEmailVerification
  summary: Confirm email verification
  x-required-action: verify-email
  security:
    - bearerHttpAuthentication: []
  responses:
    '204':
      description: Email verified
    '403':
      description: Invalid or expired verification token
