post:
  operationId: ConfirmEmailVerification
  summary: Confirm email verification
  security:
    - bearerHttpAuthentication: []
  responses:
    '204':
      description: Email verified
    '400':
      description: Invalid verification
