get:
  operationId: GetCurrentUser
  summary: Get the current user's profile
  security:
    - bearerHttpAuthentication: []
  responses:
    '200':
      description: Current user profile
      content:
        application/json:
          schema:
            $ref: '../components/schemas/UserResponse.yaml'
post:
  operationId: UpdateUser
  summary: Update user name or password
  security:
    - bearerHttpAuthentication: []
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../components/schemas/UpdateUserRequest.yaml'
  responses:
    '200':
      description: User updated
      content:
        application/json:
          schema:
            $ref: '../components/schemas/UserResponse.yaml'
    '400':
      description: Invalid input
    '401':
      description: Invalid current password
