# yaml-language-server: $schema=https://spec.openapis.org/oas/3.0/schema/2024-10-18
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Datei API
paths:
  /api/v1/ping:
    get:
      responses:
        "200":
          description: pet response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Ping"
      responses:
        "200":
          description: pet response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"
components:
  schemas:
    Ping:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
    # base types
    Pong:
      type: object
      required:
        - ping
      properties:
        ping:
          type: string
          example: pong
