[settings]
env_shell_expand = false

[tools]
go = "1.26.1"
golangci-lint = "2.11.1"
ko = "0.18.1"
node = "24"
pnpm = "10.30.3"
github-cli = "2.87.3"

[env]
_.source = ['hack/current-commit.sh']
_.file = ".env.local"
VERSION = 'snapshot'
CGO_ENABLED = "0"

[vars]
ldflags = "-s -w -X github.com/godatei/datei/internal/buildconfig.version=$VERSION -X github.com/godatei/datei/internal/buildconfig.commit=$COMMIT"

[tasks."deps:backend"]
run = 'go mod tidy'

[tasks."deps:frontend"]
run = 'pnpm install'
sources = ["package.json", "pnpm-lock.yaml"]
outputs = ["node_modules/**/*"]

[tasks."generate:openapi"]
run = 'pnpm run generate-openapi-bundle'
depends = "deps:frontend"
sources = ["api/**/*.yaml"]
outputs = ["dist/openapi.yaml"]

[tasks."generate:backend"]
run = 'go generate ./...'
depends = ["deps:backend", "generate:openapi"]


[tasks."generate:frontend"]
run = 'pnpm run generate-openapi-client'
depends = ["deps:frontend", "generate:openapi"]
sources = ["dist/openapi.yaml"]
outputs = ["frontend/src/api/**/*"]

[tasks.generate]
run = { tasks = ["generate:backend", "generate:frontend"] }

[tasks."build:frontend:dev"]
run = 'pnpm build:dev'
depends = "generate:frontend"
sources = ["node_modules/**/*", "frontend/**/*"]

[tasks."build:frontend"]
run = 'pnpm build'
depends = "generate:frontend"

[tasks."build:datei"]
run = 'go build -ldflags="{{vars.ldflags}}" -o dist/datei .'
depends = ["generate:backend", "build:frontend"]

[tasks."build:container"]
depends = "build:datei"
run = "docker build -t ghcr.io/godatei/datei:snapshot ."

[tasks."lint:backend"]
depends = ["generate:backend"]
run = 'golangci-lint run'

[tasks."lint:frontend"]
run = 'pnpm lint'

[tasks.lint]
run = { tasks = ["lint:frontend", "lint:backend"] }

[tasks."test:backend"]
run = 'go test ./...'
depends = ["generate:backend"]
description = 'Run all Go tests'

[tasks."test:frontend"]
run = 'pnpm run test'
depends = "generate:frontend"

[tasks.test]
run = { tasks = ["test:backend", "test:frontend"] }

[tasks."format:backend"]
run = 'golangci-lint run --fix'

[tasks."format:frontend"]
run = 'pnpm format'

[tasks.format]
run = { tasks = ["format:frontend", "format:backend"] }

[tasks."run:datei:serve"]
alias = "serve"
run = 'go run -ldflags="{{vars.ldflags}}" . serve'
depends = ["generate:backend", "build:frontend:dev"]
sources = ["api/**/*.go", "cmd/**/*.go", "internal/**/*.go"]

[tasks."run:datei:migrate"]
run = 'go run -ldflags="{{vars.ldflags}}" . migrate'
description = 'Migrate the database to the latest schema version. Protip: `mise run:datei:migrate -- --to xx` to migrate to a specific version'

[tasks."import-db-schema"]
run = 'podman compose exec --no-tty postgres pg_dump datei --user=local --section=pre-data --no-owner --no-privileges --exclude-table=schema_migrations | grep --invert-match "^\\\\" > internal/db/schema.sql'
