// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	. "github.com/godatei/datei/pkg/api"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all Datei
	// (GET /api/v1/datei)
	ListDatei(w http.ResponseWriter, r *http.Request, params ListDateiParams)
	// Create a new Datei
	// (POST /api/v1/datei)
	CreateDatei(w http.ResponseWriter, r *http.Request)
	// Delete a Datei
	// (DELETE /api/v1/datei/{id})
	DeleteDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a Datei
	// (PATCH /api/v1/datei/{id})
	UpdateDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Download a Datei
	// (GET /api/v1/datei/{id}/download)
	DownloadDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all Datei
// (GET /api/v1/datei)
func (_ Unimplemented) ListDatei(w http.ResponseWriter, r *http.Request, params ListDateiParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new Datei
// (POST /api/v1/datei)
func (_ Unimplemented) CreateDatei(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a Datei
// (DELETE /api/v1/datei/{id})
func (_ Unimplemented) DeleteDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a Datei
// (PATCH /api/v1/datei/{id})
func (_ Unimplemented) UpdateDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download a Datei
// (GET /api/v1/datei/{id}/download)
func (_ Unimplemented) DownloadDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDatei operation middleware
func (siw *ServerInterfaceWrapper) ListDatei(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerHttpAuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDateiParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDatei(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDatei operation middleware
func (siw *ServerInterfaceWrapper) CreateDatei(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerHttpAuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDatei(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDatei operation middleware
func (siw *ServerInterfaceWrapper) DeleteDatei(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerHttpAuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDatei(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDatei operation middleware
func (siw *ServerInterfaceWrapper) UpdateDatei(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerHttpAuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDatei(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadDatei operation middleware
func (siw *ServerInterfaceWrapper) DownloadDatei(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerHttpAuthenticationScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadDatei(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/datei", wrapper.ListDatei)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/datei", wrapper.CreateDatei)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/datei/{id}", wrapper.DeleteDatei)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/datei/{id}", wrapper.UpdateDatei)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/datei/{id}/download", wrapper.DownloadDatei)
	})

	return r
}

type ListDateiRequestObject struct {
	Params ListDateiParams
}

type ListDateiResponseObject interface {
	VisitListDateiResponse(w http.ResponseWriter) error
}

type ListDatei200JSONResponse ListDateiResponse

func (response ListDatei200JSONResponse) VisitListDateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDatei400Response struct {
}

func (response ListDatei400Response) VisitListDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateDateiRequestObject struct {
	Body *multipart.Reader
}

type CreateDateiResponseObject interface {
	VisitCreateDateiResponse(w http.ResponseWriter) error
}

type CreateDatei201JSONResponse Datei

func (response CreateDatei201JSONResponse) VisitCreateDateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatei400Response struct {
}

func (response CreateDatei400Response) VisitCreateDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateDatei409Response struct {
}

func (response CreateDatei409Response) VisitCreateDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type DeleteDateiRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteDateiResponseObject interface {
	VisitDeleteDateiResponse(w http.ResponseWriter) error
}

type DeleteDatei204Response struct {
}

func (response DeleteDatei204Response) VisitDeleteDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDatei404Response struct {
}

func (response DeleteDatei404Response) VisitDeleteDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DeleteDatei409Response struct {
}

func (response DeleteDatei409Response) VisitDeleteDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type UpdateDateiRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *multipart.Reader
}

type UpdateDateiResponseObject interface {
	VisitUpdateDateiResponse(w http.ResponseWriter) error
}

type UpdateDatei200JSONResponse Datei

func (response UpdateDatei200JSONResponse) VisitUpdateDateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateDatei400Response struct {
}

func (response UpdateDatei400Response) VisitUpdateDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateDatei404Response struct {
}

func (response UpdateDatei404Response) VisitUpdateDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DownloadDateiRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DownloadDateiResponseObject interface {
	VisitDownloadDateiResponse(w http.ResponseWriter) error
}

type DownloadDatei200ResponseHeaders struct {
	ContentDisposition string
	ContentType        string
}

type DownloadDatei200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadDatei200ResponseHeaders
	ContentLength int64
}

func (response DownloadDatei200ApplicationoctetStreamResponse) VisitDownloadDateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadDatei404Response struct {
}

func (response DownloadDatei404Response) VisitDownloadDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DownloadDatei409Response struct {
}

func (response DownloadDatei409Response) VisitDownloadDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all Datei
	// (GET /api/v1/datei)
	ListDatei(ctx context.Context, request ListDateiRequestObject) (ListDateiResponseObject, error)
	// Create a new Datei
	// (POST /api/v1/datei)
	CreateDatei(ctx context.Context, request CreateDateiRequestObject) (CreateDateiResponseObject, error)
	// Delete a Datei
	// (DELETE /api/v1/datei/{id})
	DeleteDatei(ctx context.Context, request DeleteDateiRequestObject) (DeleteDateiResponseObject, error)
	// Update a Datei
	// (PATCH /api/v1/datei/{id})
	UpdateDatei(ctx context.Context, request UpdateDateiRequestObject) (UpdateDateiResponseObject, error)
	// Download a Datei
	// (GET /api/v1/datei/{id}/download)
	DownloadDatei(ctx context.Context, request DownloadDateiRequestObject) (DownloadDateiResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListDatei operation middleware
func (sh *strictHandler) ListDatei(w http.ResponseWriter, r *http.Request, params ListDateiParams) {
	var request ListDateiRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDatei(ctx, request.(ListDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDateiResponseObject); ok {
		if err := validResponse.VisitListDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDatei operation middleware
func (sh *strictHandler) CreateDatei(w http.ResponseWriter, r *http.Request) {
	var request CreateDateiRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDatei(ctx, request.(CreateDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDateiResponseObject); ok {
		if err := validResponse.VisitCreateDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDatei operation middleware
func (sh *strictHandler) DeleteDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteDateiRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDatei(ctx, request.(DeleteDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDateiResponseObject); ok {
		if err := validResponse.VisitDeleteDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDatei operation middleware
func (sh *strictHandler) UpdateDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateDateiRequestObject

	request.Id = id

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDatei(ctx, request.(UpdateDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateDateiResponseObject); ok {
		if err := validResponse.VisitUpdateDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadDatei operation middleware
func (sh *strictHandler) DownloadDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DownloadDateiRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadDatei(ctx, request.(DownloadDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadDateiResponseObject); ok {
		if err := validResponse.VisitDownloadDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYX2/bNhD/KgS3hxRQYmcrBsxvab1iGdquWNP1IcgDLZ2saySSIU/x3MDffSAp2bJE",
	"xV7abntqQx3v3+/ud0c/8FRVWkmQZPnsgdu0gEr4/740IAjmggD/gLsaLLlTbZQGQwheJscS3L8Z2NSg",
	"JlSSz/grLIFlggQ7Uf5MlAlTFRLLlWEZGkhJGQT7jCc8V6YSxGd8gVKYNU84rTXwGbdkUC75JuFSVBEr",
	"b0UFXiEVwCSsmHd1eH+TcAN3NRrI+Ow6KLvZSqnFJ0jJWQnXByGmPg3ZBQ098BlCJRlhBZZEpbvxZILg",
	"1H2JhdRofbEeav1gwbDLOVM581LKdLXWNWY84bIuS7FwySdTQ8QAZhHNEu9qYJiBJMwRYoqHiuy8ASzi",
	"68cCqAAHAVqGloktuh0gF0qVIKRTVgoCS3+Csf7+Axdl+XvOZ9cP/HsDOZ/x7ya7gpw01Tjx0LS3NjdJ",
	"z4vXXiu7DwKTWpdKZC5/rjJ8iY4mbAd/ifIWMm/pMpK7AEgQCpXGTlzx2XXlDvdL+ViQ4oX9sjYGJDH3",
	"tY2ire2DKrVwd2MRvPNfdgCxy/lTfCYjbBHvhyv36XAzHGviseZYFYo1YgzpKXHUOhvr69fCEgvf/3Fr",
	"99jG+9JtoaRDKF0nRhmp0yw9YiogvbV1NcK/288x9lGSQNKbSJW8EeY2UyvJGhmmDdwjrI5J6SNU2UQR",
	"GO1bUmZofngSZzqqeI+fxyaaxc/AULLFmsB29aOkn57vXEZJsAQzxsJtKqLtN/Cpwgqu/OEAqcs3vzAv",
	"f1QRboNLeKc0tuq76MVq8TVaanYBq5W0MCxIJKjs0M8LY8TaQRNYM6h0+dvKH6R+TwrBI+G0+b8ViTLC",
	"Qe6YybpagHFGvRF2soBcGWBaLFH6AnwWwaufNu9faymWlA++fZ+yIr2FlZ9MvTXpyxYiWIWZ0S5FzZjq",
	"Kh8WSi+oTcItpLVBWr93EIQgFiAMmF+J9EVNhVsfUkENK4Vvr1qvf/t4xfsD+oUXYaRuQbLaolwywYKg",
	"xxm2MjsXCyLNN84flLlyhgjJpTLQIrt4d8kTft+yIz8/m55NXXKUBik08hn/0R+5mUiFD2MiNE7uzydZ",
	"u+otwSPm8PLxuLm5K3V/1YgKCIz1S0qfK//Cqq461WbA1mUobidwV4MHMODFS6z8rAq1HQDMRV0Sn51P",
	"p7F6HEDct8RIMXuLesSiynMLIyZjBm9cB4T+9gn7YTr1oybMAr+waV024E8+2VABO+WPdfKQQTy6vdGL",
	"lrZc4dB8HjzoLWPyXpSYMR8t62Dky7euKtc3jTJRljttWtkI4J2XDg8UAJZeqGzdi72qS0ItDE1cj566",
	"1j0+/MhzarPPOG4qbQYAnH81AJosDJMeGqrhf2brNAVr87os1wcRMG0oTu7nyC6rZF5iSuwEzpZnCdP9",
	"JVQq9yqsZfasB17IFxOdp50T2GvhyQNmm2C0BIIhsnN/flQzhyT4oew7yZHGrpH8CN2HqttUB8Z4pK+e",
	"D3MVPAihxGAYvbLN4TgMQjqhoLvFYh8EqDSt+yCE/DHR6SBBaTFMdGcS/veJ/ib9G5n1R/Xv9N/q3+Yt",
	"8QX9e0yB7ZVHyMmuPKL9OXHPCbeUjw7ceSPwf+zTx+BTKQGdWjIg3CtsCEx4iDWXE16Ae5mEH9fC4ekc",
	"rVYW212qtzkTibSoHGGGq2yFVPi90YfbjWy42LUmDrweer+TjGvcfC0SatBuaWj/Z6MBA7XSuyLrrKi+",
	"PsaX0+ubzc3m7wAAAP//wdObe+MUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
