// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	. "github.com/godatei/datei/pkg/api"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all Datei
	// (GET /api/v1/datei)
	GetApiV1Datei(w http.ResponseWriter, r *http.Request, params GetApiV1DateiParams)
	// Create a new Datei
	// (POST /api/v1/datei)
	PostApiV1Datei(w http.ResponseWriter, r *http.Request)
	// Delete a Datei
	// (DELETE /api/v1/datei/{id})
	DeleteApiV1DateiId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a Datei
	// (PATCH /api/v1/datei/{id})
	PatchApiV1DateiId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Download a Datei
	// (GET /api/v1/datei/{id}/download)
	GetApiV1DateiIdDownload(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all Datei
// (GET /api/v1/datei)
func (_ Unimplemented) GetApiV1Datei(w http.ResponseWriter, r *http.Request, params GetApiV1DateiParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new Datei
// (POST /api/v1/datei)
func (_ Unimplemented) PostApiV1Datei(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a Datei
// (DELETE /api/v1/datei/{id})
func (_ Unimplemented) DeleteApiV1DateiId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a Datei
// (PATCH /api/v1/datei/{id})
func (_ Unimplemented) PatchApiV1DateiId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download a Datei
// (GET /api/v1/datei/{id}/download)
func (_ Unimplemented) GetApiV1DateiIdDownload(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetApiV1Datei operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Datei(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1DateiParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1Datei(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiV1Datei operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Datei(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiV1Datei(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiV1DateiId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1DateiId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiV1DateiId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchApiV1DateiId operation middleware
func (siw *ServerInterfaceWrapper) PatchApiV1DateiId(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchApiV1DateiId(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiV1DateiIdDownload operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1DateiIdDownload(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiV1DateiIdDownload(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/datei", wrapper.GetApiV1Datei)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/datei", wrapper.PostApiV1Datei)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/datei/{id}", wrapper.DeleteApiV1DateiId)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/datei/{id}", wrapper.PatchApiV1DateiId)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/datei/{id}/download", wrapper.GetApiV1DateiIdDownload)
	})

	return r
}

type GetApiV1DateiRequestObject struct {
	Params GetApiV1DateiParams
}

type GetApiV1DateiResponseObject interface {
	VisitGetApiV1DateiResponse(w http.ResponseWriter) error
}

type GetApiV1Datei200JSONResponse ListDateiResponse

func (response GetApiV1Datei200JSONResponse) VisitGetApiV1DateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetApiV1Datei400Response struct {
}

func (response GetApiV1Datei400Response) VisitGetApiV1DateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostApiV1DateiRequestObject struct {
	Body *multipart.Reader
}

type PostApiV1DateiResponseObject interface {
	VisitPostApiV1DateiResponse(w http.ResponseWriter) error
}

type PostApiV1Datei201JSONResponse DateiResponse

func (response PostApiV1Datei201JSONResponse) VisitPostApiV1DateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type PostApiV1Datei400Response struct {
}

func (response PostApiV1Datei400Response) VisitPostApiV1DateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PostApiV1Datei409Response struct {
}

func (response PostApiV1Datei409Response) VisitPostApiV1DateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type DeleteApiV1DateiIdRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteApiV1DateiIdResponseObject interface {
	VisitDeleteApiV1DateiIdResponse(w http.ResponseWriter) error
}

type DeleteApiV1DateiId204Response struct {
}

func (response DeleteApiV1DateiId204Response) VisitDeleteApiV1DateiIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteApiV1DateiId404Response struct {
}

func (response DeleteApiV1DateiId404Response) VisitDeleteApiV1DateiIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DeleteApiV1DateiId409Response struct {
}

func (response DeleteApiV1DateiId409Response) VisitDeleteApiV1DateiIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type PatchApiV1DateiIdRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *multipart.Reader
}

type PatchApiV1DateiIdResponseObject interface {
	VisitPatchApiV1DateiIdResponse(w http.ResponseWriter) error
}

type PatchApiV1DateiId200JSONResponse DateiResponse

func (response PatchApiV1DateiId200JSONResponse) VisitPatchApiV1DateiIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PatchApiV1DateiId400Response struct {
}

func (response PatchApiV1DateiId400Response) VisitPatchApiV1DateiIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type PatchApiV1DateiId404Response struct {
}

func (response PatchApiV1DateiId404Response) VisitPatchApiV1DateiIdResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetApiV1DateiIdDownloadRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetApiV1DateiIdDownloadResponseObject interface {
	VisitGetApiV1DateiIdDownloadResponse(w http.ResponseWriter) error
}

type GetApiV1DateiIdDownload200ResponseHeaders struct {
	ContentDisposition string
	ContentType        string
}

type GetApiV1DateiIdDownload200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       GetApiV1DateiIdDownload200ResponseHeaders
	ContentLength int64
}

func (response GetApiV1DateiIdDownload200ApplicationoctetStreamResponse) VisitGetApiV1DateiIdDownloadResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetApiV1DateiIdDownload404Response struct {
}

func (response GetApiV1DateiIdDownload404Response) VisitGetApiV1DateiIdDownloadResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetApiV1DateiIdDownload409Response struct {
}

func (response GetApiV1DateiIdDownload409Response) VisitGetApiV1DateiIdDownloadResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all Datei
	// (GET /api/v1/datei)
	GetApiV1Datei(ctx context.Context, request GetApiV1DateiRequestObject) (GetApiV1DateiResponseObject, error)
	// Create a new Datei
	// (POST /api/v1/datei)
	PostApiV1Datei(ctx context.Context, request PostApiV1DateiRequestObject) (PostApiV1DateiResponseObject, error)
	// Delete a Datei
	// (DELETE /api/v1/datei/{id})
	DeleteApiV1DateiId(ctx context.Context, request DeleteApiV1DateiIdRequestObject) (DeleteApiV1DateiIdResponseObject, error)
	// Update a Datei
	// (PATCH /api/v1/datei/{id})
	PatchApiV1DateiId(ctx context.Context, request PatchApiV1DateiIdRequestObject) (PatchApiV1DateiIdResponseObject, error)
	// Download a Datei
	// (GET /api/v1/datei/{id}/download)
	GetApiV1DateiIdDownload(ctx context.Context, request GetApiV1DateiIdDownloadRequestObject) (GetApiV1DateiIdDownloadResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetApiV1Datei operation middleware
func (sh *strictHandler) GetApiV1Datei(w http.ResponseWriter, r *http.Request, params GetApiV1DateiParams) {
	var request GetApiV1DateiRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1Datei(ctx, request.(GetApiV1DateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1Datei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1DateiResponseObject); ok {
		if err := validResponse.VisitGetApiV1DateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostApiV1Datei operation middleware
func (sh *strictHandler) PostApiV1Datei(w http.ResponseWriter, r *http.Request) {
	var request PostApiV1DateiRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostApiV1Datei(ctx, request.(PostApiV1DateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostApiV1Datei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostApiV1DateiResponseObject); ok {
		if err := validResponse.VisitPostApiV1DateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteApiV1DateiId operation middleware
func (sh *strictHandler) DeleteApiV1DateiId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteApiV1DateiIdRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteApiV1DateiId(ctx, request.(DeleteApiV1DateiIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteApiV1DateiId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteApiV1DateiIdResponseObject); ok {
		if err := validResponse.VisitDeleteApiV1DateiIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchApiV1DateiId operation middleware
func (sh *strictHandler) PatchApiV1DateiId(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PatchApiV1DateiIdRequestObject

	request.Id = id

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchApiV1DateiId(ctx, request.(PatchApiV1DateiIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchApiV1DateiId")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchApiV1DateiIdResponseObject); ok {
		if err := validResponse.VisitPatchApiV1DateiIdResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetApiV1DateiIdDownload operation middleware
func (sh *strictHandler) GetApiV1DateiIdDownload(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetApiV1DateiIdDownloadRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetApiV1DateiIdDownload(ctx, request.(GetApiV1DateiIdDownloadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetApiV1DateiIdDownload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetApiV1DateiIdDownloadResponseObject); ok {
		if err := validResponse.VisitGetApiV1DateiIdDownloadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYX2/bNhD/KgS3hxRwYmctBsxvab0Nxtqi2NruoegDLZ3iaySSIU/x3MDffThSsmWJ",
	"jr20HfrUlDrev9/v/tD3MjOVNRo0eTm9lz5bQqXCny8cKIKZIsA/4bYGT3xqnbHgCCHIFFgC/5uDzxxa",
	"QqPlVP6GJYhckRJnJpypciRMhSQK40SODjIyDsE/kSNZGFcpklO5QK3cWo4krS3IqfTkUF/LzUhqVSWs",
	"vFYVBIW0BKFhJYKrw/ubkXRwW6ODXE4/RGUft1Jm8QkyYitNpN4a7WEYahbSkV/R0JOQKTRaEFbgSVW2",
	"G1euCM75Syq0Ruvz9VDrOw9OzGfCFCJIGdfVWteYy5HUdVmqBYNAroaEAcwTmjXe1iAwB01YIKQUDxX5",
	"WQNcwte/l0BLYCjQC/RCbVHuALowpgSlWVmpCDy9B+fD/Xv5o4NCTuUP4x0dxw0XxwGYVpYvo76BPJzO",
	"E9HFlEWhyAlxxjTx64oP90l3ahrTFHxROweaBH9lo8zEloVHVVrFd1MRvAlfdikU89ljfCan/DLN2Lf8",
	"6ThdTzXxEH1XSyMaMYH0mDhqmx+qvJfKk4jf/3Px9fpC8KVL8lGn5LtOHOwdHTr3WscSshtfVwc65fZz",
	"qj8YTaDpVYIlr5S7yc1Ki0ZGWAd3CKtTUvpAM2uiiD3nWza12pZG5fCorsZz5y/8fGj2ePwMArVYrAl8",
	"Vz9q+vnZzmXUBNfgDvXJNhXJ8hv4VGEFb8PhAKn5q19FkD+JhP7pH8D02wY5kh2KbM10UUxx8iV6OjLT",
	"kKDyQ3+vnFNrhih2z6iS87iVP9qutzY3W88Uaw3/N6TKRE/iY6HragGOjQdj4mwBhXEgrLpGHQj5JIFf",
	"P43Bz9ZSKjnvQjk/Zrl5DStRDBecL1tlYBVnSLvONGOrq3xInF5QfIS6MKyekNj32JfE1Zu5HMm7tj3J",
	"y4vJxYS9MRa0siin8mk44qFEyxD8WFkc312O8zDOpvfyGkKKOEEBBh5c8negK4vvL9uhZ5VTFRA4L6cf",
	"hg3rH6zqqgOxA1+XkVkscFtDyFpMkiyxCgMjEitmrVB1SXJ6OZmkSDDIa9+SICP8DdoDFk1ReDhgMmXw",
	"I9MuEj0k7afJJPT72JD5T2VtiVlI2PiTj8Nhp/yhMhqWb0C4N//Q07ZQGdFn0YPeRqTvVIm5CNGKDkas",
	"0NdVxWRtlKmy3GmzxidAf2P8PuouVtBzk6974Vd1SWiVozHXxjmXzOkZSDxANvuVztNhM8Dg8qthcDT/",
	"sb6aPix8nWXgfVGX5fooGK4NieV+SeyWRhclZiTO4OL6YiRsfynUht9Ttc6f9HCMeROq8yhigb2KHt9j",
	"volGSyAYgjwL5zuY5/mx8o65CLMy1Ba3kl1phcm2j1y3zI5M10SlPRumLHoQI0qhcfDKNpWH0VCahaLu",
	"FpJ9LKCytO5jEdMoVKemFGXLRFHx8feV7m9S1InBe1JRT/7vom4W/i8o6lPotkeWmJsdWZJFO+adnzfn",
	"04byPJ+18t9X/T4EqMkI6NyTA8WPpiFE8d3UXB7JJfBDIv5qFQ/PZ+it8UjNg6y34BKpbFlxP41XxQpp",
	"Gda6EG43suHe1Zo4suy3PwiENfIhjZuv1ZwaoNv2tP87zKAztdI7um02/wYAAP//AAKSWw8UAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
