// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	. "github.com/godatei/datei/pkg/api"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all Datei
	// (GET /api/v1/datei)
	ListDatei(w http.ResponseWriter, r *http.Request, params ListDateiParams)
	// Create a new Datei
	// (POST /api/v1/datei)
	CreateDatei(w http.ResponseWriter, r *http.Request)
	// Delete a Datei
	// (DELETE /api/v1/datei/{id})
	DeleteDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a Datei
	// (PATCH /api/v1/datei/{id})
	UpdateDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Download a Datei
	// (GET /api/v1/datei/{id}/download)
	DownloadDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all Datei
// (GET /api/v1/datei)
func (_ Unimplemented) ListDatei(w http.ResponseWriter, r *http.Request, params ListDateiParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new Datei
// (POST /api/v1/datei)
func (_ Unimplemented) CreateDatei(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a Datei
// (DELETE /api/v1/datei/{id})
func (_ Unimplemented) DeleteDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a Datei
// (PATCH /api/v1/datei/{id})
func (_ Unimplemented) UpdateDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Download a Datei
// (GET /api/v1/datei/{id}/download)
func (_ Unimplemented) DownloadDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDatei operation middleware
func (siw *ServerInterfaceWrapper) ListDatei(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListDateiParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDatei(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDatei operation middleware
func (siw *ServerInterfaceWrapper) CreateDatei(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDatei(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDatei operation middleware
func (siw *ServerInterfaceWrapper) DeleteDatei(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDatei(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDatei operation middleware
func (siw *ServerInterfaceWrapper) UpdateDatei(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDatei(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadDatei operation middleware
func (siw *ServerInterfaceWrapper) DownloadDatei(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadDatei(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/datei", wrapper.ListDatei)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/datei", wrapper.CreateDatei)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/datei/{id}", wrapper.DeleteDatei)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/datei/{id}", wrapper.UpdateDatei)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/datei/{id}/download", wrapper.DownloadDatei)
	})

	return r
}

type ListDateiRequestObject struct {
	Params ListDateiParams
}

type ListDateiResponseObject interface {
	VisitListDateiResponse(w http.ResponseWriter) error
}

type ListDatei200JSONResponse ListDateiResponse

func (response ListDatei200JSONResponse) VisitListDateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListDatei400Response struct {
}

func (response ListDatei400Response) VisitListDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type CreateDateiRequestObject struct {
	Body *multipart.Reader
}

type CreateDateiResponseObject interface {
	VisitCreateDateiResponse(w http.ResponseWriter) error
}

type CreateDatei201JSONResponse Datei

func (response CreateDatei201JSONResponse) VisitCreateDateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatei400JSONResponse struct {
	Message string `json:"message"`
}

func (response CreateDatei400JSONResponse) VisitCreateDateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDatei409Response struct {
}

func (response CreateDatei409Response) VisitCreateDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type DeleteDateiRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteDateiResponseObject interface {
	VisitDeleteDateiResponse(w http.ResponseWriter) error
}

type DeleteDatei204Response struct {
}

func (response DeleteDatei204Response) VisitDeleteDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDatei404Response struct {
}

func (response DeleteDatei404Response) VisitDeleteDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DeleteDatei409Response struct {
}

func (response DeleteDatei409Response) VisitDeleteDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

type UpdateDateiRequestObject struct {
	Id            openapi_types.UUID `json:"id"`
	FormdataBody  *UpdateDateiFormdataRequestBody
	MultipartBody *multipart.Reader
}

type UpdateDateiResponseObject interface {
	VisitUpdateDateiResponse(w http.ResponseWriter) error
}

type UpdateDatei200JSONResponse Datei

func (response UpdateDatei200JSONResponse) VisitUpdateDateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateDatei400Response struct {
}

func (response UpdateDatei400Response) VisitUpdateDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(400)
	return nil
}

type UpdateDatei404Response struct {
}

func (response UpdateDatei404Response) VisitUpdateDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DownloadDateiRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DownloadDateiResponseObject interface {
	VisitDownloadDateiResponse(w http.ResponseWriter) error
}

type DownloadDatei200ResponseHeaders struct {
	ContentDisposition string
	ContentType        string
}

type DownloadDatei200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       DownloadDatei200ResponseHeaders
	ContentLength int64
}

func (response DownloadDatei200ApplicationoctetStreamResponse) VisitDownloadDateiResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.Header().Set("Content-Type", fmt.Sprint(response.Headers.ContentType))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type DownloadDatei404Response struct {
}

func (response DownloadDatei404Response) VisitDownloadDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type DownloadDatei409Response struct {
}

func (response DownloadDatei409Response) VisitDownloadDateiResponse(w http.ResponseWriter) error {
	w.WriteHeader(409)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all Datei
	// (GET /api/v1/datei)
	ListDatei(ctx context.Context, request ListDateiRequestObject) (ListDateiResponseObject, error)
	// Create a new Datei
	// (POST /api/v1/datei)
	CreateDatei(ctx context.Context, request CreateDateiRequestObject) (CreateDateiResponseObject, error)
	// Delete a Datei
	// (DELETE /api/v1/datei/{id})
	DeleteDatei(ctx context.Context, request DeleteDateiRequestObject) (DeleteDateiResponseObject, error)
	// Update a Datei
	// (PATCH /api/v1/datei/{id})
	UpdateDatei(ctx context.Context, request UpdateDateiRequestObject) (UpdateDateiResponseObject, error)
	// Download a Datei
	// (GET /api/v1/datei/{id}/download)
	DownloadDatei(ctx context.Context, request DownloadDateiRequestObject) (DownloadDateiResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListDatei operation middleware
func (sh *strictHandler) ListDatei(w http.ResponseWriter, r *http.Request, params ListDateiParams) {
	var request ListDateiRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListDatei(ctx, request.(ListDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListDateiResponseObject); ok {
		if err := validResponse.VisitListDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDatei operation middleware
func (sh *strictHandler) CreateDatei(w http.ResponseWriter, r *http.Request) {
	var request CreateDateiRequestObject

	if reader, err := r.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDatei(ctx, request.(CreateDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDateiResponseObject); ok {
		if err := validResponse.VisitCreateDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDatei operation middleware
func (sh *strictHandler) DeleteDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteDateiRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDatei(ctx, request.(DeleteDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDateiResponseObject); ok {
		if err := validResponse.VisitDeleteDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateDatei operation middleware
func (sh *strictHandler) UpdateDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateDateiRequestObject

	request.Id = id
	if strings.HasPrefix(r.Header.Get("Content-Type"), "application/x-www-form-urlencoded") {
		if err := r.ParseForm(); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode formdata: %w", err))
			return
		}
		var body UpdateDateiFormdataRequestBody
		if err := runtime.BindForm(&body, r.Form, nil, nil); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't bind formdata: %w", err))
			return
		}
		request.FormdataBody = &body
	}
	if strings.HasPrefix(r.Header.Get("Content-Type"), "multipart/form-data") {
		if reader, err := r.MultipartReader(); err != nil {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode multipart body: %w", err))
			return
		} else {
			request.MultipartBody = reader
		}
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateDatei(ctx, request.(UpdateDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateDateiResponseObject); ok {
		if err := validResponse.VisitUpdateDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DownloadDatei operation middleware
func (sh *strictHandler) DownloadDatei(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DownloadDateiRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DownloadDatei(ctx, request.(DownloadDateiRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DownloadDatei")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DownloadDateiResponseObject); ok {
		if err := validResponse.VisitDownloadDateiResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xYTW/bRhP+K4t934MNyJbcBgWqmxM1qIukCNoEPgQ5rMihODF3l94dWlEN/fdidkmT",
	"EklJddKPk+Xd4Xw/zwz5KBOrS2vAkJfzR+mTHLQKP185UAQLRYC/wX0Fnvi0dLYERwhBJsMC+G8KPnFY",
	"Eloj5/I1FiBSRUqc2XCmiomwGklk1okUHSRkHYI/lxOZWacVyblcolFuIyeSNiXIufTk0KzkdiKN0gNW",
	"flUagkLKQRhYi+Bq//nt04ldfoaEWGMU7YWT5JDc+UqPhNRcizNTFcVQMHyulpwTchUMhJJYQ2Dobdo3",
	"8Va5u9SujahlROngAWF9ktpQq/Sa+mpDGdEaQajBk9JlN+mpIrjgGzmu9eWmr/WDByduFsJmIkhZ19Va",
	"VZie4jYOpOGDwfsKBKZgCDOEIcV9RX5RF2LA19scKAfuE/QCvVBPVet029LaApRhZQWaO0hDi9wMOBij",
	"jkKx58QZt4LfaD7cbepTM6FRw/tw2GuLm7c/CZb/iq4bBtCryjnuM77lkBhHDYaOqiwVPzuUn3fhps2x",
	"uFk8JyMe/xijFr4SaMRyQ+DH0/JkEg398GLcJhqCFTg2Sk75fBhH7/nqOIiOxlWbOASqdW5FLSaQnpO8",
	"qkzH+OCN8iTi/TMooVZ8zPuiNfK8ELYT6eC+QgepnH+U8REVfOpivct83ag/DXD+G/RUTzNfWuOhz/9I",
	"oH0/smvn1IYREtEeVXp2pZH/v4NMzuX/pu00ndajdBoh1U4hxdrC/5ZUMdBofCxMpZfg2GgwIs6WkFkH",
	"olQrNIHQz2W/g/fTFvxrLA0l5UNI2eEhPzJ+YR2ZoxnBNRU2E//8pCIfcugWKWe8/8Xtgx3L+hvI8K7x",
	"TOr8W4Jn0oOkckib37l3YpBLUA7cz0TldUU5D8VERS+au9dNVL/cvpeTPU9fBhFB9g6MqDyalVAiCoYG",
	"hSeZtp1yolJu2R80mWVDhMSBxL1JXL+7kRP5AM5HG1eXs8sZJ8uWYFSJci6/D0c8JigPYUxVidOHq2na",
	"bF4rCBXleoZ4eJS0GA2POqWBwHk5/9hflr6grnQHJg58VURUssB9BbHAoX6yQB1oKIIyFjRTVUFyfjWb",
	"DQGpV/J9S4Ks8HdYjli0WeZhxOSQwU8M3UhMIWHfzWZhJY3LIP9UZVnUxZ9+9rEDWuWHKKhPfaG6e4MB",
	"PT2RHFfzRfRgb/sxD6rAVIRoRadGoX0rrRlXtTJVFK220vqBgndeMmTkLvD00qabvdh1VRCWytGUMXzB",
	"0D49/IE3me0uVTJCt70CXH2zAtRZ6Cc9AqoeYsJXSQLeZ1VRbDoVONmFXXrU4L1aBfY6PF0bwf6A6Dvc",
	"1N81iWQvfxxYLq3JCkxInMHl6nIiyv2t0Fh+HaxMer7XOrFaQnXe6Vhgh0Cmj5huo9ECCPp9tQjnJ1FJ",
	"LEFYUgOOmbJaGIfNY7dRupA+8mYygOoX/VxFD2IoQ00w+shTDsfLoAwLRd1NLXaLALqkzX4RYv6E6uBX",
	"UZL3E92Z1/9+osfYo4uaLxfr9foisEjlCjCJTSE9HckDCxNn7qv46cDOcxJPzf4pnmo2+hGeOoEpTmnl",
	"nUaMuWkbcZAJpqldm8KqdHSxWNQC/0VGOFQ+mxDQhScHSsv5Y78w8cNU/fBE5qDSENQjMzAfXizQl9Zj",
	"szPuvdoQqSTXTM3xUbFGysP+XL9utZH1h0hj4tiXi/rjQtjXD2ncfiu6q6vdEN7uR58e1zXSbZNtt38G",
	"AAD//8iT3NIZFQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
