// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerHttpAuthenticationScopes = "bearerHttpAuthentication.Scopes"
)

// CreateDateiRequest defines model for CreateDateiRequest.
type CreateDateiRequest struct {
	// File File data (optional, omit for directories)
	File *openapi_types.File `json:"file,omitempty"`

	// Name Name for the new Datei
	Name string `json:"name"`
}

// Datei defines model for Datei.
type Datei struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy User ID of creator
	CreatedBy *openapi_types.UUID `json:"createdBy"`

	// Id Unique identifier
	Id openapi_types.UUID `json:"id"`

	// IsDirectory Whether this is a directory
	IsDirectory bool `json:"isDirectory"`

	// LatestVersion Latest version/upload of the file
	LatestVersion *DateiVersion `json:"latestVersion"`

	// LinkedDateiId ID of linked Datei (for symlinks)
	LinkedDateiId *openapi_types.UUID `json:"linkedDateiId"`

	// Name Current name of the Datei
	Name *string `json:"name"`

	// ParentId Parent directory ID
	ParentId *openapi_types.UUID `json:"parentId"`

	// TrashedAt Trash timestamp
	TrashedAt *time.Time `json:"trashedAt"`

	// TrashedBy User ID who trashed it
	TrashedBy *openapi_types.UUID `json:"trashedBy"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

// DateiVersion defines model for DateiVersion.
type DateiVersion struct {
	// Checksum File checksum
	Checksum string `json:"checksum"`

	// ContentMd Markdown content preview
	ContentMd *string `json:"contentMd"`

	// CreatedAt Version creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy User ID of uploader
	CreatedBy *openapi_types.UUID `json:"createdBy"`

	// FileSize File size in bytes
	FileSize int64 `json:"fileSize"`

	// Id Version ID
	Id openapi_types.UUID `json:"id"`

	// MimeType MIME type
	MimeType string `json:"mimeType"`
}

// ListDateiResponse defines model for ListDateiResponse.
type ListDateiResponse struct {
	// Items Array of Datei objects
	Items []Datei `json:"items"`

	// Total Total number of items (before pagination)
	Total int `json:"total"`
}

// UpdateDateiRequest defines model for UpdateDateiRequest.
type UpdateDateiRequest struct {
	// File New file data (optional)
	File *openapi_types.File `json:"file,omitempty"`

	// Name New name for the Datei (optional)
	Name *string `json:"name,omitempty"`
}

// ListDateiParams defines parameters for ListDatei.
type ListDateiParams struct {
	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateDateiMultipartRequestBody defines body for CreateDatei for multipart/form-data ContentType.
type CreateDateiMultipartRequestBody = CreateDateiRequest

// UpdateDateiMultipartRequestBody defines body for UpdateDatei for multipart/form-data ContentType.
type UpdateDateiMultipartRequestBody = UpdateDateiRequest
