// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerHttpAuthenticationScopes       bearerHttpAuthenticationContextKey       = "bearerHttpAuthentication.Scopes"
	PublicLinkBearerAuthenticationScopes publicLinkBearerAuthenticationContextKey = "publicLinkBearerAuthentication.Scopes"
)

// Defines values for CreateMailAccountRequestSecurity.
const (
	CreateMailAccountRequestSecurityNone     CreateMailAccountRequestSecurity = "none"
	CreateMailAccountRequestSecuritySsl      CreateMailAccountRequestSecurity = "ssl"
	CreateMailAccountRequestSecurityStarttls CreateMailAccountRequestSecurity = "starttls"
)

// Valid indicates whether the value is a known member of the CreateMailAccountRequestSecurity enum.
func (e CreateMailAccountRequestSecurity) Valid() bool {
	switch e {
	case CreateMailAccountRequestSecurityNone:
		return true
	case CreateMailAccountRequestSecuritySsl:
		return true
	case CreateMailAccountRequestSecurityStarttls:
		return true
	default:
		return false
	}
}

// Defines values for CreateMailRuleRequestAction.
const (
	CreateMailRuleRequestActionMarkAsRead CreateMailRuleRequestAction = "mark_as_read"
)

// Valid indicates whether the value is a known member of the CreateMailRuleRequestAction enum.
func (e CreateMailRuleRequestAction) Valid() bool {
	switch e {
	case CreateMailRuleRequestActionMarkAsRead:
		return true
	default:
		return false
	}
}

// Defines values for MailAccountSecurity.
const (
	MailAccountSecurityNone     MailAccountSecurity = "none"
	MailAccountSecuritySsl      MailAccountSecurity = "ssl"
	MailAccountSecurityStarttls MailAccountSecurity = "starttls"
)

// Valid indicates whether the value is a known member of the MailAccountSecurity enum.
func (e MailAccountSecurity) Valid() bool {
	switch e {
	case MailAccountSecurityNone:
		return true
	case MailAccountSecuritySsl:
		return true
	case MailAccountSecurityStarttls:
		return true
	default:
		return false
	}
}

// Defines values for MailRuleAction.
const (
	MailRuleActionMarkAsRead MailRuleAction = "mark_as_read"
)

// Valid indicates whether the value is a known member of the MailRuleAction enum.
func (e MailRuleAction) Valid() bool {
	switch e {
	case MailRuleActionMarkAsRead:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMailAccountRequestSecurity.
const (
	None     UpdateMailAccountRequestSecurity = "none"
	Ssl      UpdateMailAccountRequestSecurity = "ssl"
	Starttls UpdateMailAccountRequestSecurity = "starttls"
)

// Valid indicates whether the value is a known member of the UpdateMailAccountRequestSecurity enum.
func (e UpdateMailAccountRequestSecurity) Valid() bool {
	switch e {
	case None:
		return true
	case Ssl:
		return true
	case Starttls:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMailRuleRequestAction.
const (
	MarkAsRead UpdateMailRuleRequestAction = "mark_as_read"
)

// Valid indicates whether the value is a known member of the UpdateMailRuleRequestAction enum.
func (e UpdateMailRuleRequestAction) Valid() bool {
	switch e {
	case MarkAsRead:
		return true
	default:
		return false
	}
}

// Defines values for ListLinksParamsStatus.
const (
	Active  ListLinksParamsStatus = "active"
	Expired ListLinksParamsStatus = "expired"
	Revoked ListLinksParamsStatus = "revoked"
)

// Valid indicates whether the value is a known member of the ListLinksParamsStatus enum.
func (e ListLinksParamsStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Expired:
		return true
	case Revoked:
		return true
	default:
		return false
	}
}

// AddEmailRequest defines model for AddEmailRequest.
type AddEmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// AddFileToLinkRequest defines model for AddFileToLinkRequest.
type AddFileToLinkRequest struct {
	// FileId ID of the file to add to the link
	FileId openapi_types.UUID `json:"fileId"`
}

// AdminCreateUserRequest defines model for AdminCreateUserRequest.
type AdminCreateUserRequest struct {
	Email    openapi_types.Email `json:"email"`
	IsAdmin  bool                `json:"isAdmin"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// AdminResetPasswordRequest defines model for AdminResetPasswordRequest.
type AdminResetPasswordRequest struct {
	Password string `json:"password"`
}

// AdminUpdateUserRequest defines model for AdminUpdateUserRequest.
type AdminUpdateUserRequest struct {
	// Archived When true the account is archived (disabled). Setting false unarchives it.
	Archived *bool   `json:"archived,omitempty"`
	IsAdmin  *bool   `json:"isAdmin,omitempty"`
	Name     *string `json:"name,omitempty"`

	// PrimaryEmailId Promote this email to be the user's primary email.
	PrimaryEmailId *openapi_types.UUID `json:"primaryEmailId,omitempty"`
}

// AdminUserListItem defines model for AdminUserListItem.
type AdminUserListItem struct {
	Archived             bool                 `json:"archived"`
	CreatedAt            time.Time            `json:"createdAt"`
	Id                   openapi_types.UUID   `json:"id"`
	IsAdmin              bool                 `json:"isAdmin"`
	LastLoggedInAt       *time.Time           `json:"lastLoggedInAt,omitempty"`
	MfaEnabled           bool                 `json:"mfaEnabled"`
	Name                 string               `json:"name"`
	PrimaryEmail         *openapi_types.Email `json:"primaryEmail,omitempty"`
	PrimaryEmailVerified *bool                `json:"primaryEmailVerified,omitempty"`
}

// ConfirmResetPasswordRequest defines model for ConfirmResetPasswordRequest.
type ConfirmResetPasswordRequest struct {
	Password string `json:"password"`
}

// CreateFileRequest defines model for CreateFileRequest.
type CreateFileRequest struct {
	// File File data (optional, omit for directories)
	File *openapi_types.File `json:"file,omitempty"`

	// Name Name for the new File
	Name *string `json:"name,omitempty"`

	// ParentId Parent directory ID (omit for root)
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`
}

// CreateLinkRequest defines model for CreateLinkRequest.
type CreateLinkRequest struct {
	// Code Optional plain-text code required to view
	Code *string `json:"code,omitempty"`

	// ExpiresAt Expiration timestamp; omit or null for "never expires"
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// FileIds IDs of files to share (may be empty)
	FileIds []openapi_types.UUID `json:"fileIds"`

	// Name Display name of the link (mandatory, may not be blank)
	Name string `json:"name"`
}

// CreateMailAccountRequest defines model for CreateMailAccountRequest.
type CreateMailAccountRequest struct {
	ImapHost string `json:"imapHost"`
	ImapPort int    `json:"imapPort"`
	Name     string `json:"name"`

	// Password IMAP password; stored encrypted and never returned
	Password string                           `json:"password"`
	Security CreateMailAccountRequestSecurity `json:"security"`
	Username string                           `json:"username"`
}

// CreateMailAccountRequestSecurity defines model for CreateMailAccountRequest.Security.
type CreateMailAccountRequestSecurity string

// CreateMailRuleRequest defines model for CreateMailRuleRequest.
type CreateMailRuleRequest struct {
	// AccountId Account the rule belongs to
	AccountId openapi_types.UUID `json:"accountId"`

	// Action Omit for no action once attachments are consumed
	Action *CreateMailRuleRequestAction `json:"action,omitempty"`

	// AttachmentPattern Comma-separated filename globs (e.g. "*.pdf,*.docx"); empty means all attachments
	AttachmentPattern *string `json:"attachmentPattern,omitempty"`
	Enabled           *bool   `json:"enabled,omitempty"`
	FilterFrom        *string `json:"filterFrom,omitempty"`
	FilterSubject     *string `json:"filterSubject,omitempty"`
	Folder            *string `json:"folder,omitempty"`
	MaxAgeDays        int     `json:"maxAgeDays"`
	Name              string  `json:"name"`
	Order             *int    `json:"order,omitempty"`

	// TargetDirectoryId Directory the attachments are stored in; omit for the account owner's root
	TargetDirectoryId *openapi_types.UUID `json:"targetDirectoryId,omitempty"`
}

// CreateMailRuleRequestAction Omit for no action once attachments are consumed
type CreateMailRuleRequestAction string

// CreatePersonalAccessTokenRequest defines model for CreatePersonalAccessTokenRequest.
type CreatePersonalAccessTokenRequest struct {
	// ExpiresAt Expiration timestamp; omit for "never expires"
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Label Human-readable label describing the token's purpose; omit (or send empty/whitespace-only) for unlabeled tokens
	Label *string `json:"label,omitempty"`
}

// CreatePersonalAccessTokenResponse defines model for CreatePersonalAccessTokenResponse.
type CreatePersonalAccessTokenResponse struct {
	AccessToken PersonalAccessToken `json:"accessToken"`

	// Token The plaintext token (prefixed with "datei-"). Shown only once at creation time; only its hash is stored server-side and it can never be retrieved again.
	Token string `json:"token"`
}

// DisableMFARequest defines model for DisableMFARequest.
type DisableMFARequest struct {
	Password string `json:"password"`
}

// EnableMFARequest defines model for EnableMFARequest.
type EnableMFARequest struct {
	Code string `json:"code"`
}

// EnableMFAResponse defines model for EnableMFAResponse.
type EnableMFAResponse struct {
	RecoveryCodes []string `json:"recoveryCodes"`
}

// File defines model for File.
type File struct {
	// Checksum File checksum (null for directories)
	Checksum *string `json:"checksum,omitempty"`

	// ContentMd Markdown content preview
	ContentMd *string `json:"contentMd,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy User ID of creator
	CreatedBy *openapi_types.UUID `json:"createdBy,omitempty"`

	// Id Unique identifier
	Id openapi_types.UUID `json:"id"`

	// IsDirectory Whether this is a directory
	IsDirectory bool `json:"isDirectory"`

	// LinkedFileId ID of linked File (for symlinks)
	LinkedFileId *openapi_types.UUID `json:"linkedFileId,omitempty"`

	// MimeType MIME type (null for directories)
	MimeType *string `json:"mimeType,omitempty"`

	// Name Current name of the File
	Name *string `json:"name"`

	// ParentId Parent directory ID
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`

	// Size File size in bytes (null for directories)
	Size *int64 `json:"size,omitempty"`

	// TrashedAt Trash timestamp
	TrashedAt *time.Time `json:"trashedAt,omitempty"`

	// TrashedBy User ID who trashed it
	TrashedBy *openapi_types.UUID `json:"trashedBy,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// UpdatedBy User ID who last updated it
	UpdatedBy *openapi_types.UUID `json:"updatedBy,omitempty"`
}

// FilePathItem defines model for FilePathItem.
type FilePathItem struct {
	Id      openapi_types.UUID `json:"id"`
	Name    string             `json:"name"`
	Trashed *bool              `json:"trashed,omitempty"`
}

// Link defines model for Link.
type Link struct {
	// Code Optional plain-text code required to view; null if no code is set
	Code *string `json:"code,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// ExpiresAt Expiration timestamp; null if the link never expires
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// FileCount Total number of files reachable in the shared subtree (excluding trashed)
	FileCount int `json:"fileCount"`

	// FolderCount Total number of folders reachable in the shared subtree (excluding trashed)
	FolderCount int `json:"folderCount"`

	// Id Unique identifier
	Id openapi_types.UUID `json:"id"`

	// Key Opaque URL slug used to access the link publicly
	Key string `json:"key"`

	// Name Display name of the link
	Name string `json:"name"`

	// OpenCount Number of times the link has been successfully unlocked (lifetime)
	OpenCount int `json:"openCount"`

	// OwnerId User ID of the owner
	OwnerId openapi_types.UUID `json:"ownerId"`

	// RevokedAt Revocation timestamp; null if the link is active
	RevokedAt *time.Time `json:"revokedAt,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

// LinkDetail defines model for LinkDetail.
type LinkDetail struct {
	// Code Optional plain-text code required to view; null if no code is set
	Code *string `json:"code,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// ExpiresAt Expiration timestamp; null if the link never expires
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// FileCount Total number of files reachable in the shared subtree (excluding trashed)
	FileCount int `json:"fileCount"`

	// Files Top-level files shared by the link
	Files []File `json:"files"`

	// FolderCount Total number of folders reachable in the shared subtree (excluding trashed)
	FolderCount int `json:"folderCount"`

	// Id Unique identifier
	Id openapi_types.UUID `json:"id"`

	// Key Opaque URL slug used to access the link publicly
	Key string `json:"key"`

	// Name Display name of the link
	Name string `json:"name"`

	// OpenCount Number of times the link has been successfully unlocked (lifetime)
	OpenCount int `json:"openCount"`

	// OwnerId User ID of the owner
	OwnerId openapi_types.UUID `json:"ownerId"`

	// RevokedAt Revocation timestamp; null if the link is active
	RevokedAt *time.Time `json:"revokedAt,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`
}

// ListAdminUsersResponse defines model for ListAdminUsersResponse.
type ListAdminUsersResponse struct {
	// Items Array of users
	Items []AdminUserListItem `json:"items"`

	// Total Total number of users (before pagination)
	Total int `json:"total"`
}

// ListEmailsResponse defines model for ListEmailsResponse.
type ListEmailsResponse struct {
	Emails []UserEmail `json:"emails"`
}

// ListFilesResponse defines model for ListFilesResponse.
type ListFilesResponse struct {
	// Items Array of File objects
	Items []File `json:"items"`

	// Total Total number of items (before pagination)
	Total int `json:"total"`
}

// ListLinksResponse defines model for ListLinksResponse.
type ListLinksResponse struct {
	// Items Array of Link objects
	Items []Link `json:"items"`

	// Total Total number of items matching the filter (before pagination)
	Total int `json:"total"`
}

// ListMailAccountsResponse defines model for ListMailAccountsResponse.
type ListMailAccountsResponse struct {
	Items []MailAccount `json:"items"`

	// Total Total number of accounts matching the query
	Total int `json:"total"`
}

// ListMailRulesResponse defines model for ListMailRulesResponse.
type ListMailRulesResponse struct {
	Items []MailRule `json:"items"`

	// Total Total number of rules matching the query
	Total int `json:"total"`
}

// ListPersonalAccessTokensResponse defines model for ListPersonalAccessTokensResponse.
type ListPersonalAccessTokensResponse struct {
	Tokens []PersonalAccessToken `json:"tokens"`
}

// ListPublicLinkFilesResponse defines model for ListPublicLinkFilesResponse.
type ListPublicLinkFilesResponse struct {
	// ExpiresAt When the link expires; null if it never expires
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Items Array of File objects accessible via the public link
	Items []File `json:"items"`

	// Name Display name of the link
	Name string `json:"name"`

	// OwnerName Display name of the user who created the link
	OwnerName string `json:"ownerName"`
}

// ListTrashResponse defines model for ListTrashResponse.
type ListTrashResponse struct {
	// Items Array of trashed File objects
	Items []TrashedFile `json:"items"`

	// Total Total number of items (before pagination)
	Total int `json:"total"`
}

// LoginConfigResponse defines model for LoginConfigResponse.
type LoginConfigResponse struct {
	RegistrationEnabled bool `json:"registrationEnabled"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	MfaCode  *string             `json:"mfaCode,omitempty"`
	Password string              `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	RequiresMfa *bool   `json:"requiresMfa,omitempty"`
	Token       *string `json:"token,omitempty"`
}

// MFARecoveryCodesStatusResponse defines model for MFARecoveryCodesStatusResponse.
type MFARecoveryCodesStatusResponse struct {
	RemainingCodes int `json:"remainingCodes"`
}

// MailAccount defines model for MailAccount.
type MailAccount struct {
	CreatedAt time.Time `json:"createdAt"`

	// Id Unique identifier
	Id openapi_types.UUID `json:"id"`

	// ImapHost IMAP server hostname
	ImapHost string `json:"imapHost"`

	// ImapPort IMAP server port
	ImapPort int `json:"imapPort"`

	// Name Human-readable account name
	Name string `json:"name"`

	// Security Transport security used for the IMAP connection
	Security  MailAccountSecurity `json:"security"`
	UpdatedAt time.Time           `json:"updatedAt"`

	// Username IMAP login username
	Username string `json:"username"`
}

// MailAccountSecurity Transport security used for the IMAP connection
type MailAccountSecurity string

// MailRule defines model for MailRule.
type MailRule struct {
	AccountId openapi_types.UUID `json:"accountId"`

	// Action Action performed on a mail once its attachments have been consumed; omitted means no action
	Action *MailRuleAction `json:"action,omitempty"`

	// AttachmentPattern Comma-separated filename globs (e.g. "*.pdf,*.docx"); empty means all attachments
	AttachmentPattern *string   `json:"attachmentPattern,omitempty"`
	CreatedAt         time.Time `json:"createdAt"`
	Enabled           bool      `json:"enabled"`

	// FilterFrom Only process mails whose From address contains this value
	FilterFrom *string `json:"filterFrom,omitempty"`

	// FilterSubject Only process mails whose subject contains this value
	FilterSubject *string `json:"filterSubject,omitempty"`

	// Folder IMAP folder to scan (e.g. INBOX)
	Folder string             `json:"folder"`
	Id     openapi_types.UUID `json:"id"`

	// MaxAgeDays Only process mails newer than this many days
	MaxAgeDays int    `json:"maxAgeDays"`
	Name       string `json:"name"`

	// Order Rules are applied in ascending order
	Order int `json:"order"`

	// TargetDirectoryId Directory the attachments are stored in; omitted means the account owner's root
	TargetDirectoryId *openapi_types.UUID `json:"targetDirectoryId,omitempty"`
	UpdatedAt         time.Time           `json:"updatedAt"`
}

// MailRuleAction Action performed on a mail once its attachments have been consumed; omitted means no action
type MailRuleAction string

// PersonalAccessToken defines model for PersonalAccessToken.
type PersonalAccessToken struct {
	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// ExpiresAt Expiration timestamp; omitted if the token never expires
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Id Unique identifier
	Id openapi_types.UUID `json:"id"`

	// Label Human-readable label describing the token's purpose; omitted if unlabeled
	Label *string `json:"label,omitempty"`
}

// RegenerateMFARecoveryCodesRequest defines model for RegenerateMFARecoveryCodesRequest.
type RegenerateMFARecoveryCodesRequest struct {
	Password string `json:"password"`
}

// RegenerateMFARecoveryCodesResponse defines model for RegenerateMFARecoveryCodesResponse.
type RegenerateMFARecoveryCodesResponse struct {
	RecoveryCodes []string `json:"recoveryCodes"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Name     string              `json:"name"`
	Password string              `json:"password"`
}

// ResetPasswordRequest defines model for ResetPasswordRequest.
type ResetPasswordRequest struct {
	Email openapi_types.Email `json:"email"`
}

// RestoreFileRequest defines model for RestoreFileRequest.
type RestoreFileRequest struct {
	// ParentId Target parent directory for the restored item, or null to restore to the root.
	ParentId *openapi_types.UUID `json:"parentId"`
}

// SetupMFAResponse defines model for SetupMFAResponse.
type SetupMFAResponse struct {
	QrCodeUrl string `json:"qrCodeUrl"`
	Secret    string `json:"secret"`
}

// TestMailAccountResponse defines model for TestMailAccountResponse.
type TestMailAccountResponse struct {
	// Message Error detail when the connection failed
	Message *string `json:"message,omitempty"`

	// Success Whether the IMAP connection and login succeeded
	Success bool `json:"success"`
}

// TrashedFile defines model for TrashedFile.
type TrashedFile struct {
	// Checksum File checksum (null for directories)
	Checksum *string `json:"checksum,omitempty"`

	// ContentMd Markdown content preview
	ContentMd *string `json:"contentMd,omitempty"`

	// CreatedAt Creation timestamp
	CreatedAt time.Time `json:"createdAt"`

	// CreatedBy User ID of creator
	CreatedBy *openapi_types.UUID `json:"createdBy,omitempty"`

	// Id Unique identifier
	Id openapi_types.UUID `json:"id"`

	// IsDirectory Whether this is a directory
	IsDirectory bool `json:"isDirectory"`

	// LinkedFileId ID of linked File (for symlinks)
	LinkedFileId *openapi_types.UUID `json:"linkedFileId,omitempty"`

	// MimeType MIME type (null for directories)
	MimeType *string `json:"mimeType,omitempty"`

	// Name Current name of the File
	Name *string `json:"name"`

	// OriginPath Full ancestor path of the parent directory at the time of trashing. Populated only for root-level trash items (when listing without parentId). Empty when the item was at root level.
	OriginPath *[]FilePathItem `json:"originPath,omitempty"`

	// ParentId Parent directory ID
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`

	// Size File size in bytes (null for directories)
	Size *int64 `json:"size,omitempty"`

	// TrashedAt Trash timestamp
	TrashedAt *time.Time `json:"trashedAt"`

	// TrashedBy User ID who trashed it
	TrashedBy *openapi_types.UUID `json:"trashedBy,omitempty"`

	// UpdatedAt Last update timestamp
	UpdatedAt time.Time `json:"updatedAt"`

	// UpdatedBy User ID who last updated it
	UpdatedBy *openapi_types.UUID `json:"updatedBy,omitempty"`
}

// UnlockPublicLinkRequest defines model for UnlockPublicLinkRequest.
type UnlockPublicLinkRequest struct {
	// Code Plain-text code required when the link is configured with one
	Code *string `json:"code,omitempty"`
}

// UnlockPublicLinkResponse defines model for UnlockPublicLinkResponse.
type UnlockPublicLinkResponse struct {
	// ExpiresAt When the issued token expires (capped at the link's own expiration)
	ExpiresAt time.Time `json:"expiresAt"`

	// Token Short-lived JWT to authorize subsequent list/download calls for this link
	Token string `json:"token"`
}

// UpdateFileRequest defines model for UpdateFileRequest.
type UpdateFileRequest struct {
	// Name New name for the File (optional)
	Name *string `json:"name,omitempty"`

	// ParentId New parent directory ID (null moves to root; only used when updateParentId is true)
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`

	// UpdateParentId Whether to move the File to a new parent directory
	UpdateParentId *bool `json:"updateParentId,omitempty"`
}

// UpdateFileWithContentRequest defines model for UpdateFileWithContentRequest.
type UpdateFileWithContentRequest struct {
	// File New file data (optional)
	File *openapi_types.File `json:"file,omitempty"`

	// Name New name for the File (optional)
	Name *string `json:"name,omitempty"`

	// ParentId New parent directory ID (null moves to root; only used when updateParentId is true)
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`

	// UpdateParentId Whether to move the File to a new parent directory
	UpdateParentId *bool `json:"updateParentId,omitempty"`
}

// UpdateLinkRequest defines model for UpdateLinkRequest.
type UpdateLinkRequest struct {
	// ClearCode When true, clears the code (no code required); takes precedence over code
	ClearCode *bool `json:"clearCode,omitempty"`

	// ClearExpiration When true, clears the expiration (link never expires); takes precedence over expiresAt
	ClearExpiration *bool `json:"clearExpiration,omitempty"`

	// Code New plain-text code (only used when clearCode is false)
	Code *string `json:"code,omitempty"`

	// ExpiresAt New expiration timestamp (only used when clearExpiration is false)
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Name New display name (omit to leave unchanged; must not be blank when set)
	Name *string `json:"name,omitempty"`
}

// UpdateMailAccountRequest defines model for UpdateMailAccountRequest.
type UpdateMailAccountRequest struct {
	ImapHost string `json:"imapHost"`
	ImapPort int    `json:"imapPort"`
	Name     string `json:"name"`

	// Password New IMAP password; omit to keep the existing one
	Password *string                          `json:"password,omitempty"`
	Security UpdateMailAccountRequestSecurity `json:"security"`
	Username string                           `json:"username"`
}

// UpdateMailAccountRequestSecurity defines model for UpdateMailAccountRequest.Security.
type UpdateMailAccountRequestSecurity string

// UpdateMailRuleRequest defines model for UpdateMailRuleRequest.
type UpdateMailRuleRequest struct {
	// AccountId Move the rule to this account; omit to keep its current account
	AccountId *openapi_types.UUID `json:"accountId,omitempty"`

	// Action Omit for no action once attachments are consumed
	Action *UpdateMailRuleRequestAction `json:"action,omitempty"`

	// AttachmentPattern Comma-separated filename globs (e.g. "*.pdf,*.docx"); empty means all attachments
	AttachmentPattern *string `json:"attachmentPattern,omitempty"`
	Enabled           bool    `json:"enabled"`
	FilterFrom        *string `json:"filterFrom,omitempty"`
	FilterSubject     *string `json:"filterSubject,omitempty"`
	Folder            string  `json:"folder"`
	MaxAgeDays        int     `json:"maxAgeDays"`
	Name              string  `json:"name"`
	Order             int     `json:"order"`

	// TargetDirectoryId Directory the attachments are stored in; omit for the account owner's root
	TargetDirectoryId *openapi_types.UUID `json:"targetDirectoryId,omitempty"`
}

// UpdateMailRuleRequestAction Omit for no action once attachments are consumed
type UpdateMailRuleRequestAction string

// UpdateUserEmailRequest defines model for UpdateUserEmailRequest.
type UpdateUserEmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	CurrentPassword *string `json:"currentPassword,omitempty"`
	Name            *string `json:"name,omitempty"`
	Password        *string `json:"password,omitempty"`
}

// UserEmail defines model for UserEmail.
type UserEmail struct {
	CreatedAt time.Time           `json:"createdAt"`
	Email     openapi_types.Email `json:"email"`
	Id        openapi_types.UUID  `json:"id"`
	IsPrimary bool                `json:"isPrimary"`
	Verified  bool                `json:"verified"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	IsAdmin    bool   `json:"isAdmin"`
	MfaEnabled bool   `json:"mfaEnabled"`
	Name       string `json:"name"`
}

// bearerHttpAuthenticationContextKey is the context key for bearerHttpAuthentication security scheme
type bearerHttpAuthenticationContextKey string

// publicLinkBearerAuthenticationContextKey is the context key for publicLinkBearerAuthentication security scheme
type publicLinkBearerAuthenticationContextKey string

// ListUsersAdminParams defines parameters for ListUsersAdmin.
type ListUsersAdminParams struct {
	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// ParentId Parent directory ID (omit for root)
	ParentId *openapi_types.UUID `form:"parentId,omitempty" json:"parentId,omitempty"`

	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetFileThumbnailParams defines parameters for GetFileThumbnail.
type GetFileThumbnailParams struct {
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// ListLinksParams defines parameters for ListLinks.
type ListLinksParams struct {
	// Status Filter by link status; omit to return all
	Status *ListLinksParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListLinksParamsStatus defines parameters for ListLinks.
type ListLinksParamsStatus string

// ListPublicLinkFilesParams defines parameters for ListPublicLinkFiles.
type ListPublicLinkFilesParams struct {
	// ParentId When set, list children of this folder (must be inside the link's shared scope); when omitted, list the top-level shared files
	ParentId *openapi_types.UUID `form:"parentId,omitempty" json:"parentId,omitempty"`
}

// ListMailAccountsParams defines parameters for ListMailAccounts.
type ListMailAccountsParams struct {
	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAllMailRulesParams defines parameters for ListAllMailRules.
type ListAllMailRulesParams struct {
	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTrashParams defines parameters for ListTrash.
type ListTrashParams struct {
	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTrashChildrenParams defines parameters for ListTrashChildren.
type ListTrashChildrenParams struct {
	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateUserAdminJSONRequestBody defines body for CreateUserAdmin for application/json ContentType.
type CreateUserAdminJSONRequestBody = AdminCreateUserRequest

// UpdateUserAdminJSONRequestBody defines body for UpdateUserAdmin for application/json ContentType.
type UpdateUserAdminJSONRequestBody = AdminUpdateUserRequest

// AddUserEmailAdminJSONRequestBody defines body for AddUserEmailAdmin for application/json ContentType.
type AddUserEmailAdminJSONRequestBody = AddEmailRequest

// ResetUserPasswordAdminJSONRequestBody defines body for ResetUserPasswordAdmin for application/json ContentType.
type ResetUserPasswordAdminJSONRequestBody = AdminResetPasswordRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// ResetPasswordJSONRequestBody defines body for ResetPassword for application/json ContentType.
type ResetPasswordJSONRequestBody = ResetPasswordRequest

// CreateFileMultipartRequestBody defines body for CreateFile for multipart/form-data ContentType.
type CreateFileMultipartRequestBody = CreateFileRequest

// UpdateFileFormdataRequestBody defines body for UpdateFile for application/x-www-form-urlencoded ContentType.
type UpdateFileFormdataRequestBody = UpdateFileRequest

// UpdateFileMultipartRequestBody defines body for UpdateFile for multipart/form-data ContentType.
type UpdateFileMultipartRequestBody = UpdateFileWithContentRequest

// CreateLinkJSONRequestBody defines body for CreateLink for application/json ContentType.
type CreateLinkJSONRequestBody = CreateLinkRequest

// UpdateLinkJSONRequestBody defines body for UpdateLink for application/json ContentType.
type UpdateLinkJSONRequestBody = UpdateLinkRequest

// AddFileToLinkJSONRequestBody defines body for AddFileToLink for application/json ContentType.
type AddFileToLinkJSONRequestBody = AddFileToLinkRequest

// UnlockPublicLinkJSONRequestBody defines body for UnlockPublicLink for application/json ContentType.
type UnlockPublicLinkJSONRequestBody = UnlockPublicLinkRequest

// AddEmailJSONRequestBody defines body for AddEmail for application/json ContentType.
type AddEmailJSONRequestBody = AddEmailRequest

// CreateMailAccountJSONRequestBody defines body for CreateMailAccount for application/json ContentType.
type CreateMailAccountJSONRequestBody = CreateMailAccountRequest

// UpdateMailAccountJSONRequestBody defines body for UpdateMailAccount for application/json ContentType.
type UpdateMailAccountJSONRequestBody = UpdateMailAccountRequest

// CreateMailRuleJSONRequestBody defines body for CreateMailRule for application/json ContentType.
type CreateMailRuleJSONRequestBody = CreateMailRuleRequest

// UpdateMailRuleJSONRequestBody defines body for UpdateMailRule for application/json ContentType.
type UpdateMailRuleJSONRequestBody = UpdateMailRuleRequest

// DisableMFAJSONRequestBody defines body for DisableMFA for application/json ContentType.
type DisableMFAJSONRequestBody = DisableMFARequest

// EnableMFAJSONRequestBody defines body for EnableMFA for application/json ContentType.
type EnableMFAJSONRequestBody = EnableMFARequest

// RegenerateMFARecoveryCodesJSONRequestBody defines body for RegenerateMFARecoveryCodes for application/json ContentType.
type RegenerateMFARecoveryCodesJSONRequestBody = RegenerateMFARecoveryCodesRequest

// ConfirmResetPasswordJSONRequestBody defines body for ConfirmResetPassword for application/json ContentType.
type ConfirmResetPasswordJSONRequestBody = ConfirmResetPasswordRequest

// CreatePersonalAccessTokenJSONRequestBody defines body for CreatePersonalAccessToken for application/json ContentType.
type CreatePersonalAccessTokenJSONRequestBody = CreatePersonalAccessTokenRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// UpdateUserEmailJSONRequestBody defines body for UpdateUserEmail for application/json ContentType.
type UpdateUserEmailJSONRequestBody = UpdateUserEmailRequest

// RestoreTrashJSONRequestBody defines body for RestoreTrash for application/json ContentType.
type RestoreTrashJSONRequestBody = RestoreFileRequest
