 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ListDatei$Params as ListDatei$Params } from './fn/operations/list-datei';
export { listDatei as listDatei } from './fn/operations/list-datei';
export type { CreateDatei$Params as CreateDatei$Params } from './fn/operations/create-datei';
export { createDatei as createDatei } from './fn/operations/create-datei';
export type { DeleteDatei$Params as DeleteDatei$Params } from './fn/operations/delete-datei';
export { deleteDatei as deleteDatei } from './fn/operations/delete-datei';
export type { UpdateDatei$Params as UpdateDatei$Params } from './fn/operations/update-datei';
export { updateDatei as updateDatei } from './fn/operations/update-datei';
export type { DownloadDatei$Params as DownloadDatei$Params } from './fn/operations/download-datei';
export { downloadDatei as downloadDatei } from './fn/operations/download-datei';
