/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { CreateDateiRequest } from './models/create-datei-request';
export type { DateiResponse } from './models/datei-response';
export type { DateiVersion } from './models/datei-version';
export type { ListDateiResponse } from './models/list-datei-response';
export type { UpdateDateiRequest } from './models/update-datei-request';
