/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AddDateiToLinkRequest } from './models/add-datei-to-link-request';
export type { AddEmailRequest } from './models/add-email-request';
export type { ConfirmResetPasswordRequest } from './models/confirm-reset-password-request';
export type { CreateDateiRequest } from './models/create-datei-request';
export type { CreateLinkRequest } from './models/create-link-request';
export type { Datei } from './models/datei';
export type { DateiPathItem } from './models/datei-path-item';
export type { DisableMfaRequest } from './models/disable-mfa-request';
export type { EnableMfaRequest } from './models/enable-mfa-request';
export type { EnableMfaResponse } from './models/enable-mfa-response';
export type { Link } from './models/link';
export type { LinkDetail } from './models/link-detail';
export type { ListDateiResponse } from './models/list-datei-response';
export type { ListEmailsResponse } from './models/list-emails-response';
export type { ListLinksResponse } from './models/list-links-response';
export type { ListPublicLinkDateienResponse } from './models/list-public-link-dateien-response';
export type { ListTrashResponse } from './models/list-trash-response';
export type { LoginConfigResponse } from './models/login-config-response';
export type { LoginRequest } from './models/login-request';
export type { LoginResponse } from './models/login-response';
export type { MfaRecoveryCodesStatusResponse } from './models/mfa-recovery-codes-status-response';
export type { RegenerateMfaRecoveryCodesRequest } from './models/regenerate-mfa-recovery-codes-request';
export type { RegenerateMfaRecoveryCodesResponse } from './models/regenerate-mfa-recovery-codes-response';
export type { RegisterRequest } from './models/register-request';
export type { ResetPasswordRequest } from './models/reset-password-request';
export type { RestoreDateiRequest } from './models/restore-datei-request';
export type { SetupMfaResponse } from './models/setup-mfa-response';
export type { TrashedDatei } from './models/trashed-datei';
export type { UpdateDateiRequest } from './models/update-datei-request';
export type { UpdateDateiWithFileRequest } from './models/update-datei-with-file-request';
export type { UpdateLinkRequest } from './models/update-link-request';
export type { UpdateUserEmailRequest } from './models/update-user-email-request';
export type { UpdateUserRequest } from './models/update-user-request';
export type { UserEmail } from './models/user-email';
export type { UserResponse } from './models/user-response';
