/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminUpdateUserRequest {

  /**
   * When false the account is archived (disabled). Setting true unarchives it.
   */
  enabled?: boolean;
  isAdmin?: boolean;
  name?: string;

  /**
   * Promote this email to be the user's primary email.
   */
  primaryEmailId?: string;
}
