/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminUpdateUserRequest {

  /**
   * When true the account is archived (disabled). Setting false unarchives it.
   */
  archived?: boolean;
  isAdmin?: boolean;
  name?: string;

  /**
   * Promote this email to be the user's primary email.
   */
  primaryEmailId?: string;
}
