/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminUserListItem {
  archived: boolean;
  createdAt: string;
  id: string;
  isAdmin: boolean;
  lastLoggedInAt?: string | null;
  mfaEnabled: boolean;
  name: string;
  primaryEmail?: string | null;
  primaryEmailVerified?: boolean | null;
}
