/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonalAccessToken } from '../models/personal-access-token';
export interface CreatePersonalAccessTokenResponse {
  accessToken: PersonalAccessToken;

  /**
   * The plaintext token (prefixed with "datei-"). Shown only once at creation time; only its hash is stored server-side and it can never be retrieved again.
   */
  token: string;
}
