/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateMailAccountRequest {
  imapHost: string;
  imapPort: number;
  name: string;

  /**
   * IMAP password; stored encrypted and never returned
   */
  password: string;
  security: 'ssl' | 'starttls' | 'none';
  username: string;
}
