/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePersonalAccessTokenRequest {

  /**
   * Expiration timestamp; omit or null for "never expires"
   */
  expiresAt?: string | null;

  /**
   * Human-readable label describing the token's purpose
   */
  label: string;
}
