/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateFileRequest {

  /**
   * File data (optional, omit for directories)
   */
  file?: Blob;

  /**
   * Name for the new File
   */
  name?: string;

  /**
   * Parent directory ID (omit for root)
   */
  parentId?: string;
}
