/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateLinkRequest {

  /**
   * Optional plain-text code required to view
   */
  code?: string | null;

  /**
   * Expiration timestamp; omit or null for "never expires"
   */
  expiresAt?: string | null;

  /**
   * IDs of files to share (may be empty)
   */
  fileIds: Array<string>;

  /**
   * Display name of the link (mandatory, may not be blank)
   */
  name: string;
}
