/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MailAccountSecurity } from '../models/mail-account-security';
export interface CreateMailAccountRequest {
  imapHost: string;
  imapPort: number;
  name: string;

  /**
   * IMAP password; stored encrypted and never returned
   */
  password: string;
  security: MailAccountSecurity;
  username: string;
}
