/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreatePersonalAccessTokenRequest {

  /**
   * Expiration timestamp; omit for "never expires"
   */
  expiresAt?: string;

  /**
   * Human-readable label describing the token's purpose; omit (or send empty/whitespace-only) for unlabeled tokens
   */
  label?: string;
}
