 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateDateiRequest {

  /**
   * File data (optional, omit for directories)
   */
  file?: Blob;

  /**
   * Name for the new Datei
   */
  name: string;
}
