 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DateiVersion } from '../models/datei-version';
export interface Datei {

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * User ID of creator
   */
  createdBy?: string | null;

  /**
   * Unique identifier
   */
  id: string;

  /**
   * Whether this is a directory
   */
  isDirectory: boolean;

  /**
   * Latest version/upload of the file
   */
  latestVersion?: (DateiVersion & {
}) | null;

  /**
   * ID of linked Datei (for symlinks)
   */
  linkedDateiId?: string | null;

  /**
   * Current name of the Datei
   */
  name?: string | null;

  /**
   * Parent directory ID
   */
  parentId?: string | null;

  /**
   * Trash timestamp
   */
  trashedAt?: string | null;

  /**
   * User ID who trashed it
   */
  trashedBy?: string | null;

  /**
   * Last update timestamp
   */
  updatedAt: string;
}
