/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Datei {

  /**
   * File checksum (null for directories)
   */
  checksum?: string | null;

  /**
   * Markdown content preview
   */
  contentMd?: string | null;

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * User ID of creator
   */
  createdBy?: string | null;

  /**
   * Unique identifier
   */
  id: string;

  /**
   * Whether this is a directory
   */
  isDirectory: boolean;

  /**
   * ID of linked Datei (for symlinks)
   */
  linkedDateiId?: string | null;

  /**
   * MIME type (null for directories)
   */
  mimeType?: string | null;

  /**
   * Current name of the Datei
   */
  name?: string | null;

  /**
   * Parent directory ID
   */
  parentId?: string | null;

  /**
   * File size in bytes (null for directories)
   */
  size?: number | null;

  /**
   * Trash timestamp
   */
  trashedAt?: string | null;

  /**
   * User ID who trashed it
   */
  trashedBy?: string | null;

  /**
   * Last update timestamp
   */
  updatedAt: string;
}
