 
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DateiVersion {

  /**
   * File checksum
   */
  checksum: string;

  /**
   * Markdown content preview
   */
  contentMd?: string | null;

  /**
   * Version creation timestamp
   */
  createdAt: string;

  /**
   * User ID of uploader
   */
  createdBy?: string | null;

  /**
   * File size in bytes
   */
  fileSize: number;

  /**
   * Version ID
   */
  id: string;

  /**
   * MIME type
   */
  mimeType: string;
}
