/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DateiVersion {

  /**
   * File checksum
   */
  checksum: string;

  /**
   * Markdown content preview
   */
  contentMd?: string | null;

  /**
   * File size in bytes
   */
  fileSize: number;

  /**
   * MIME type
   */
  mimeType: string;
}
