/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { File } from '../models/file';
import { Link } from '../models/link';
export type LinkDetail = Link & {

/**
 * Top-level files shared by the link
 */
'files': Array<File>;
};

