/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Datei } from '../models/datei';
import { Link } from '../models/link';
export type LinkDetail = Link & {

/**
 * Top-level dateien shared by the link
 */
'dateien': Array<Datei>;
};

