/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Link {

  /**
   * Optional plain-text code required to view; null if no code is set
   */
  code?: string | null;

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * Expiration timestamp; null if the link never expires
   */
  expiresAt?: string | null;

  /**
   * Total number of files reachable in the shared subtree (excluding trashed)
   */
  fileCount: number;

  /**
   * Total number of folders reachable in the shared subtree (excluding trashed)
   */
  folderCount: number;

  /**
   * Unique identifier
   */
  id: string;

  /**
   * Opaque URL slug used to access the link publicly
   */
  key: string;

  /**
   * Display name of the link
   */
  name: string;

  /**
   * Number of times the link has been successfully unlocked (lifetime)
   */
  openCount: number;

  /**
   * User ID of the owner
   */
  ownerId: string;

  /**
   * Revocation timestamp; null if the link is active
   */
  revokedAt?: string | null;

  /**
   * Last update timestamp
   */
  updatedAt: string;
}
