/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { File } from '../models/file';
export interface ListPublicLinkFilesResponse {

  /**
   * When the link expires; null if it never expires
   */
  expiresAt?: string | null;

  /**
   * Array of File objects accessible via the public link
   */
  items: Array<File>;

  /**
   * Display name of the link
   */
  name: string;

  /**
   * Display name of the user who created the link
   */
  ownerName: string;
}
