/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Datei } from '../models/datei';
export interface ListDateiResponse {

  /**
   * Array of Datei objects
   */
  items: Array<Datei>;

  /**
   * Total number of items (before pagination)
   */
  total: number;
}
