/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DateiResponse } from '../models/datei-response';
export interface ListDateiResponse {

  /**
   * Array of Datei objects
   */
  items: Array<DateiResponse>;

  /**
   * Total number of items (before pagination)
   */
  total: number;
}
