/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TrashedDatei } from '../models/trashed-datei';
export interface ListTrashResponse {

  /**
   * Array of trashed Datei objects
   */
  items: Array<TrashedDatei>;

  /**
   * Total number of items (before pagination)
   */
  total: number;
}
