/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { File } from '../models/file';
export interface ListFilesResponse {

  /**
   * Array of File objects
   */
  items: Array<File>;

  /**
   * Total number of items (before pagination)
   */
  total: number;
}
