/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Datei } from '../models/datei';
export interface ListPublicLinkDateienResponse {

  /**
   * Array of Datei objects accessible via the public link
   */
  items: Array<Datei>;

  /**
   * Display name of the link
   */
  name: string;

  /**
   * Display name of the user who created the link
   */
  ownerName: string;
}
