/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MailAccount } from '../models/mail-account';
export interface ListMailAccountsResponse {
  items: Array<MailAccount>;

  /**
   * Total number of accounts matching the query
   */
  total: number;
}
