/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminUserListItem } from '../models/admin-user-list-item';
export interface ListAdminUsersResponse {

  /**
   * Array of users
   */
  items: Array<AdminUserListItem>;

  /**
   * Total number of users (before pagination)
   */
  total: number;
}
