/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminUserListItem } from '../models/admin-user-list-item';
export interface ListAdminUsersResponse {
  users: Array<AdminUserListItem>;
}
