/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TrashedFile } from '../models/trashed-file';
export interface ListTrashResponse {

  /**
   * Array of trashed File objects
   */
  items: Array<TrashedFile>;

  /**
   * Total number of items (before pagination)
   */
  total: number;
}
