/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PersonalAccessToken } from '../models/personal-access-token';
export interface ListPersonalAccessTokensResponse {
  tokens: Array<PersonalAccessToken>;
}
