/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MailRule } from '../models/mail-rule';
export interface ListMailRulesResponse {
  items: Array<MailRule>;

  /**
   * Total number of rules matching the query
   */
  total: number;
}
