/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Link } from '../models/link';
export interface ListLinksResponse {

  /**
   * Array of Link objects
   */
  items: Array<Link>;

  /**
   * Total number of items
   */
  total: number;
}
