/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MailAccountSecurity } from '../models/mail-account-security';
export interface MailAccount {
  createdAt: string;

  /**
   * Unique identifier
   */
  id: string;

  /**
   * IMAP server hostname
   */
  imapHost: string;

  /**
   * IMAP server port
   */
  imapPort: number;

  /**
   * Human-readable account name
   */
  name: string;
  security: MailAccountSecurity;
  updatedAt: string;

  /**
   * IMAP login username
   */
  username: string;
}
