/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MailRule {
  accountId: string;

  /**
   * Action performed on a mail once its attachments have been consumed; omitted means no action
   */
  action?: 'mark_as_read';

  /**
   * Comma-separated filename globs (e.g. "*.pdf,*.docx"); empty means all attachments
   */
  attachmentPattern?: string;
  createdAt: string;
  enabled: boolean;

  /**
   * Only process mails whose From address contains this value
   */
  filterFrom?: string;

  /**
   * Only process mails whose subject contains this value
   */
  filterSubject?: string;

  /**
   * IMAP folder to scan (e.g. INBOX)
   */
  folder: string;
  id: string;

  /**
   * Only process mails newer than this many days
   */
  maxAgeDays: number;
  name: string;

  /**
   * Rules are applied in ascending order
   */
  order: number;

  /**
   * Directory the attachments are stored in; omitted means the account owner's root
   */
  targetDirectoryId?: string;
  updatedAt: string;
}
