/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MailAccountSecurity } from './mail-account-security';

/**
 * Each possible value of `MailAccountSecurity`
 */
export const MAIL_ACCOUNT_SECURITY: MailAccountSecurity[] = [
  'ssl',
  'starttls',
  'none'
];