/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PersonalAccessToken {

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * Expiration timestamp; null if the token never expires
   */
  expiresAt?: string | null;

  /**
   * Unique identifier
   */
  id: string;

  /**
   * Human-readable label describing the token's purpose
   */
  label: string;
}
