/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PersonalAccessToken {

  /**
   * Creation timestamp
   */
  createdAt: string;

  /**
   * Expiration timestamp; omitted if the token never expires
   */
  expiresAt?: string;

  /**
   * Unique identifier
   */
  id: string;

  /**
   * Human-readable label describing the token's purpose; omitted if unlabeled
   */
  label?: string;
}
