/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicLinkErrorResponse {

  /**
   * Reason the request was rejected
   */
  code: 'code_required' | 'code_invalid';
}
