/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RestoreDateiRequest {

  /**
   * Target parent directory for the restored item, or null to restore to the root.
   */
  parentId: string | null;
}
