/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RestoreDateiRequest {

  /**
   * New parent directory for the restored item. Required when the item's original parent is trashed, or when the item is a descendant of a trashed item.
   */
  parentId?: string;
}
