/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TestMailAccountResponse {

  /**
   * Error detail when the connection failed
   */
  message?: string;

  /**
   * Whether the IMAP connection and login succeeded
   */
  success: boolean;
}
