/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Datei } from '../models/datei';
import { DateiPathItem } from '../models/datei-path-item';
export type TrashedDatei = Datei & {

/**
 * Full ancestor path of the parent directory at the time of trashing. Populated only for root-level trash items (when listing without parentId). Empty when the item was at root level.
 */
'originPath'?: Array<DateiPathItem> | null;
};

