/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { File } from '../models/file';
import { FilePathItem } from '../models/file-path-item';
export type TrashedFile = File & {

/**
 * Full ancestor path of the parent directory at the time of trashing. Populated only for root-level trash items (when listing without parentId). Empty when the item was at root level.
 */
'originPath'?: Array<FilePathItem> | null;
};

