/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UnlockPublicLinkRequest {

  /**
   * Plain-text code required when the link is configured with one
   */
  code?: string;
}
