/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UnlockPublicLinkResponse {

  /**
   * When the issued token expires (capped at the link's own expiration)
   */
  expiresAt: string;

  /**
   * Short-lived JWT to authorize subsequent list/download calls for this link
   */
  token: string;
}
