/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UpdateDateiRequest } from '../models/update-datei-request';
export type UpdateDateiWithFileRequest = UpdateDateiRequest & {

/**
 * New file data (optional)
 */
'file'?: Blob | null;
};

