/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateFileRequest {

  /**
   * New name for the File (optional)
   */
  name?: string | null;

  /**
   * New parent directory ID (null moves to root; only used when updateParentId is true)
   */
  parentId?: string | null;

  /**
   * Whether to move the File to a new parent directory
   */
  updateParentId?: boolean | null;
}
