/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDateiRequest {

  /**
   * New file data (optional)
   */
  file?: Blob;

  /**
   * New name for the Datei (optional)
   */
  name?: string;
}
