/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateLinkRequest {

  /**
   * When true, clears the code (no code required); takes precedence over code
   */
  clearCode?: boolean | null;

  /**
   * When true, clears the expiration (link never expires); takes precedence over expiresAt
   */
  clearExpiration?: boolean | null;

  /**
   * New plain-text code (only used when clearCode is false)
   */
  code?: string | null;

  /**
   * New expiration timestamp (only used when clearExpiration is false)
   */
  expiresAt?: string | null;

  /**
   * New display name (omit to leave unchanged)
   */
  name?: string | null;
}
