/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateMailRuleRequest {

  /**
   * Move the rule to this account; omit to keep its current account
   */
  accountId?: string;
  action: 'mark_as_read';

  /**
   * Comma-separated filename globs (e.g. "*.pdf,*.docx"); empty means all attachments
   */
  attachmentPattern?: string;
  enabled: boolean;
  filterFrom?: string;
  filterSubject?: string;
  folder: string;
  maxAgeDays: number;
  name: string;
  order: number;

  /**
   * Directory the attachments are stored in; omit for the account owner's root
   */
  targetDirectoryId?: string;
}
