/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateMailAccountRequest {
  imapHost: string;
  imapPort: number;
  name: string;

  /**
   * New IMAP password; omit to keep the existing one
   */
  password?: string;
  security: 'ssl' | 'starttls' | 'none';
  username: string;
}
