/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDateiWithFileRequest {

  /**
   * New file data (optional)
   */
  file?: Blob | null;

  /**
   * New name for the Datei (optional)
   */
  name?: string | null;

  /**
   * New parent directory ID (optional; empty string moves to root)
   */
  parentId?: string | null;
}
