/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateDateiRequest {

  /**
   * New name for the Datei (optional)
   */
  name?: string | null;

  /**
   * New parent directory ID (null moves to root; only used when updateParentId is true)
   */
  parentId?: string | null;

  /**
   * Whether to move the Datei to a new parent directory
   */
  updateParentId?: boolean | null;
}
