/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserEmail {
  createdAt: string;
  email: string;
  id: string;
  isPrimary: boolean;
  verified: boolean;
}
