// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: datei.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteDateiPermissionProjection = `-- name: DeleteDateiPermissionProjection :exec
DELETE FROM datei_permission_projection
 WHERE id = $1
`

func (q *Queries) DeleteDateiPermissionProjection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDateiPermissionProjection, id)
	return err
}

const getDateiProjectionByID = `-- name: GetDateiProjectionByID :one
SELECT id, parent_id, is_directory, linked_datei_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM datei_projection WHERE id = $1
`

func (q *Queries) GetDateiProjectionByID(ctx context.Context, id uuid.UUID) (DateiProjection, error) {
	row := q.db.QueryRow(ctx, getDateiProjectionByID, id)
	var i DateiProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedDateiID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const insertDateiPermissionProjection = `-- name: InsertDateiPermissionProjection :exec
INSERT INTO datei_permission_projection
 (id, datei_id, user_account_id, user_group_id, permission_type, created_at)
 VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDateiPermissionProjectionParams struct {
	ID             uuid.UUID           `db:"id"`
	DateiID        uuid.UUID           `db:"datei_id"`
	UserAccountID  *uuid.UUID          `db:"user_account_id"`
	UserGroupID    *uuid.UUID          `db:"user_group_id"`
	PermissionType DateiPermissionType `db:"permission_type"`
	CreatedAt      time.Time           `db:"created_at"`
}

func (q *Queries) InsertDateiPermissionProjection(ctx context.Context, arg InsertDateiPermissionProjectionParams) error {
	_, err := q.db.Exec(ctx, insertDateiPermissionProjection,
		arg.ID,
		arg.DateiID,
		arg.UserAccountID,
		arg.UserGroupID,
		arg.PermissionType,
		arg.CreatedAt,
	)
	return err
}

const insertDateiProjection = `-- name: InsertDateiProjection :exec
INSERT INTO datei_projection
 (id, parent_id, is_directory, name, created_at, updated_at)
 VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDateiProjectionParams struct {
	ID          uuid.UUID  `db:"id"`
	ParentID    *uuid.UUID `db:"parent_id"`
	IsDirectory bool       `db:"is_directory"`
	Name        string     `db:"name"`
	CreatedAt   time.Time  `db:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at"`
}

func (q *Queries) InsertDateiProjection(ctx context.Context, arg InsertDateiProjectionParams) error {
	_, err := q.db.Exec(ctx, insertDateiProjection,
		arg.ID,
		arg.ParentID,
		arg.IsDirectory,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listDateiProjections = `-- name: ListDateiProjections :many
SELECT id, parent_id, is_directory, linked_datei_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM datei_projection ORDER BY created_at DESC
`

func (q *Queries) ListDateiProjections(ctx context.Context) ([]DateiProjection, error) {
	rows, err := q.db.Query(ctx, listDateiProjections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DateiProjection
	for rows.Next() {
		var i DateiProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedDateiID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDateiProjectionContentMD = `-- name: UpdateDateiProjectionContentMD :exec
UPDATE datei_projection
 SET content_md = $1
 WHERE id = $2 AND checksum = $3
`

type UpdateDateiProjectionContentMDParams struct {
	ContentMd *string   `db:"content_md"`
	ID        uuid.UUID `db:"id"`
	Checksum  *string   `db:"checksum"`
}

func (q *Queries) UpdateDateiProjectionContentMD(ctx context.Context, arg UpdateDateiProjectionContentMDParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionContentMD, arg.ContentMd, arg.ID, arg.Checksum)
	return err
}

const updateDateiProjectionLinked = `-- name: UpdateDateiProjectionLinked :exec
UPDATE datei_projection
 SET linked_datei_id = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateDateiProjectionLinkedParams struct {
	LinkedDateiID *uuid.UUID `db:"linked_datei_id"`
	UpdatedAt     time.Time  `db:"updated_at"`
	ID            uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateDateiProjectionLinked(ctx context.Context, arg UpdateDateiProjectionLinkedParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionLinked, arg.LinkedDateiID, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionName = `-- name: UpdateDateiProjectionName :exec
UPDATE datei_projection
 SET name = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateDateiProjectionNameParams struct {
	Name      string    `db:"name"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateDateiProjectionName(ctx context.Context, arg UpdateDateiProjectionNameParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionName, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionParent = `-- name: UpdateDateiProjectionParent :exec
UPDATE datei_projection
 SET parent_id = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateDateiProjectionParentParams struct {
	ParentID  *uuid.UUID `db:"parent_id"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateDateiProjectionParent(ctx context.Context, arg UpdateDateiProjectionParentParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionParent, arg.ParentID, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionRestored = `-- name: UpdateDateiProjectionRestored :exec
UPDATE datei_projection
 SET trashed_at = NULL, trashed_by = NULL, updated_at = $1, updated_by = NULL
 WHERE id = $2
`

type UpdateDateiProjectionRestoredParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateDateiProjectionRestored(ctx context.Context, arg UpdateDateiProjectionRestoredParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionRestored, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionTrashed = `-- name: UpdateDateiProjectionTrashed :exec
UPDATE datei_projection
 SET trashed_at = $1, trashed_by = NULL, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateDateiProjectionTrashedParams struct {
	TrashedAt *time.Time `db:"trashed_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateDateiProjectionTrashed(ctx context.Context, arg UpdateDateiProjectionTrashedParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionTrashed, arg.TrashedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionUnlinked = `-- name: UpdateDateiProjectionUnlinked :exec
UPDATE datei_projection
 SET linked_datei_id = NULL, updated_at = $1, updated_by = NULL
 WHERE id = $2
`

type UpdateDateiProjectionUnlinkedParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateDateiProjectionUnlinked(ctx context.Context, arg UpdateDateiProjectionUnlinkedParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionUnlinked, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionVersion = `-- name: UpdateDateiProjectionVersion :exec
UPDATE datei_projection
 SET s3_key = $1, size = $2, checksum = $3, mime_type = $4,
     content_md = $5, updated_at = $6, updated_by = NULL
 WHERE id = $7
`

type UpdateDateiProjectionVersionParams struct {
	S3Key     *string   `db:"s3_key"`
	Size      *int64    `db:"size"`
	Checksum  *string   `db:"checksum"`
	MimeType  *string   `db:"mime_type"`
	ContentMd *string   `db:"content_md"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateDateiProjectionVersion(ctx context.Context, arg UpdateDateiProjectionVersionParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionVersion,
		arg.S3Key,
		arg.Size,
		arg.Checksum,
		arg.MimeType,
		arg.ContentMd,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
