// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: datei.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDateiProjectionsByParent = `-- name: CountDateiProjectionsByParent :one
SELECT COUNT(*) FROM datei_projection WHERE parent_id = $1 AND trashed_at IS NULL
`

func (q *Queries) CountDateiProjectionsByParent(ctx context.Context, parentID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDateiProjectionsByParent, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRootDateiProjections = `-- name: CountRootDateiProjections :one
SELECT COUNT(*) FROM datei_projection WHERE parent_id IS NULL AND trashed_at IS NULL
`

func (q *Queries) CountRootDateiProjections(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRootDateiProjections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashedDatei = `-- name: CountTrashedDatei :one
SELECT COUNT(*) FROM datei_projection WHERE trashed_at IS NOT NULL
`

func (q *Queries) CountTrashedDatei(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTrashedDatei)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDateiPermissionProjection = `-- name: DeleteDateiPermissionProjection :exec
DELETE FROM datei_permission_projection
 WHERE id = $1
`

func (q *Queries) DeleteDateiPermissionProjection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDateiPermissionProjection, id)
	return err
}

const getDateiPath = `-- name: GetDateiPath :many
WITH RECURSIVE ancestors(id, parent_id, name, trashed_at, depth) AS (
  SELECT d.id, d.parent_id, d.name, d.trashed_at, 0 FROM datei_projection d WHERE d.id = $1
  UNION ALL
  SELECT p.id, p.parent_id, p.name, p.trashed_at, a.depth + 1
  FROM datei_projection p
  INNER JOIN ancestors a ON p.id = a.parent_id
  WHERE a.trashed_at IS NULL
)
SELECT id, name, trashed_at FROM ancestors
ORDER BY depth DESC
`

type GetDateiPathRow struct {
	ID        uuid.UUID  `db:"id"`
	Name      string     `db:"name"`
	TrashedAt *time.Time `db:"trashed_at"`
}

func (q *Queries) GetDateiPath(ctx context.Context, id uuid.UUID) ([]GetDateiPathRow, error) {
	rows, err := q.db.Query(ctx, getDateiPath, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDateiPathRow
	for rows.Next() {
		var i GetDateiPathRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TrashedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDateiPathIncludingTrashed = `-- name: GetDateiPathIncludingTrashed :many
WITH RECURSIVE ancestors(id, parent_id, name, depth) AS (
  SELECT d.id, d.parent_id, d.name, 0 FROM datei_projection d WHERE d.id = $1
  UNION ALL
  SELECT p.id, p.parent_id, p.name, a.depth + 1
  FROM datei_projection p
  INNER JOIN ancestors a ON p.id = a.parent_id
)
SELECT id, name FROM ancestors
ORDER BY depth DESC
`

type GetDateiPathIncludingTrashedRow struct {
	ID   uuid.UUID `db:"id"`
	Name string    `db:"name"`
}

func (q *Queries) GetDateiPathIncludingTrashed(ctx context.Context, id uuid.UUID) ([]GetDateiPathIncludingTrashedRow, error) {
	rows, err := q.db.Query(ctx, getDateiPathIncludingTrashed, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDateiPathIncludingTrashedRow
	for rows.Next() {
		var i GetDateiPathIncludingTrashedRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDateiProjectionByID = `-- name: GetDateiProjectionByID :one
SELECT id, parent_id, is_directory, linked_datei_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM datei_projection WHERE id = $1
`

func (q *Queries) GetDateiProjectionByID(ctx context.Context, id uuid.UUID) (DateiProjection, error) {
	row := q.db.QueryRow(ctx, getDateiProjectionByID, id)
	var i DateiProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedDateiID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getDateiProjectionByParentAndName = `-- name: GetDateiProjectionByParentAndName :one
SELECT id, parent_id, is_directory, linked_datei_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM datei_projection WHERE parent_id = $1 AND name = $2 AND trashed_at IS NULL
`

type GetDateiProjectionByParentAndNameParams struct {
	ParentID *uuid.UUID `db:"parent_id"`
	Name     string     `db:"name"`
}

func (q *Queries) GetDateiProjectionByParentAndName(ctx context.Context, arg GetDateiProjectionByParentAndNameParams) (DateiProjection, error) {
	row := q.db.QueryRow(ctx, getDateiProjectionByParentAndName, arg.ParentID, arg.Name)
	var i DateiProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedDateiID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getDateiProjectionByPath = `-- name: GetDateiProjectionByPath :one
WITH RECURSIVE path_walk AS (
  SELECT d.id, 1::int AS depth
  FROM datei_projection d
  WHERE d.parent_id IS NULL
    AND d.name = ($1::text[])[1]
    AND d.trashed_at IS NULL
  UNION ALL
  SELECT d.id, pw.depth + 1
  FROM datei_projection d
  JOIN path_walk pw ON d.parent_id = pw.id
  WHERE d.name = ($1::text[])[pw.depth + 1]
    AND d.trashed_at IS NULL
)
SELECT dp.id, dp.parent_id, dp.is_directory, dp.linked_datei_id, dp.name, dp.s3_key, dp.size, dp.checksum, dp.mime_type, dp.content_md, dp.content_search, dp.created_at, dp.updated_at, dp.trashed_at, dp.created_by, dp.updated_by, dp.trashed_by FROM datei_projection dp
JOIN path_walk pw ON dp.id = pw.id
WHERE pw.depth = array_length($1::text[], 1)
`

func (q *Queries) GetDateiProjectionByPath(ctx context.Context, dollar_1 []string) (DateiProjection, error) {
	row := q.db.QueryRow(ctx, getDateiProjectionByPath, dollar_1)
	var i DateiProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedDateiID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getRootDateiProjectionByName = `-- name: GetRootDateiProjectionByName :one
SELECT id, parent_id, is_directory, linked_datei_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM datei_projection WHERE parent_id IS NULL AND name = $1 AND trashed_at IS NULL
`

func (q *Queries) GetRootDateiProjectionByName(ctx context.Context, name string) (DateiProjection, error) {
	row := q.db.QueryRow(ctx, getRootDateiProjectionByName, name)
	var i DateiProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedDateiID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const insertDateiPermissionProjection = `-- name: InsertDateiPermissionProjection :exec
INSERT INTO datei_permission_projection
 (id, datei_id, user_account_id, user_group_id, permission_type, created_at)
 VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDateiPermissionProjectionParams struct {
	ID             uuid.UUID           `db:"id"`
	DateiID        uuid.UUID           `db:"datei_id"`
	UserAccountID  *uuid.UUID          `db:"user_account_id"`
	UserGroupID    *uuid.UUID          `db:"user_group_id"`
	PermissionType DateiPermissionType `db:"permission_type"`
	CreatedAt      time.Time           `db:"created_at"`
}

func (q *Queries) InsertDateiPermissionProjection(ctx context.Context, arg InsertDateiPermissionProjectionParams) error {
	_, err := q.db.Exec(ctx, insertDateiPermissionProjection,
		arg.ID,
		arg.DateiID,
		arg.UserAccountID,
		arg.UserGroupID,
		arg.PermissionType,
		arg.CreatedAt,
	)
	return err
}

const insertDateiProjection = `-- name: InsertDateiProjection :exec
INSERT INTO datei_projection
 (id, parent_id, is_directory, name, created_at, updated_at)
 VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDateiProjectionParams struct {
	ID          uuid.UUID  `db:"id"`
	ParentID    *uuid.UUID `db:"parent_id"`
	IsDirectory bool       `db:"is_directory"`
	Name        string     `db:"name"`
	CreatedAt   time.Time  `db:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at"`
}

func (q *Queries) InsertDateiProjection(ctx context.Context, arg InsertDateiProjectionParams) error {
	_, err := q.db.Exec(ctx, insertDateiProjection,
		arg.ID,
		arg.ParentID,
		arg.IsDirectory,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listDateiProjections = `-- name: ListDateiProjections :many
SELECT id, parent_id, is_directory, linked_datei_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM datei_projection ORDER BY created_at DESC
`

func (q *Queries) ListDateiProjections(ctx context.Context) ([]DateiProjection, error) {
	rows, err := q.db.Query(ctx, listDateiProjections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DateiProjection
	for rows.Next() {
		var i DateiProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedDateiID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDateiProjectionsByParent = `-- name: ListDateiProjectionsByParent :many
SELECT id, parent_id, is_directory, linked_datei_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM datei_projection WHERE parent_id = $1 AND trashed_at IS NULL ORDER BY is_directory DESC, name ASC
LIMIT $2 OFFSET $3
`

type ListDateiProjectionsByParentParams struct {
	ParentID *uuid.UUID `db:"parent_id"`
	Limit    int32      `db:"limit"`
	Offset   int32      `db:"offset"`
}

func (q *Queries) ListDateiProjectionsByParent(ctx context.Context, arg ListDateiProjectionsByParentParams) ([]DateiProjection, error) {
	rows, err := q.db.Query(ctx, listDateiProjectionsByParent, arg.ParentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DateiProjection
	for rows.Next() {
		var i DateiProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedDateiID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootDateiProjections = `-- name: ListRootDateiProjections :many
SELECT id, parent_id, is_directory, linked_datei_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM datei_projection WHERE parent_id IS NULL AND trashed_at IS NULL ORDER BY is_directory DESC, name ASC
LIMIT $1 OFFSET $2
`

type ListRootDateiProjectionsParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListRootDateiProjections(ctx context.Context, arg ListRootDateiProjectionsParams) ([]DateiProjection, error) {
	rows, err := q.db.Query(ctx, listRootDateiProjections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DateiProjection
	for rows.Next() {
		var i DateiProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedDateiID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedDatei = `-- name: ListTrashedDatei :many
SELECT id, parent_id, is_directory, linked_datei_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM datei_projection WHERE trashed_at IS NOT NULL ORDER BY trashed_at DESC
LIMIT $1 OFFSET $2
`

type ListTrashedDateiParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListTrashedDatei(ctx context.Context, arg ListTrashedDateiParams) ([]DateiProjection, error) {
	rows, err := q.db.Query(ctx, listTrashedDatei, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DateiProjection
	for rows.Next() {
		var i DateiProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedDateiID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDateiProjectionContentMD = `-- name: UpdateDateiProjectionContentMD :exec
UPDATE datei_projection
 SET content_md = $1
 WHERE id = $2 AND checksum = $3
`

type UpdateDateiProjectionContentMDParams struct {
	ContentMd *string   `db:"content_md"`
	ID        uuid.UUID `db:"id"`
	Checksum  *string   `db:"checksum"`
}

func (q *Queries) UpdateDateiProjectionContentMD(ctx context.Context, arg UpdateDateiProjectionContentMDParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionContentMD, arg.ContentMd, arg.ID, arg.Checksum)
	return err
}

const updateDateiProjectionLinked = `-- name: UpdateDateiProjectionLinked :exec
UPDATE datei_projection
 SET linked_datei_id = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateDateiProjectionLinkedParams struct {
	LinkedDateiID *uuid.UUID `db:"linked_datei_id"`
	UpdatedAt     time.Time  `db:"updated_at"`
	ID            uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateDateiProjectionLinked(ctx context.Context, arg UpdateDateiProjectionLinkedParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionLinked, arg.LinkedDateiID, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionName = `-- name: UpdateDateiProjectionName :exec
UPDATE datei_projection
 SET name = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateDateiProjectionNameParams struct {
	Name      string    `db:"name"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateDateiProjectionName(ctx context.Context, arg UpdateDateiProjectionNameParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionName, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionParent = `-- name: UpdateDateiProjectionParent :exec
UPDATE datei_projection
 SET parent_id = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateDateiProjectionParentParams struct {
	ParentID  *uuid.UUID `db:"parent_id"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateDateiProjectionParent(ctx context.Context, arg UpdateDateiProjectionParentParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionParent, arg.ParentID, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionRestored = `-- name: UpdateDateiProjectionRestored :exec
UPDATE datei_projection
 SET trashed_at = NULL, trashed_by = NULL, updated_at = $1, updated_by = NULL
 WHERE id = $2
`

type UpdateDateiProjectionRestoredParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateDateiProjectionRestored(ctx context.Context, arg UpdateDateiProjectionRestoredParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionRestored, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionTrashed = `-- name: UpdateDateiProjectionTrashed :exec
UPDATE datei_projection
 SET trashed_at = $1, trashed_by = NULL, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateDateiProjectionTrashedParams struct {
	TrashedAt *time.Time `db:"trashed_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateDateiProjectionTrashed(ctx context.Context, arg UpdateDateiProjectionTrashedParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionTrashed, arg.TrashedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionUnlinked = `-- name: UpdateDateiProjectionUnlinked :exec
UPDATE datei_projection
 SET linked_datei_id = NULL, updated_at = $1, updated_by = NULL
 WHERE id = $2
`

type UpdateDateiProjectionUnlinkedParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateDateiProjectionUnlinked(ctx context.Context, arg UpdateDateiProjectionUnlinkedParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionUnlinked, arg.UpdatedAt, arg.ID)
	return err
}

const updateDateiProjectionVersion = `-- name: UpdateDateiProjectionVersion :exec
UPDATE datei_projection
 SET s3_key = $1, size = $2, checksum = $3, mime_type = $4,
     content_md = $5, updated_at = $6, updated_by = NULL
 WHERE id = $7
`

type UpdateDateiProjectionVersionParams struct {
	S3Key     *string   `db:"s3_key"`
	Size      *int64    `db:"size"`
	Checksum  *string   `db:"checksum"`
	MimeType  *string   `db:"mime_type"`
	ContentMd *string   `db:"content_md"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateDateiProjectionVersion(ctx context.Context, arg UpdateDateiProjectionVersionParams) error {
	_, err := q.db.Exec(ctx, updateDateiProjectionVersion,
		arg.S3Key,
		arg.Size,
		arg.Checksum,
		arg.MimeType,
		arg.ContentMd,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
