// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countMailAccountProjectionsByOwner = `-- name: CountMailAccountProjectionsByOwner :one
SELECT COUNT(*) FROM mail_account_projection WHERE owner_id = $1
`

func (q *Queries) CountMailAccountProjectionsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMailAccountProjectionsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMailRuleProjectionsByOwner = `-- name: CountMailRuleProjectionsByOwner :one
SELECT COUNT(*) FROM mail_rule_projection r
 JOIN mail_account_projection a ON a.id = r.account_id
 WHERE a.owner_id = $1
`

func (q *Queries) CountMailRuleProjectionsByOwner(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMailRuleProjectionsByOwner, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMailAccountProjection = `-- name: DeleteMailAccountProjection :exec
DELETE FROM mail_account_projection WHERE id = $1
`

func (q *Queries) DeleteMailAccountProjection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMailAccountProjection, id)
	return err
}

const deleteMailRuleProjection = `-- name: DeleteMailRuleProjection :exec
DELETE FROM mail_rule_projection WHERE id = $1
`

func (q *Queries) DeleteMailRuleProjection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMailRuleProjection, id)
	return err
}

const getMailAccountProjection = `-- name: GetMailAccountProjection :one
SELECT id, owner_id, name, imap_host, imap_port, username, password_encrypted, security, created_at, updated_at FROM mail_account_projection WHERE id = $1
`

func (q *Queries) GetMailAccountProjection(ctx context.Context, id uuid.UUID) (MailAccountProjection, error) {
	row := q.db.QueryRow(ctx, getMailAccountProjection, id)
	var i MailAccountProjection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ImapHost,
		&i.ImapPort,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Security,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMailAccountProjectionForOwner = `-- name: GetMailAccountProjectionForOwner :one
SELECT id, owner_id, name, imap_host, imap_port, username, password_encrypted, security, created_at, updated_at FROM mail_account_projection WHERE id = $1 AND owner_id = $2
`

type GetMailAccountProjectionForOwnerParams struct {
	ID      uuid.UUID `db:"id"`
	OwnerID uuid.UUID `db:"owner_id"`
}

func (q *Queries) GetMailAccountProjectionForOwner(ctx context.Context, arg GetMailAccountProjectionForOwnerParams) (MailAccountProjection, error) {
	row := q.db.QueryRow(ctx, getMailAccountProjectionForOwner, arg.ID, arg.OwnerID)
	var i MailAccountProjection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.ImapHost,
		&i.ImapPort,
		&i.Username,
		&i.PasswordEncrypted,
		&i.Security,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMailRuleProjection = `-- name: GetMailRuleProjection :one
SELECT id, account_id, name, sort_order, enabled, folder, filter_from, filter_subject, max_age_days, attachment_pattern, action, target_directory_id, created_at, updated_at FROM mail_rule_projection WHERE id = $1
`

func (q *Queries) GetMailRuleProjection(ctx context.Context, id uuid.UUID) (MailRuleProjection, error) {
	row := q.db.QueryRow(ctx, getMailRuleProjection, id)
	var i MailRuleProjection
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Name,
		&i.SortOrder,
		&i.Enabled,
		&i.Folder,
		&i.FilterFrom,
		&i.FilterSubject,
		&i.MaxAgeDays,
		&i.AttachmentPattern,
		&i.Action,
		&i.TargetDirectoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMailAccountProjection = `-- name: InsertMailAccountProjection :exec

INSERT INTO mail_account_projection
 (id, owner_id, name, imap_host, imap_port, username, password_encrypted, security, created_at, updated_at)
 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertMailAccountProjectionParams struct {
	ID                uuid.UUID    `db:"id"`
	OwnerID           uuid.UUID    `db:"owner_id"`
	Name              string       `db:"name"`
	ImapHost          string       `db:"imap_host"`
	ImapPort          int32        `db:"imap_port"`
	Username          string       `db:"username"`
	PasswordEncrypted []byte       `db:"password_encrypted"`
	Security          MailSecurity `db:"security"`
	CreatedAt         time.Time    `db:"created_at"`
	UpdatedAt         time.Time    `db:"updated_at"`
}

// ============================================================================
// Mail Account Projection
// ============================================================================
func (q *Queries) InsertMailAccountProjection(ctx context.Context, arg InsertMailAccountProjectionParams) error {
	_, err := q.db.Exec(ctx, insertMailAccountProjection,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.ImapHost,
		arg.ImapPort,
		arg.Username,
		arg.PasswordEncrypted,
		arg.Security,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertMailRuleProjection = `-- name: InsertMailRuleProjection :exec

INSERT INTO mail_rule_projection
 (id, account_id, name, sort_order, enabled, folder, filter_from, filter_subject,
  max_age_days, attachment_pattern, action, target_directory_id, created_at, updated_at)
 VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
  $9, $10, $11, $12, $13, $14)
`

type InsertMailRuleProjectionParams struct {
	ID                uuid.UUID  `db:"id"`
	AccountID         uuid.UUID  `db:"account_id"`
	Name              string     `db:"name"`
	SortOrder         int32      `db:"sort_order"`
	Enabled           bool       `db:"enabled"`
	Folder            string     `db:"folder"`
	FilterFrom        *string    `db:"filter_from"`
	FilterSubject     *string    `db:"filter_subject"`
	MaxAgeDays        int32      `db:"max_age_days"`
	AttachmentPattern *string    `db:"attachment_pattern"`
	Action            MailAction `db:"action"`
	TargetDirectoryID *uuid.UUID `db:"target_directory_id"`
	CreatedAt         time.Time  `db:"created_at"`
	UpdatedAt         time.Time  `db:"updated_at"`
}

// ============================================================================
// Mail Rule Projection
// ============================================================================
func (q *Queries) InsertMailRuleProjection(ctx context.Context, arg InsertMailRuleProjectionParams) error {
	_, err := q.db.Exec(ctx, insertMailRuleProjection,
		arg.ID,
		arg.AccountID,
		arg.Name,
		arg.SortOrder,
		arg.Enabled,
		arg.Folder,
		arg.FilterFrom,
		arg.FilterSubject,
		arg.MaxAgeDays,
		arg.AttachmentPattern,
		arg.Action,
		arg.TargetDirectoryID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertProcessedMessage = `-- name: InsertProcessedMessage :exec

INSERT INTO mail_processed_message (account_id, folder, uid_validity, imap_uid)
 VALUES ($1, $2, $3, $4)
 ON CONFLICT (account_id, folder, uid_validity, imap_uid) DO NOTHING
`

type InsertProcessedMessageParams struct {
	AccountID   uuid.UUID `db:"account_id"`
	Folder      string    `db:"folder"`
	UidValidity int64     `db:"uid_validity"`
	ImapUid     int64     `db:"imap_uid"`
}

// ============================================================================
// Processed Message Bookkeeping
// ============================================================================
func (q *Queries) InsertProcessedMessage(ctx context.Context, arg InsertProcessedMessageParams) error {
	_, err := q.db.Exec(ctx, insertProcessedMessage,
		arg.AccountID,
		arg.Folder,
		arg.UidValidity,
		arg.ImapUid,
	)
	return err
}

const listEnabledMailRuleProjectionsByAccount = `-- name: ListEnabledMailRuleProjectionsByAccount :many
SELECT id, account_id, name, sort_order, enabled, folder, filter_from, filter_subject, max_age_days, attachment_pattern, action, target_directory_id, created_at, updated_at FROM mail_rule_projection
 WHERE account_id = $1 AND enabled = true
 ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListEnabledMailRuleProjectionsByAccount(ctx context.Context, accountID uuid.UUID) ([]MailRuleProjection, error) {
	rows, err := q.db.Query(ctx, listEnabledMailRuleProjectionsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailRuleProjection
	for rows.Next() {
		var i MailRuleProjection
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.SortOrder,
			&i.Enabled,
			&i.Folder,
			&i.FilterFrom,
			&i.FilterSubject,
			&i.MaxAgeDays,
			&i.AttachmentPattern,
			&i.Action,
			&i.TargetDirectoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailAccountProjectionsAll = `-- name: ListMailAccountProjectionsAll :many
SELECT id, owner_id, name, imap_host, imap_port, username, password_encrypted, security, created_at, updated_at FROM mail_account_projection ORDER BY id ASC
`

func (q *Queries) ListMailAccountProjectionsAll(ctx context.Context) ([]MailAccountProjection, error) {
	rows, err := q.db.Query(ctx, listMailAccountProjectionsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailAccountProjection
	for rows.Next() {
		var i MailAccountProjection
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.ImapHost,
			&i.ImapPort,
			&i.Username,
			&i.PasswordEncrypted,
			&i.Security,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailAccountProjectionsByOwner = `-- name: ListMailAccountProjectionsByOwner :many
SELECT id, owner_id, name, imap_host, imap_port, username, password_encrypted, security, created_at, updated_at FROM mail_account_projection
 WHERE owner_id = $1
 ORDER BY name ASC
 LIMIT $3 OFFSET $2
`

type ListMailAccountProjectionsByOwnerParams struct {
	OwnerID uuid.UUID `db:"owner_id"`
	Off     int32     `db:"off"`
	Lim     int32     `db:"lim"`
}

func (q *Queries) ListMailAccountProjectionsByOwner(ctx context.Context, arg ListMailAccountProjectionsByOwnerParams) ([]MailAccountProjection, error) {
	rows, err := q.db.Query(ctx, listMailAccountProjectionsByOwner, arg.OwnerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailAccountProjection
	for rows.Next() {
		var i MailAccountProjection
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.ImapHost,
			&i.ImapPort,
			&i.Username,
			&i.PasswordEncrypted,
			&i.Security,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailRuleProjectionsByOwner = `-- name: ListMailRuleProjectionsByOwner :many
SELECT r.id, r.account_id, r.name, r.sort_order, r.enabled, r.folder, r.filter_from, r.filter_subject, r.max_age_days, r.attachment_pattern, r.action, r.target_directory_id, r.created_at, r.updated_at FROM mail_rule_projection r
 JOIN mail_account_projection a ON a.id = r.account_id
 WHERE a.owner_id = $1
 ORDER BY a.name ASC, r.sort_order ASC, r.created_at ASC
 LIMIT $3 OFFSET $2
`

type ListMailRuleProjectionsByOwnerParams struct {
	OwnerID uuid.UUID `db:"owner_id"`
	Off     int32     `db:"off"`
	Lim     int32     `db:"lim"`
}

func (q *Queries) ListMailRuleProjectionsByOwner(ctx context.Context, arg ListMailRuleProjectionsByOwnerParams) ([]MailRuleProjection, error) {
	rows, err := q.db.Query(ctx, listMailRuleProjectionsByOwner, arg.OwnerID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailRuleProjection
	for rows.Next() {
		var i MailRuleProjection
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Name,
			&i.SortOrder,
			&i.Enabled,
			&i.Folder,
			&i.FilterFrom,
			&i.FilterSubject,
			&i.MaxAgeDays,
			&i.AttachmentPattern,
			&i.Action,
			&i.TargetDirectoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const processedMessageExists = `-- name: ProcessedMessageExists :one
SELECT EXISTS (
  SELECT 1 FROM mail_processed_message
   WHERE account_id = $1 AND folder = $2
     AND uid_validity = $3 AND imap_uid = $4
)
`

type ProcessedMessageExistsParams struct {
	AccountID   uuid.UUID `db:"account_id"`
	Folder      string    `db:"folder"`
	UidValidity int64     `db:"uid_validity"`
	ImapUid     int64     `db:"imap_uid"`
}

func (q *Queries) ProcessedMessageExists(ctx context.Context, arg ProcessedMessageExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, processedMessageExists,
		arg.AccountID,
		arg.Folder,
		arg.UidValidity,
		arg.ImapUid,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMailAccountProjection = `-- name: UpdateMailAccountProjection :exec
UPDATE mail_account_projection
 SET name = $1,
     imap_host = $2,
     imap_port = $3,
     username = $4,
     password_encrypted = $5,
     security = $6,
     updated_at = $7
 WHERE id = $8
`

type UpdateMailAccountProjectionParams struct {
	Name              string       `db:"name"`
	ImapHost          string       `db:"imap_host"`
	ImapPort          int32        `db:"imap_port"`
	Username          string       `db:"username"`
	PasswordEncrypted []byte       `db:"password_encrypted"`
	Security          MailSecurity `db:"security"`
	UpdatedAt         time.Time    `db:"updated_at"`
	ID                uuid.UUID    `db:"id"`
}

func (q *Queries) UpdateMailAccountProjection(ctx context.Context, arg UpdateMailAccountProjectionParams) error {
	_, err := q.db.Exec(ctx, updateMailAccountProjection,
		arg.Name,
		arg.ImapHost,
		arg.ImapPort,
		arg.Username,
		arg.PasswordEncrypted,
		arg.Security,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateMailRuleProjection = `-- name: UpdateMailRuleProjection :exec
UPDATE mail_rule_projection
 SET account_id = $1,
     name = $2,
     sort_order = $3,
     enabled = $4,
     folder = $5,
     filter_from = $6,
     filter_subject = $7,
     max_age_days = $8,
     attachment_pattern = $9,
     action = $10,
     target_directory_id = $11,
     updated_at = $12
 WHERE id = $13
`

type UpdateMailRuleProjectionParams struct {
	AccountID         uuid.UUID  `db:"account_id"`
	Name              string     `db:"name"`
	SortOrder         int32      `db:"sort_order"`
	Enabled           bool       `db:"enabled"`
	Folder            string     `db:"folder"`
	FilterFrom        *string    `db:"filter_from"`
	FilterSubject     *string    `db:"filter_subject"`
	MaxAgeDays        int32      `db:"max_age_days"`
	AttachmentPattern *string    `db:"attachment_pattern"`
	Action            MailAction `db:"action"`
	TargetDirectoryID *uuid.UUID `db:"target_directory_id"`
	UpdatedAt         time.Time  `db:"updated_at"`
	ID                uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateMailRuleProjection(ctx context.Context, arg UpdateMailRuleProjectionParams) error {
	_, err := q.db.Exec(ctx, updateMailRuleProjection,
		arg.AccountID,
		arg.Name,
		arg.SortOrder,
		arg.Enabled,
		arg.Folder,
		arg.FilterFrom,
		arg.FilterSubject,
		arg.MaxAgeDays,
		arg.AttachmentPattern,
		arg.Action,
		arg.TargetDirectoryID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
