// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_store.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getEventsByStreamID = `-- name: GetEventsByStreamID :many
SELECT event_type, event_data FROM event_store
 WHERE stream_id = $1 AND stream_version >= $2
 ORDER BY stream_version ASC
`

type GetEventsByStreamIDParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
}

type GetEventsByStreamIDRow struct {
	EventType string `db:"event_type"`
	EventData []byte `db:"event_data"`
}

func (q *Queries) GetEventsByStreamID(ctx context.Context, arg GetEventsByStreamIDParams) ([]GetEventsByStreamIDRow, error) {
	rows, err := q.db.Query(ctx, getEventsByStreamID, arg.StreamID, arg.StreamVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventsByStreamIDRow
	for rows.Next() {
		var i GetEventsByStreamIDRow
		if err := rows.Scan(&i.EventType, &i.EventData); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStreamVersion = `-- name: GetStreamVersion :one
SELECT COALESCE(MAX(stream_version), 0)::int FROM event_store WHERE stream_id = $1
`

func (q *Queries) GetStreamVersion(ctx context.Context, streamID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getStreamVersion, streamID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertEventStoreEvent = `-- name: InsertEventStoreEvent :exec
INSERT INTO event_store (stream_id, stream_version, event_type, event_data, created_at)
 VALUES ($1, $2, $3, $4, NOW())
`

type InsertEventStoreEventParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
}

func (q *Queries) InsertEventStoreEvent(ctx context.Context, arg InsertEventStoreEventParams) error {
	_, err := q.db.Exec(ctx, insertEventStoreEvent,
		arg.StreamID,
		arg.StreamVersion,
		arg.EventType,
		arg.EventData,
	)
	return err
}
