// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFileProjectionsByParent = `-- name: CountFileProjectionsByParent :one
SELECT COUNT(*) FROM file_projection WHERE parent_id = $1 AND trashed_at IS NULL
`

func (q *Queries) CountFileProjectionsByParent(ctx context.Context, parentID *uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFileProjectionsByParent, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRootFileProjections = `-- name: CountRootFileProjections :one
SELECT COUNT(*) FROM file_projection WHERE parent_id IS NULL AND trashed_at IS NULL
`

func (q *Queries) CountRootFileProjections(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRootFileProjections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashedFile = `-- name: CountTrashedFile :one
SELECT COUNT(*) FROM file_projection WHERE trashed_at IS NOT NULL
`

func (q *Queries) CountTrashedFile(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTrashedFile)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUntrashedFileByIDs = `-- name: CountUntrashedFileByIDs :one
SELECT COUNT(*)::int FROM file_projection
 WHERE id = ANY($1::uuid[]) AND trashed_at IS NULL
`

// Counts how many of the given UUIDs refer to files that exist AND are not
// trashed. Callers compare against len(input) to reject requests that point
// at missing or trashed rows.
func (q *Queries) CountUntrashedFileByIDs(ctx context.Context, dollar_1 []uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUntrashedFileByIDs, dollar_1)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteFilePermissionProjection = `-- name: DeleteFilePermissionProjection :exec
DELETE FROM file_permission_projection
 WHERE id = $1
`

func (q *Queries) DeleteFilePermissionProjection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFilePermissionProjection, id)
	return err
}

const getFilePath = `-- name: GetFilePath :many
WITH RECURSIVE ancestors(id, parent_id, name, trashed_at, depth) AS (
  SELECT d.id, d.parent_id, d.name, d.trashed_at, 0 FROM file_projection d WHERE d.id = $1
  UNION ALL
  SELECT p.id, p.parent_id, p.name, p.trashed_at, a.depth + 1
  FROM file_projection p
  INNER JOIN ancestors a ON p.id = a.parent_id
  WHERE a.trashed_at IS NULL
)
SELECT id, name, trashed_at FROM ancestors
ORDER BY depth DESC
`

type GetFilePathRow struct {
	ID        uuid.UUID  `db:"id"`
	Name      string     `db:"name"`
	TrashedAt *time.Time `db:"trashed_at"`
}

func (q *Queries) GetFilePath(ctx context.Context, id uuid.UUID) ([]GetFilePathRow, error) {
	rows, err := q.db.Query(ctx, getFilePath, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilePathRow
	for rows.Next() {
		var i GetFilePathRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TrashedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilePathIncludingTrashed = `-- name: GetFilePathIncludingTrashed :many
WITH RECURSIVE ancestors(id, parent_id, name, depth) AS (
  SELECT d.id, d.parent_id, d.name, 0 FROM file_projection d WHERE d.id = $1
  UNION ALL
  SELECT p.id, p.parent_id, p.name, a.depth + 1
  FROM file_projection p
  INNER JOIN ancestors a ON p.id = a.parent_id
)
SELECT id, name FROM ancestors
ORDER BY depth DESC
`

type GetFilePathIncludingTrashedRow struct {
	ID   uuid.UUID `db:"id"`
	Name string    `db:"name"`
}

func (q *Queries) GetFilePathIncludingTrashed(ctx context.Context, id uuid.UUID) ([]GetFilePathIncludingTrashedRow, error) {
	rows, err := q.db.Query(ctx, getFilePathIncludingTrashed, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilePathIncludingTrashedRow
	for rows.Next() {
		var i GetFilePathIncludingTrashedRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileProjectionByID = `-- name: GetFileProjectionByID :one
SELECT id, parent_id, is_directory, linked_file_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM file_projection WHERE id = $1
`

func (q *Queries) GetFileProjectionByID(ctx context.Context, id uuid.UUID) (FileProjection, error) {
	row := q.db.QueryRow(ctx, getFileProjectionByID, id)
	var i FileProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedFileID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getFileProjectionByParentAndName = `-- name: GetFileProjectionByParentAndName :one
SELECT id, parent_id, is_directory, linked_file_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM file_projection WHERE parent_id = $1 AND name = $2 AND trashed_at IS NULL
`

type GetFileProjectionByParentAndNameParams struct {
	ParentID *uuid.UUID `db:"parent_id"`
	Name     string     `db:"name"`
}

func (q *Queries) GetFileProjectionByParentAndName(ctx context.Context, arg GetFileProjectionByParentAndNameParams) (FileProjection, error) {
	row := q.db.QueryRow(ctx, getFileProjectionByParentAndName, arg.ParentID, arg.Name)
	var i FileProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedFileID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getFileProjectionByPath = `-- name: GetFileProjectionByPath :one
WITH RECURSIVE path_walk AS (
  SELECT d.id, 1::int AS depth
  FROM file_projection d
  WHERE d.parent_id IS NULL
    AND d.name = ($1::text[])[1]
    AND d.trashed_at IS NULL
  UNION ALL
  SELECT d.id, pw.depth + 1
  FROM file_projection d
  JOIN path_walk pw ON d.parent_id = pw.id
  WHERE d.name = ($1::text[])[pw.depth + 1]
    AND d.trashed_at IS NULL
)
SELECT dp.id, dp.parent_id, dp.is_directory, dp.linked_file_id, dp.name, dp.s3_key, dp.size, dp.checksum, dp.mime_type, dp.content_md, dp.content_search, dp.created_at, dp.updated_at, dp.trashed_at, dp.created_by, dp.updated_by, dp.trashed_by FROM file_projection dp
JOIN path_walk pw ON dp.id = pw.id
WHERE pw.depth = array_length($1::text[], 1)
`

func (q *Queries) GetFileProjectionByPath(ctx context.Context, dollar_1 []string) (FileProjection, error) {
	row := q.db.QueryRow(ctx, getFileProjectionByPath, dollar_1)
	var i FileProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedFileID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getRootFileProjectionByName = `-- name: GetRootFileProjectionByName :one
SELECT id, parent_id, is_directory, linked_file_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM file_projection WHERE parent_id IS NULL AND name = $1 AND trashed_at IS NULL
`

func (q *Queries) GetRootFileProjectionByName(ctx context.Context, name string) (FileProjection, error) {
	row := q.db.QueryRow(ctx, getRootFileProjectionByName, name)
	var i FileProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedFileID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const insertFilePermissionProjection = `-- name: InsertFilePermissionProjection :exec
INSERT INTO file_permission_projection
 (id, file_id, user_account_id, user_group_id, permission_type, created_at)
 VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFilePermissionProjectionParams struct {
	ID             uuid.UUID          `db:"id"`
	FileID         uuid.UUID          `db:"file_id"`
	UserAccountID  *uuid.UUID         `db:"user_account_id"`
	UserGroupID    *uuid.UUID         `db:"user_group_id"`
	PermissionType FilePermissionType `db:"permission_type"`
	CreatedAt      time.Time          `db:"created_at"`
}

func (q *Queries) InsertFilePermissionProjection(ctx context.Context, arg InsertFilePermissionProjectionParams) error {
	_, err := q.db.Exec(ctx, insertFilePermissionProjection,
		arg.ID,
		arg.FileID,
		arg.UserAccountID,
		arg.UserGroupID,
		arg.PermissionType,
		arg.CreatedAt,
	)
	return err
}

const insertFileProjection = `-- name: InsertFileProjection :exec
INSERT INTO file_projection
 (id, parent_id, is_directory, name, created_at, updated_at)
 VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFileProjectionParams struct {
	ID          uuid.UUID  `db:"id"`
	ParentID    *uuid.UUID `db:"parent_id"`
	IsDirectory bool       `db:"is_directory"`
	Name        string     `db:"name"`
	CreatedAt   time.Time  `db:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at"`
}

func (q *Queries) InsertFileProjection(ctx context.Context, arg InsertFileProjectionParams) error {
	_, err := q.db.Exec(ctx, insertFileProjection,
		arg.ID,
		arg.ParentID,
		arg.IsDirectory,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listFileProjections = `-- name: ListFileProjections :many
SELECT id, parent_id, is_directory, linked_file_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM file_projection ORDER BY created_at DESC
`

func (q *Queries) ListFileProjections(ctx context.Context) ([]FileProjection, error) {
	rows, err := q.db.Query(ctx, listFileProjections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileProjection
	for rows.Next() {
		var i FileProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedFileID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileProjectionsByParent = `-- name: ListFileProjectionsByParent :many
SELECT id, parent_id, is_directory, linked_file_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM file_projection WHERE parent_id = $1 AND trashed_at IS NULL ORDER BY is_directory DESC, name ASC
LIMIT $2 OFFSET $3
`

type ListFileProjectionsByParentParams struct {
	ParentID *uuid.UUID `db:"parent_id"`
	Limit    int32      `db:"limit"`
	Offset   int32      `db:"offset"`
}

func (q *Queries) ListFileProjectionsByParent(ctx context.Context, arg ListFileProjectionsByParentParams) ([]FileProjection, error) {
	rows, err := q.db.Query(ctx, listFileProjectionsByParent, arg.ParentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileProjection
	for rows.Next() {
		var i FileProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedFileID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFileProjections = `-- name: ListRootFileProjections :many
SELECT id, parent_id, is_directory, linked_file_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM file_projection WHERE parent_id IS NULL AND trashed_at IS NULL ORDER BY is_directory DESC, name ASC
LIMIT $1 OFFSET $2
`

type ListRootFileProjectionsParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListRootFileProjections(ctx context.Context, arg ListRootFileProjectionsParams) ([]FileProjection, error) {
	rows, err := q.db.Query(ctx, listRootFileProjections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileProjection
	for rows.Next() {
		var i FileProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedFileID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedFile = `-- name: ListTrashedFile :many
SELECT id, parent_id, is_directory, linked_file_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM file_projection WHERE trashed_at IS NOT NULL ORDER BY trashed_at DESC
LIMIT $1 OFFSET $2
`

type ListTrashedFileParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListTrashedFile(ctx context.Context, arg ListTrashedFileParams) ([]FileProjection, error) {
	rows, err := q.db.Query(ctx, listTrashedFile, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileProjection
	for rows.Next() {
		var i FileProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedFileID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileProjectionContentMD = `-- name: UpdateFileProjectionContentMD :exec
UPDATE file_projection
 SET content_md = $1
 WHERE id = $2 AND checksum = $3
`

type UpdateFileProjectionContentMDParams struct {
	ContentMd *string   `db:"content_md"`
	ID        uuid.UUID `db:"id"`
	Checksum  *string   `db:"checksum"`
}

func (q *Queries) UpdateFileProjectionContentMD(ctx context.Context, arg UpdateFileProjectionContentMDParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionContentMD, arg.ContentMd, arg.ID, arg.Checksum)
	return err
}

const updateFileProjectionLinked = `-- name: UpdateFileProjectionLinked :exec
UPDATE file_projection
 SET linked_file_id = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateFileProjectionLinkedParams struct {
	LinkedFileID *uuid.UUID `db:"linked_file_id"`
	UpdatedAt    time.Time  `db:"updated_at"`
	ID           uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateFileProjectionLinked(ctx context.Context, arg UpdateFileProjectionLinkedParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionLinked, arg.LinkedFileID, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionName = `-- name: UpdateFileProjectionName :exec
UPDATE file_projection
 SET name = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateFileProjectionNameParams struct {
	Name      string    `db:"name"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateFileProjectionName(ctx context.Context, arg UpdateFileProjectionNameParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionName, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionParent = `-- name: UpdateFileProjectionParent :exec
UPDATE file_projection
 SET parent_id = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateFileProjectionParentParams struct {
	ParentID  *uuid.UUID `db:"parent_id"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateFileProjectionParent(ctx context.Context, arg UpdateFileProjectionParentParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionParent, arg.ParentID, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionRestored = `-- name: UpdateFileProjectionRestored :exec
UPDATE file_projection
 SET trashed_at = NULL, trashed_by = NULL, updated_at = $1, updated_by = NULL
 WHERE id = $2
`

type UpdateFileProjectionRestoredParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateFileProjectionRestored(ctx context.Context, arg UpdateFileProjectionRestoredParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionRestored, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionTrashed = `-- name: UpdateFileProjectionTrashed :exec
UPDATE file_projection
 SET trashed_at = $1, trashed_by = NULL, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateFileProjectionTrashedParams struct {
	TrashedAt *time.Time `db:"trashed_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateFileProjectionTrashed(ctx context.Context, arg UpdateFileProjectionTrashedParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionTrashed, arg.TrashedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionUnlinked = `-- name: UpdateFileProjectionUnlinked :exec
UPDATE file_projection
 SET linked_file_id = NULL, updated_at = $1, updated_by = NULL
 WHERE id = $2
`

type UpdateFileProjectionUnlinkedParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateFileProjectionUnlinked(ctx context.Context, arg UpdateFileProjectionUnlinkedParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionUnlinked, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionVersion = `-- name: UpdateFileProjectionVersion :exec
UPDATE file_projection
 SET s3_key = $1, size = $2, checksum = $3, mime_type = $4,
     content_md = $5, updated_at = $6, updated_by = NULL
 WHERE id = $7
`

type UpdateFileProjectionVersionParams struct {
	S3Key     *string   `db:"s3_key"`
	Size      *int64    `db:"size"`
	Checksum  *string   `db:"checksum"`
	MimeType  *string   `db:"mime_type"`
	ContentMd *string   `db:"content_md"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateFileProjectionVersion(ctx context.Context, arg UpdateFileProjectionVersionParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionVersion,
		arg.S3Key,
		arg.Size,
		arg.Checksum,
		arg.MimeType,
		arg.ContentMd,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
