// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file_event.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getFileEventsByStreamID = `-- name: GetFileEventsByStreamID :many
SELECT id, stream_id, stream_version, event_type, event_data, created_at FROM file_event
 WHERE stream_id = $1 AND stream_version >= $2
 ORDER BY stream_version ASC
`

type GetFileEventsByStreamIDParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
}

func (q *Queries) GetFileEventsByStreamID(ctx context.Context, arg GetFileEventsByStreamIDParams) ([]FileEvent, error) {
	rows, err := q.db.Query(ctx, getFileEventsByStreamID, arg.StreamID, arg.StreamVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileEvent
	for rows.Next() {
		var i FileEvent
		if err := rows.Scan(
			&i.ID,
			&i.StreamID,
			&i.StreamVersion,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStreamVersion = `-- name: GetStreamVersion :one
SELECT COALESCE(MAX(stream_version), 0)::int FROM file_event WHERE stream_id = $1
`

func (q *Queries) GetStreamVersion(ctx context.Context, streamID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getStreamVersion, streamID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertFileEvent = `-- name: InsertFileEvent :exec
INSERT INTO file_event (stream_id, stream_version, event_type, event_data, created_at)
 VALUES ($1, $2, $3, $4, NOW())
`

type InsertFileEventParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
}

func (q *Queries) InsertFileEvent(ctx context.Context, arg InsertFileEventParams) error {
	_, err := q.db.Exec(ctx, insertFileEvent,
		arg.StreamID,
		arg.StreamVersion,
		arg.EventType,
		arg.EventData,
	)
	return err
}
