// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countFileProjectionsByParent = `-- name: CountFileProjectionsByParent :one
SELECT COUNT(*) FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.parent_id = $2 AND f.trashed_at IS NULL
`

type CountFileProjectionsByParentParams struct {
	UserID   uuid.UUID  `db:"user_id"`
	ParentID *uuid.UUID `db:"parent_id"`
}

func (q *Queries) CountFileProjectionsByParent(ctx context.Context, arg CountFileProjectionsByParentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFileProjectionsByParent, arg.UserID, arg.ParentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRootFileProjections = `-- name: CountRootFileProjections :one
SELECT COUNT(*) FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.parent_id IS NULL AND f.trashed_at IS NULL
`

func (q *Queries) CountRootFileProjections(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRootFileProjections, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrashedFile = `-- name: CountTrashedFile :one
SELECT COUNT(*) FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.trashed_at IS NOT NULL
`

func (q *Queries) CountTrashedFile(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTrashedFile, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUntrashedFileByIDs = `-- name: CountUntrashedFileByIDs :one
SELECT COUNT(*)::int FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.id = ANY($2::uuid[]) AND f.trashed_at IS NULL
`

type CountUntrashedFileByIDsParams struct {
	UserID uuid.UUID   `db:"user_id"`
	Ids    []uuid.UUID `db:"ids"`
}

// Counts how many of the given UUIDs refer to files that exist, are accessible
// to the given user, AND are not trashed. Callers compare against len(input) to
// reject requests that point at missing, trashed, or non-accessible rows.
func (q *Queries) CountUntrashedFileByIDs(ctx context.Context, arg CountUntrashedFileByIDsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUntrashedFileByIDs, arg.UserID, arg.Ids)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getFilePath = `-- name: GetFilePath :many
WITH RECURSIVE ancestors(id, parent_id, name, trashed_at, depth) AS (
  SELECT d.id, d.parent_id, d.name, d.trashed_at, 0
  FROM file_projection d
  JOIN file_permission_projection perm ON perm.file_id = d.id AND perm.user_account_id = $1::uuid
  WHERE d.id = $2
  UNION ALL
  SELECT parent.id, parent.parent_id, parent.name, parent.trashed_at, a.depth + 1
  FROM file_projection parent
  INNER JOIN ancestors a ON parent.id = a.parent_id
  WHERE a.trashed_at IS NULL
)
SELECT id, name, trashed_at FROM ancestors
ORDER BY depth DESC
`

type GetFilePathParams struct {
	UserID uuid.UUID `db:"user_id"`
	FileID uuid.UUID `db:"file_id"`
}

type GetFilePathRow struct {
	ID        uuid.UUID  `db:"id"`
	Name      string     `db:"name"`
	TrashedAt *time.Time `db:"trashed_at"`
}

// Walks ancestors of a file the user can access. The anchor is permission-checked;
// ancestors share the same owner (single-owner trees) so the chain needs no recheck.
func (q *Queries) GetFilePath(ctx context.Context, arg GetFilePathParams) ([]GetFilePathRow, error) {
	rows, err := q.db.Query(ctx, getFilePath, arg.UserID, arg.FileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilePathRow
	for rows.Next() {
		var i GetFilePathRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TrashedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilePathIncludingTrashed = `-- name: GetFilePathIncludingTrashed :many
WITH RECURSIVE ancestors(id, parent_id, name, depth) AS (
  SELECT d.id, d.parent_id, d.name, 0
  FROM file_projection d
  JOIN file_permission_projection perm ON perm.file_id = d.id AND perm.user_account_id = $1::uuid
  WHERE d.id = $2
  UNION ALL
  SELECT parent.id, parent.parent_id, parent.name, a.depth + 1
  FROM file_projection parent
  INNER JOIN ancestors a ON parent.id = a.parent_id
)
SELECT id, name FROM ancestors
ORDER BY depth DESC
`

type GetFilePathIncludingTrashedParams struct {
	UserID uuid.UUID `db:"user_id"`
	FileID uuid.UUID `db:"file_id"`
}

type GetFilePathIncludingTrashedRow struct {
	ID   uuid.UUID `db:"id"`
	Name string    `db:"name"`
}

func (q *Queries) GetFilePathIncludingTrashed(ctx context.Context, arg GetFilePathIncludingTrashedParams) ([]GetFilePathIncludingTrashedRow, error) {
	rows, err := q.db.Query(ctx, getFilePathIncludingTrashed, arg.UserID, arg.FileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilePathIncludingTrashedRow
	for rows.Next() {
		var i GetFilePathIncludingTrashedRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFileProjectionByID = `-- name: GetFileProjectionByID :one
SELECT id, parent_id, is_directory, linked_file_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM file_projection WHERE id = $1
`

// Access-agnostic lookup by id (no permission check). Used by the public-link
// viewer plane, which authorizes via link scope rather than file ownership.
func (q *Queries) GetFileProjectionByID(ctx context.Context, id uuid.UUID) (FileProjection, error) {
	row := q.db.QueryRow(ctx, getFileProjectionByID, id)
	var i FileProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedFileID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getFileProjectionByParentAndName = `-- name: GetFileProjectionByParentAndName :one
SELECT f.id, f.parent_id, f.is_directory, f.linked_file_id, f.name, f.s3_key, f.size, f.checksum, f.mime_type, f.content_md, f.content_search, f.created_at, f.updated_at, f.trashed_at, f.created_by, f.updated_by, f.trashed_by FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.parent_id = $2 AND f.name = $3 AND f.trashed_at IS NULL
`

type GetFileProjectionByParentAndNameParams struct {
	UserID   uuid.UUID  `db:"user_id"`
	ParentID *uuid.UUID `db:"parent_id"`
	Name     string     `db:"name"`
}

func (q *Queries) GetFileProjectionByParentAndName(ctx context.Context, arg GetFileProjectionByParentAndNameParams) (FileProjection, error) {
	row := q.db.QueryRow(ctx, getFileProjectionByParentAndName, arg.UserID, arg.ParentID, arg.Name)
	var i FileProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedFileID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getFileProjectionByPath = `-- name: GetFileProjectionByPath :one
WITH RECURSIVE path_walk AS (
  SELECT d.id, 1::int AS depth
  FROM file_projection d
  WHERE d.parent_id IS NULL
    AND d.name = ($2::text[])[1]
    AND d.trashed_at IS NULL
  UNION ALL
  SELECT d.id, pw.depth + 1
  FROM file_projection d
  JOIN path_walk pw ON d.parent_id = pw.id
  WHERE d.name = ($2::text[])[pw.depth + 1]
    AND d.trashed_at IS NULL
)
SELECT dp.id, dp.parent_id, dp.is_directory, dp.linked_file_id, dp.name, dp.s3_key, dp.size, dp.checksum, dp.mime_type, dp.content_md, dp.content_search, dp.created_at, dp.updated_at, dp.trashed_at, dp.created_by, dp.updated_by, dp.trashed_by FROM file_projection dp
JOIN path_walk pw ON dp.id = pw.id
JOIN file_permission_projection p ON p.file_id = dp.id AND p.user_account_id = $1::uuid
WHERE pw.depth = array_length($2::text[], 1)
`

type GetFileProjectionByPathParams struct {
	UserID   uuid.UUID `db:"user_id"`
	Segments []string  `db:"segments"`
}

// Resolves a name path to a file the user can access. The recursive walk matches
// purely on parent/name (trees are single-owner and disjoint per user); the final
// permission join restricts the result to the requesting user's own subtree.
func (q *Queries) GetFileProjectionByPath(ctx context.Context, arg GetFileProjectionByPathParams) (FileProjection, error) {
	row := q.db.QueryRow(ctx, getFileProjectionByPath, arg.UserID, arg.Segments)
	var i FileProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedFileID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getFileProjectionForUser = `-- name: GetFileProjectionForUser :one
SELECT f.id, f.parent_id, f.is_directory, f.linked_file_id, f.name, f.s3_key, f.size, f.checksum, f.mime_type, f.content_md, f.content_search, f.created_at, f.updated_at, f.trashed_at, f.created_by, f.updated_by, f.trashed_by FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.id = $2
`

type GetFileProjectionForUserParams struct {
	UserID uuid.UUID `db:"user_id"`
	ID     uuid.UUID `db:"id"`
}

// Ownership-scoped lookup: returns the file only if the given user has a
// file_permission_projection entry for it. Any entry currently means "owner"
// (see InsertFilePermissionProjection on create); the join is the single
// authorization gate and extends naturally to shared read/write grants later.
func (q *Queries) GetFileProjectionForUser(ctx context.Context, arg GetFileProjectionForUserParams) (FileProjection, error) {
	row := q.db.QueryRow(ctx, getFileProjectionForUser, arg.UserID, arg.ID)
	var i FileProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedFileID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const getRootFileProjectionByName = `-- name: GetRootFileProjectionByName :one
SELECT f.id, f.parent_id, f.is_directory, f.linked_file_id, f.name, f.s3_key, f.size, f.checksum, f.mime_type, f.content_md, f.content_search, f.created_at, f.updated_at, f.trashed_at, f.created_by, f.updated_by, f.trashed_by FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.parent_id IS NULL AND f.name = $2 AND f.trashed_at IS NULL
`

type GetRootFileProjectionByNameParams struct {
	UserID uuid.UUID `db:"user_id"`
	Name   string    `db:"name"`
}

func (q *Queries) GetRootFileProjectionByName(ctx context.Context, arg GetRootFileProjectionByNameParams) (FileProjection, error) {
	row := q.db.QueryRow(ctx, getRootFileProjectionByName, arg.UserID, arg.Name)
	var i FileProjection
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.IsDirectory,
		&i.LinkedFileID,
		&i.Name,
		&i.S3Key,
		&i.Size,
		&i.Checksum,
		&i.MimeType,
		&i.ContentMd,
		&i.ContentSearch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrashedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.TrashedBy,
	)
	return i, err
}

const insertFilePermissionProjection = `-- name: InsertFilePermissionProjection :exec
INSERT INTO file_permission_projection
 (file_id, user_account_id, created_at)
 VALUES ($1, $2, $3)
`

type InsertFilePermissionProjectionParams struct {
	FileID        uuid.UUID `db:"file_id"`
	UserAccountID uuid.UUID `db:"user_account_id"`
	CreatedAt     time.Time `db:"created_at"`
}

func (q *Queries) InsertFilePermissionProjection(ctx context.Context, arg InsertFilePermissionProjectionParams) error {
	_, err := q.db.Exec(ctx, insertFilePermissionProjection, arg.FileID, arg.UserAccountID, arg.CreatedAt)
	return err
}

const insertFileProjection = `-- name: InsertFileProjection :exec
INSERT INTO file_projection
 (id, parent_id, is_directory, name, created_at, updated_at)
 VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFileProjectionParams struct {
	ID          uuid.UUID  `db:"id"`
	ParentID    *uuid.UUID `db:"parent_id"`
	IsDirectory bool       `db:"is_directory"`
	Name        string     `db:"name"`
	CreatedAt   time.Time  `db:"created_at"`
	UpdatedAt   time.Time  `db:"updated_at"`
}

func (q *Queries) InsertFileProjection(ctx context.Context, arg InsertFileProjectionParams) error {
	_, err := q.db.Exec(ctx, insertFileProjection,
		arg.ID,
		arg.ParentID,
		arg.IsDirectory,
		arg.Name,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listFileOwners = `-- name: ListFileOwners :many
SELECT DISTINCT ON (p.file_id)
  p.file_id, ua.id AS owner_id, ua.name AS owner_name
FROM file_permission_projection p
JOIN user_account_projection ua ON ua.id = p.user_account_id
WHERE p.file_id = ANY($1::uuid[])
ORDER BY p.file_id, p.created_at ASC, p.user_account_id ASC
`

type ListFileOwnersRow struct {
	FileID    uuid.UUID `db:"file_id"`
	OwnerID   uuid.UUID `db:"owner_id"`
	OwnerName string    `db:"owner_name"`
}

// Resolves the owner (id + display name) for each given file. Ownership lives in
// file_permission_projection; the earliest entry per file is the owner (the
// creator), which keeps the result single-valued even once shared grants exist.
// user_account_id is a deterministic tie-breaker for entries sharing created_at.
func (q *Queries) ListFileOwners(ctx context.Context, fileIds []uuid.UUID) ([]ListFileOwnersRow, error) {
	rows, err := q.db.Query(ctx, listFileOwners, fileIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFileOwnersRow
	for rows.Next() {
		var i ListFileOwnersRow
		if err := rows.Scan(&i.FileID, &i.OwnerID, &i.OwnerName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileProjections = `-- name: ListFileProjections :many
SELECT id, parent_id, is_directory, linked_file_id, name, s3_key, size, checksum, mime_type, content_md, content_search, created_at, updated_at, trashed_at, created_by, updated_by, trashed_by FROM file_projection ORDER BY created_at DESC
`

func (q *Queries) ListFileProjections(ctx context.Context) ([]FileProjection, error) {
	rows, err := q.db.Query(ctx, listFileProjections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileProjection
	for rows.Next() {
		var i FileProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedFileID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileProjectionsByParent = `-- name: ListFileProjectionsByParent :many
SELECT f.id, f.parent_id, f.is_directory, f.linked_file_id, f.name, f.s3_key, f.size, f.checksum, f.mime_type, f.content_md, f.content_search, f.created_at, f.updated_at, f.trashed_at, f.created_by, f.updated_by, f.trashed_by FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.parent_id = $2 AND f.trashed_at IS NULL ORDER BY f.is_directory DESC, f.name ASC
LIMIT $4 OFFSET $3
`

type ListFileProjectionsByParentParams struct {
	UserID   uuid.UUID  `db:"user_id"`
	ParentID *uuid.UUID `db:"parent_id"`
	Off      int32      `db:"off"`
	Lim      int32      `db:"lim"`
}

func (q *Queries) ListFileProjectionsByParent(ctx context.Context, arg ListFileProjectionsByParentParams) ([]FileProjection, error) {
	rows, err := q.db.Query(ctx, listFileProjectionsByParent,
		arg.UserID,
		arg.ParentID,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileProjection
	for rows.Next() {
		var i FileProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedFileID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRootFileProjections = `-- name: ListRootFileProjections :many
SELECT f.id, f.parent_id, f.is_directory, f.linked_file_id, f.name, f.s3_key, f.size, f.checksum, f.mime_type, f.content_md, f.content_search, f.created_at, f.updated_at, f.trashed_at, f.created_by, f.updated_by, f.trashed_by FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.parent_id IS NULL AND f.trashed_at IS NULL ORDER BY f.is_directory DESC, f.name ASC
LIMIT $3 OFFSET $2
`

type ListRootFileProjectionsParams struct {
	UserID uuid.UUID `db:"user_id"`
	Off    int32     `db:"off"`
	Lim    int32     `db:"lim"`
}

func (q *Queries) ListRootFileProjections(ctx context.Context, arg ListRootFileProjectionsParams) ([]FileProjection, error) {
	rows, err := q.db.Query(ctx, listRootFileProjections, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileProjection
	for rows.Next() {
		var i FileProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedFileID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrashedFile = `-- name: ListTrashedFile :many
SELECT f.id, f.parent_id, f.is_directory, f.linked_file_id, f.name, f.s3_key, f.size, f.checksum, f.mime_type, f.content_md, f.content_search, f.created_at, f.updated_at, f.trashed_at, f.created_by, f.updated_by, f.trashed_by FROM file_projection f
 JOIN file_permission_projection p ON p.file_id = f.id AND p.user_account_id = $1::uuid
 WHERE f.trashed_at IS NOT NULL ORDER BY f.trashed_at DESC
LIMIT $3 OFFSET $2
`

type ListTrashedFileParams struct {
	UserID uuid.UUID `db:"user_id"`
	Off    int32     `db:"off"`
	Lim    int32     `db:"lim"`
}

func (q *Queries) ListTrashedFile(ctx context.Context, arg ListTrashedFileParams) ([]FileProjection, error) {
	rows, err := q.db.Query(ctx, listTrashedFile, arg.UserID, arg.Off, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileProjection
	for rows.Next() {
		var i FileProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedFileID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFileProjectionContentMD = `-- name: UpdateFileProjectionContentMD :exec
UPDATE file_projection
 SET content_md = $1
 WHERE id = $2 AND checksum = $3
`

type UpdateFileProjectionContentMDParams struct {
	ContentMd *string   `db:"content_md"`
	ID        uuid.UUID `db:"id"`
	Checksum  *string   `db:"checksum"`
}

func (q *Queries) UpdateFileProjectionContentMD(ctx context.Context, arg UpdateFileProjectionContentMDParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionContentMD, arg.ContentMd, arg.ID, arg.Checksum)
	return err
}

const updateFileProjectionLinked = `-- name: UpdateFileProjectionLinked :exec
UPDATE file_projection
 SET linked_file_id = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateFileProjectionLinkedParams struct {
	LinkedFileID *uuid.UUID `db:"linked_file_id"`
	UpdatedAt    time.Time  `db:"updated_at"`
	ID           uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateFileProjectionLinked(ctx context.Context, arg UpdateFileProjectionLinkedParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionLinked, arg.LinkedFileID, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionName = `-- name: UpdateFileProjectionName :exec
UPDATE file_projection
 SET name = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateFileProjectionNameParams struct {
	Name      string    `db:"name"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateFileProjectionName(ctx context.Context, arg UpdateFileProjectionNameParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionName, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionParent = `-- name: UpdateFileProjectionParent :exec
UPDATE file_projection
 SET parent_id = $1, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateFileProjectionParentParams struct {
	ParentID  *uuid.UUID `db:"parent_id"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateFileProjectionParent(ctx context.Context, arg UpdateFileProjectionParentParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionParent, arg.ParentID, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionRestored = `-- name: UpdateFileProjectionRestored :exec
UPDATE file_projection
 SET trashed_at = NULL, trashed_by = NULL, updated_at = $1, updated_by = NULL
 WHERE id = $2
`

type UpdateFileProjectionRestoredParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateFileProjectionRestored(ctx context.Context, arg UpdateFileProjectionRestoredParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionRestored, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionTrashed = `-- name: UpdateFileProjectionTrashed :exec
UPDATE file_projection
 SET trashed_at = $1, trashed_by = NULL, updated_at = $2, updated_by = NULL
 WHERE id = $3
`

type UpdateFileProjectionTrashedParams struct {
	TrashedAt *time.Time `db:"trashed_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateFileProjectionTrashed(ctx context.Context, arg UpdateFileProjectionTrashedParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionTrashed, arg.TrashedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionUnlinked = `-- name: UpdateFileProjectionUnlinked :exec
UPDATE file_projection
 SET linked_file_id = NULL, updated_at = $1, updated_by = NULL
 WHERE id = $2
`

type UpdateFileProjectionUnlinkedParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateFileProjectionUnlinked(ctx context.Context, arg UpdateFileProjectionUnlinkedParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionUnlinked, arg.UpdatedAt, arg.ID)
	return err
}

const updateFileProjectionVersion = `-- name: UpdateFileProjectionVersion :exec
UPDATE file_projection
 SET s3_key = $1, size = $2, checksum = $3, mime_type = $4,
     content_md = $5, updated_at = $6, updated_by = NULL
 WHERE id = $7
`

type UpdateFileProjectionVersionParams struct {
	S3Key     *string   `db:"s3_key"`
	Size      *int64    `db:"size"`
	Checksum  *string   `db:"checksum"`
	MimeType  *string   `db:"mime_type"`
	ContentMd *string   `db:"content_md"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateFileProjectionVersion(ctx context.Context, arg UpdateFileProjectionVersionParams) error {
	_, err := q.db.Exec(ctx, updateFileProjectionVersion,
		arg.S3Key,
		arg.Size,
		arg.Checksum,
		arg.MimeType,
		arg.ContentMd,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
