// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link_event.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getLinkEventsByStreamID = `-- name: GetLinkEventsByStreamID :many
SELECT id, stream_id, stream_version, event_type, event_data, created_at FROM link_event
 WHERE stream_id = $1 AND stream_version >= $2
 ORDER BY stream_version ASC
`

type GetLinkEventsByStreamIDParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
}

func (q *Queries) GetLinkEventsByStreamID(ctx context.Context, arg GetLinkEventsByStreamIDParams) ([]LinkEvent, error) {
	rows, err := q.db.Query(ctx, getLinkEventsByStreamID, arg.StreamID, arg.StreamVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkEvent
	for rows.Next() {
		var i LinkEvent
		if err := rows.Scan(
			&i.ID,
			&i.StreamID,
			&i.StreamVersion,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkStreamVersion = `-- name: GetLinkStreamVersion :one
SELECT COALESCE(MAX(stream_version), 0)::int FROM link_event WHERE stream_id = $1
`

func (q *Queries) GetLinkStreamVersion(ctx context.Context, streamID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getLinkStreamVersion, streamID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertLinkEvent = `-- name: InsertLinkEvent :exec
INSERT INTO link_event (stream_id, stream_version, event_type, event_data, created_at)
 VALUES ($1, $2, $3, $4, NOW())
`

type InsertLinkEventParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
}

func (q *Queries) InsertLinkEvent(ctx context.Context, arg InsertLinkEventParams) error {
	_, err := q.db.Exec(ctx, insertLinkEvent,
		arg.StreamID,
		arg.StreamVersion,
		arg.EventType,
		arg.EventData,
	)
	return err
}
