// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLinkContents = `-- name: CountLinkContents :one
WITH RECURSIVE
roots AS (
  SELECT d.id, d.is_directory
    FROM datei_projection d
    INNER JOIN link_datei_projection ld ON ld.datei_id = d.id
    WHERE ld.link_id = $1 AND d.trashed_at IS NULL
),
descendants(id, is_directory) AS (
  SELECT id, is_directory FROM roots
  UNION
  SELECT child.id, child.is_directory
    FROM datei_projection child
    INNER JOIN descendants d ON child.parent_id = d.id
    WHERE child.trashed_at IS NULL
)
SELECT
  COALESCE(SUM(CASE WHEN is_directory THEN 0 ELSE 1 END), 0)::bigint AS file_count,
  COALESCE(SUM(CASE WHEN is_directory THEN 1 ELSE 0 END), 0)::bigint AS folder_count,
  (SELECT lp.open_count FROM link_projection lp WHERE lp.id = $1) AS open_count
FROM descendants
`

type CountLinkContentsRow struct {
	FileCount   int64 `db:"file_count"`
	FolderCount int64 `db:"folder_count"`
	OpenCount   int64 `db:"open_count"`
}

// Recursively counts files and folders reachable from the link's shared roots,
// including the shared roots themselves. Trashed dateien are excluded. Also
// returns the link's lifetime open count so the response includes everything
// the owner needs in a single round-trip.
func (q *Queries) CountLinkContents(ctx context.Context, id uuid.UUID) (CountLinkContentsRow, error) {
	row := q.db.QueryRow(ctx, countLinkContents, id)
	var i CountLinkContentsRow
	err := row.Scan(&i.FileCount, &i.FolderCount, &i.OpenCount)
	return i, err
}

const countLinkProjectionsByOwner = `-- name: CountLinkProjectionsByOwner :one
SELECT COUNT(*)::bigint FROM link_projection
 WHERE owner_id = $1
   AND CASE $2::text
     WHEN 'active'  THEN revoked_at IS NULL AND (expires_at IS NULL OR expires_at > NOW())
     WHEN 'expired' THEN revoked_at IS NULL AND expires_at IS NOT NULL AND expires_at <= NOW()
     WHEN 'revoked' THEN revoked_at IS NOT NULL
     ELSE TRUE
   END
`

type CountLinkProjectionsByOwnerParams struct {
	OwnerID uuid.UUID `db:"owner_id"`
	Status  string    `db:"status"`
}

// Total row count for the same filter as ListLinkProjectionsByOwner; used to
// populate the response's `total` field for pagination.
func (q *Queries) CountLinkProjectionsByOwner(ctx context.Context, arg CountLinkProjectionsByOwnerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkProjectionsByOwner, arg.OwnerID, arg.Status)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteLinkDateiProjection = `-- name: DeleteLinkDateiProjection :exec
DELETE FROM link_datei_projection
 WHERE link_id = $1 AND datei_id = $2
`

type DeleteLinkDateiProjectionParams struct {
	LinkID  uuid.UUID `db:"link_id"`
	DateiID uuid.UUID `db:"datei_id"`
}

func (q *Queries) DeleteLinkDateiProjection(ctx context.Context, arg DeleteLinkDateiProjectionParams) error {
	_, err := q.db.Exec(ctx, deleteLinkDateiProjection, arg.LinkID, arg.DateiID)
	return err
}

const getLinkProjectionByKey = `-- name: GetLinkProjectionByKey :one
SELECT id, owner_id, name, key, code, expires_at, revoked_at, created_at, updated_at, open_count FROM link_projection WHERE key = $1
`

func (q *Queries) GetLinkProjectionByKey(ctx context.Context, key string) (LinkProjection, error) {
	row := q.db.QueryRow(ctx, getLinkProjectionByKey, key)
	var i LinkProjection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Key,
		&i.Code,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenCount,
	)
	return i, err
}

const getLinkProjectionWithOwnerByID = `-- name: GetLinkProjectionWithOwnerByID :one
SELECT l.id, l.owner_id, l.name, l.key, l.code, l.expires_at, l.revoked_at, l.created_at, l.updated_at, l.open_count, u.name AS owner_name
FROM link_projection l
INNER JOIN user_account_projection u ON u.id = l.owner_id
WHERE l.id = $1
`

type GetLinkProjectionWithOwnerByIDRow struct {
	ID        uuid.UUID  `db:"id"`
	OwnerID   uuid.UUID  `db:"owner_id"`
	Name      string     `db:"name"`
	Key       string     `db:"key"`
	Code      *string    `db:"code"`
	ExpiresAt *time.Time `db:"expires_at"`
	RevokedAt *time.Time `db:"revoked_at"`
	CreatedAt time.Time  `db:"created_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	OpenCount int64      `db:"open_count"`
	OwnerName string     `db:"owner_name"`
}

// Returns the link projection joined with the owner's display name in one
// round-trip. Used by the public list/download endpoints to populate the
// response shape without a second user lookup.
func (q *Queries) GetLinkProjectionWithOwnerByID(ctx context.Context, id uuid.UUID) (GetLinkProjectionWithOwnerByIDRow, error) {
	row := q.db.QueryRow(ctx, getLinkProjectionWithOwnerByID, id)
	var i GetLinkProjectionWithOwnerByIDRow
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Key,
		&i.Code,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OpenCount,
		&i.OwnerName,
	)
	return i, err
}

const incrementLinkProjectionOpenCount = `-- name: IncrementLinkProjectionOpenCount :exec
UPDATE link_projection SET open_count = open_count + 1, updated_at = $1 WHERE id = $2
`

type IncrementLinkProjectionOpenCountParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

// Atomic counter increment driven by the public unlock endpoint. Each
// successful unlock counts as one access.
func (q *Queries) IncrementLinkProjectionOpenCount(ctx context.Context, arg IncrementLinkProjectionOpenCountParams) error {
	_, err := q.db.Exec(ctx, incrementLinkProjectionOpenCount, arg.UpdatedAt, arg.ID)
	return err
}

const insertLinkDateiProjection = `-- name: InsertLinkDateiProjection :exec
INSERT INTO link_datei_projection (link_id, datei_id, added_at)
 VALUES ($1, $2, $3)
 ON CONFLICT (link_id, datei_id) DO NOTHING
`

type InsertLinkDateiProjectionParams struct {
	LinkID  uuid.UUID `db:"link_id"`
	DateiID uuid.UUID `db:"datei_id"`
	AddedAt time.Time `db:"added_at"`
}

func (q *Queries) InsertLinkDateiProjection(ctx context.Context, arg InsertLinkDateiProjectionParams) error {
	_, err := q.db.Exec(ctx, insertLinkDateiProjection, arg.LinkID, arg.DateiID, arg.AddedAt)
	return err
}

const insertLinkProjection = `-- name: InsertLinkProjection :exec
INSERT INTO link_projection
 (id, owner_id, name, key, code, expires_at, created_at, updated_at)
 VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertLinkProjectionParams struct {
	ID        uuid.UUID  `db:"id"`
	OwnerID   uuid.UUID  `db:"owner_id"`
	Name      string     `db:"name"`
	Key       string     `db:"key"`
	Code      *string    `db:"code"`
	ExpiresAt *time.Time `db:"expires_at"`
	CreatedAt time.Time  `db:"created_at"`
	UpdatedAt time.Time  `db:"updated_at"`
}

func (q *Queries) InsertLinkProjection(ctx context.Context, arg InsertLinkProjectionParams) error {
	_, err := q.db.Exec(ctx, insertLinkProjection,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Key,
		arg.Code,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const isDateiInLinkScope = `-- name: IsDateiInLinkScope :one
WITH RECURSIVE
shared_roots(id) AS (
  SELECT datei_id FROM link_datei_projection WHERE link_id = $1
),
ancestors(id, parent_id, trashed_at, depth) AS (
  SELECT d.id, d.parent_id, d.trashed_at, 0
    FROM datei_projection d
    WHERE d.id = $2
  UNION
  SELECT p.id, p.parent_id, p.trashed_at, a.depth + 1
    FROM datei_projection p
    INNER JOIN ancestors a ON p.id = a.parent_id
)
SELECT EXISTS(
  SELECT 1 FROM ancestors a
   WHERE a.id IN (SELECT id FROM shared_roots)
     AND NOT EXISTS (SELECT 1 FROM ancestors WHERE trashed_at IS NOT NULL)
)
`

type IsDateiInLinkScopeParams struct {
	LinkID uuid.UUID `db:"link_id"`
	ID     uuid.UUID `db:"id"`
}

// Returns true iff dateiID is one of the link's directly-shared dateien OR is
// a descendant of any shared directory in the link, AND no ancestor in the
// chain (up to and including the shared root) is trashed.
func (q *Queries) IsDateiInLinkScope(ctx context.Context, arg IsDateiInLinkScopeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDateiInLinkScope, arg.LinkID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDateienByLink = `-- name: ListDateienByLink :many
SELECT d.id, d.parent_id, d.is_directory, d.linked_datei_id, d.name, d.s3_key, d.size, d.checksum, d.mime_type, d.content_md, d.content_search, d.created_at, d.updated_at, d.trashed_at, d.created_by, d.updated_by, d.trashed_by FROM datei_projection d
 INNER JOIN link_datei_projection ld ON ld.datei_id = d.id
 WHERE ld.link_id = $1 AND d.trashed_at IS NULL
 ORDER BY d.is_directory DESC, d.name ASC
`

func (q *Queries) ListDateienByLink(ctx context.Context, linkID uuid.UUID) ([]DateiProjection, error) {
	rows, err := q.db.Query(ctx, listDateienByLink, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DateiProjection
	for rows.Next() {
		var i DateiProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedDateiID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkProjectionsByOwner = `-- name: ListLinkProjectionsByOwner :many
SELECT id, owner_id, name, key, code, expires_at, revoked_at, created_at, updated_at, open_count FROM link_projection
 WHERE owner_id = $1
   AND CASE $2::text
     WHEN 'active'  THEN revoked_at IS NULL AND (expires_at IS NULL OR expires_at > NOW())
     WHEN 'expired' THEN revoked_at IS NULL AND expires_at IS NOT NULL AND expires_at <= NOW()
     WHEN 'revoked' THEN revoked_at IS NOT NULL
     ELSE TRUE
   END
 ORDER BY created_at DESC
 LIMIT $4 OFFSET $3
`

type ListLinkProjectionsByOwnerParams struct {
	OwnerID uuid.UUID `db:"owner_id"`
	Status  string    `db:"status"`
	Off     int32     `db:"off"`
	Lim     int32     `db:"lim"`
}

// status filter values: 'active', 'expired', 'revoked', or ” to return all.
func (q *Queries) ListLinkProjectionsByOwner(ctx context.Context, arg ListLinkProjectionsByOwnerParams) ([]LinkProjection, error) {
	rows, err := q.db.Query(ctx, listLinkProjectionsByOwner,
		arg.OwnerID,
		arg.Status,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkProjection
	for rows.Next() {
		var i LinkProjection
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Key,
			&i.Code,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OpenCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchLinkProjection = `-- name: TouchLinkProjection :exec
UPDATE link_projection SET updated_at = $1 WHERE id = $2
`

type TouchLinkProjectionParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) TouchLinkProjection(ctx context.Context, arg TouchLinkProjectionParams) error {
	_, err := q.db.Exec(ctx, touchLinkProjection, arg.UpdatedAt, arg.ID)
	return err
}

const updateLinkProjection = `-- name: UpdateLinkProjection :exec
UPDATE link_projection
 SET name = $1, code = $2, expires_at = $3, updated_at = $4
 WHERE id = $5
`

type UpdateLinkProjectionParams struct {
	Name      string     `db:"name"`
	Code      *string    `db:"code"`
	ExpiresAt *time.Time `db:"expires_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateLinkProjection(ctx context.Context, arg UpdateLinkProjectionParams) error {
	_, err := q.db.Exec(ctx, updateLinkProjection,
		arg.Name,
		arg.Code,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLinkProjectionKey = `-- name: UpdateLinkProjectionKey :exec
UPDATE link_projection SET key = $1, updated_at = $2 WHERE id = $3
`

type UpdateLinkProjectionKeyParams struct {
	Key       string    `db:"key"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateLinkProjectionKey(ctx context.Context, arg UpdateLinkProjectionKeyParams) error {
	_, err := q.db.Exec(ctx, updateLinkProjectionKey, arg.Key, arg.UpdatedAt, arg.ID)
	return err
}

const updateLinkProjectionRevoked = `-- name: UpdateLinkProjectionRevoked :exec
UPDATE link_projection SET revoked_at = $1, updated_at = $2 WHERE id = $3
`

type UpdateLinkProjectionRevokedParams struct {
	RevokedAt *time.Time `db:"revoked_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateLinkProjectionRevoked(ctx context.Context, arg UpdateLinkProjectionRevokedParams) error {
	_, err := q.db.Exec(ctx, updateLinkProjectionRevoked, arg.RevokedAt, arg.UpdatedAt, arg.ID)
	return err
}
