// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: link.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countLinkContents = `-- name: CountLinkContents :one
WITH RECURSIVE
roots AS (
  SELECT d.id, d.is_directory
    FROM datei_projection d
    INNER JOIN link_datei_projection ld ON ld.datei_id = d.id
    WHERE ld.link_id = $1 AND d.trashed_at IS NULL
),
descendants(id, is_directory) AS (
  SELECT id, is_directory FROM roots
  UNION
  SELECT child.id, child.is_directory
    FROM datei_projection child
    INNER JOIN descendants d ON child.parent_id = d.id
    WHERE child.trashed_at IS NULL
)
SELECT
  COALESCE(SUM(CASE WHEN is_directory THEN 0 ELSE 1 END), 0)::bigint AS file_count,
  COALESCE(SUM(CASE WHEN is_directory THEN 1 ELSE 0 END), 0)::bigint AS folder_count
FROM descendants
`

type CountLinkContentsRow struct {
	FileCount   int64 `db:"file_count"`
	FolderCount int64 `db:"folder_count"`
}

// Recursively counts files and folders reachable from the link's shared roots,
// including the shared roots themselves. Trashed dateien are excluded.
func (q *Queries) CountLinkContents(ctx context.Context, linkID uuid.UUID) (CountLinkContentsRow, error) {
	row := q.db.QueryRow(ctx, countLinkContents, linkID)
	var i CountLinkContentsRow
	err := row.Scan(&i.FileCount, &i.FolderCount)
	return i, err
}

const deleteLinkDateiProjection = `-- name: DeleteLinkDateiProjection :exec
DELETE FROM link_datei_projection
 WHERE link_id = $1 AND datei_id = $2
`

type DeleteLinkDateiProjectionParams struct {
	LinkID  uuid.UUID `db:"link_id"`
	DateiID uuid.UUID `db:"datei_id"`
}

func (q *Queries) DeleteLinkDateiProjection(ctx context.Context, arg DeleteLinkDateiProjectionParams) error {
	_, err := q.db.Exec(ctx, deleteLinkDateiProjection, arg.LinkID, arg.DateiID)
	return err
}

const getLinkProjectionByAccessToken = `-- name: GetLinkProjectionByAccessToken :one
SELECT id, owner_id, name, access_token, code, expires_at, revoked_at, created_at, updated_at FROM link_projection WHERE access_token = $1
`

func (q *Queries) GetLinkProjectionByAccessToken(ctx context.Context, accessToken string) (LinkProjection, error) {
	row := q.db.QueryRow(ctx, getLinkProjectionByAccessToken, accessToken)
	var i LinkProjection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.AccessToken,
		&i.Code,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLinkProjectionByID = `-- name: GetLinkProjectionByID :one
SELECT id, owner_id, name, access_token, code, expires_at, revoked_at, created_at, updated_at FROM link_projection WHERE id = $1
`

func (q *Queries) GetLinkProjectionByID(ctx context.Context, id uuid.UUID) (LinkProjection, error) {
	row := q.db.QueryRow(ctx, getLinkProjectionByID, id)
	var i LinkProjection
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.AccessToken,
		&i.Code,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLinkDateiProjection = `-- name: InsertLinkDateiProjection :exec
INSERT INTO link_datei_projection (link_id, datei_id, added_at)
 VALUES ($1, $2, $3)
 ON CONFLICT (link_id, datei_id) DO NOTHING
`

type InsertLinkDateiProjectionParams struct {
	LinkID  uuid.UUID `db:"link_id"`
	DateiID uuid.UUID `db:"datei_id"`
	AddedAt time.Time `db:"added_at"`
}

func (q *Queries) InsertLinkDateiProjection(ctx context.Context, arg InsertLinkDateiProjectionParams) error {
	_, err := q.db.Exec(ctx, insertLinkDateiProjection, arg.LinkID, arg.DateiID, arg.AddedAt)
	return err
}

const insertLinkProjection = `-- name: InsertLinkProjection :exec
INSERT INTO link_projection
 (id, owner_id, name, access_token, code, expires_at, created_at, updated_at)
 VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
`

type InsertLinkProjectionParams struct {
	ID          uuid.UUID  `db:"id"`
	OwnerID     uuid.UUID  `db:"owner_id"`
	Name        string     `db:"name"`
	AccessToken string     `db:"access_token"`
	Code        *string    `db:"code"`
	ExpiresAt   *time.Time `db:"expires_at"`
	CreatedAt   time.Time  `db:"created_at"`
}

func (q *Queries) InsertLinkProjection(ctx context.Context, arg InsertLinkProjectionParams) error {
	_, err := q.db.Exec(ctx, insertLinkProjection,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.AccessToken,
		arg.Code,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const isDateiInLinkScope = `-- name: IsDateiInLinkScope :one
WITH RECURSIVE
shared_roots(id) AS (
  SELECT datei_id FROM link_datei_projection WHERE link_id = $1
),
ancestors(id, parent_id, trashed_at, depth) AS (
  SELECT d.id, d.parent_id, d.trashed_at, 0
    FROM datei_projection d
    WHERE d.id = $2
  UNION ALL
  SELECT p.id, p.parent_id, p.trashed_at, a.depth + 1
    FROM datei_projection p
    INNER JOIN ancestors a ON p.id = a.parent_id
)
SELECT EXISTS(
  SELECT 1 FROM ancestors a
   WHERE a.id IN (SELECT id FROM shared_roots)
     AND NOT EXISTS (SELECT 1 FROM ancestors WHERE trashed_at IS NOT NULL)
)
`

type IsDateiInLinkScopeParams struct {
	LinkID uuid.UUID `db:"link_id"`
	ID     uuid.UUID `db:"id"`
}

// Returns true iff dateiID is one of the link's directly-shared dateien OR is
// a descendant of any shared directory in the link, AND no ancestor in the
// chain (up to and including the shared root) is trashed.
func (q *Queries) IsDateiInLinkScope(ctx context.Context, arg IsDateiInLinkScopeParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDateiInLinkScope, arg.LinkID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDateienByLink = `-- name: ListDateienByLink :many
SELECT d.id, d.parent_id, d.is_directory, d.linked_datei_id, d.name, d.s3_key, d.size, d.checksum, d.mime_type, d.content_md, d.content_search, d.created_at, d.updated_at, d.trashed_at, d.created_by, d.updated_by, d.trashed_by FROM datei_projection d
 INNER JOIN link_datei_projection ld ON ld.datei_id = d.id
 WHERE ld.link_id = $1 AND d.trashed_at IS NULL
 ORDER BY d.is_directory DESC, d.name ASC
`

func (q *Queries) ListDateienByLink(ctx context.Context, linkID uuid.UUID) ([]DateiProjection, error) {
	rows, err := q.db.Query(ctx, listDateienByLink, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DateiProjection
	for rows.Next() {
		var i DateiProjection
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.IsDirectory,
			&i.LinkedDateiID,
			&i.Name,
			&i.S3Key,
			&i.Size,
			&i.Checksum,
			&i.MimeType,
			&i.ContentMd,
			&i.ContentSearch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrashedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TrashedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkProjectionsByOwner = `-- name: ListLinkProjectionsByOwner :many
SELECT id, owner_id, name, access_token, code, expires_at, revoked_at, created_at, updated_at FROM link_projection
 WHERE owner_id = $1
 ORDER BY created_at DESC
`

func (q *Queries) ListLinkProjectionsByOwner(ctx context.Context, ownerID uuid.UUID) ([]LinkProjection, error) {
	rows, err := q.db.Query(ctx, listLinkProjectionsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkProjection
	for rows.Next() {
		var i LinkProjection
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.AccessToken,
			&i.Code,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLinkProjection = `-- name: UpdateLinkProjection :exec
UPDATE link_projection
 SET name = $1, code = $2, expires_at = $3, updated_at = $4
 WHERE id = $5
`

type UpdateLinkProjectionParams struct {
	Name      string     `db:"name"`
	Code      *string    `db:"code"`
	ExpiresAt *time.Time `db:"expires_at"`
	UpdatedAt time.Time  `db:"updated_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateLinkProjection(ctx context.Context, arg UpdateLinkProjectionParams) error {
	_, err := q.db.Exec(ctx, updateLinkProjection,
		arg.Name,
		arg.Code,
		arg.ExpiresAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateLinkProjectionAccessToken = `-- name: UpdateLinkProjectionAccessToken :exec
UPDATE link_projection SET access_token = $1, updated_at = $2 WHERE id = $3
`

type UpdateLinkProjectionAccessTokenParams struct {
	AccessToken string    `db:"access_token"`
	UpdatedAt   time.Time `db:"updated_at"`
	ID          uuid.UUID `db:"id"`
}

func (q *Queries) UpdateLinkProjectionAccessToken(ctx context.Context, arg UpdateLinkProjectionAccessTokenParams) error {
	_, err := q.db.Exec(ctx, updateLinkProjectionAccessToken, arg.AccessToken, arg.UpdatedAt, arg.ID)
	return err
}

const updateLinkProjectionRevoked = `-- name: UpdateLinkProjectionRevoked :exec
UPDATE link_projection SET revoked_at = $1, updated_at = $1 WHERE id = $2
`

type UpdateLinkProjectionRevokedParams struct {
	RevokedAt *time.Time `db:"revoked_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateLinkProjectionRevoked(ctx context.Context, arg UpdateLinkProjectionRevokedParams) error {
	_, err := q.db.Exec(ctx, updateLinkProjectionRevoked, arg.RevokedAt, arg.ID)
	return err
}
