// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail_account_event.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMailAccountEventsByStreamID = `-- name: GetMailAccountEventsByStreamID :many
SELECT id, stream_id, stream_version, event_type, event_data, created_at FROM mail_account_event
 WHERE stream_id = $1 AND stream_version >= $2
 ORDER BY stream_version ASC
`

type GetMailAccountEventsByStreamIDParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
}

func (q *Queries) GetMailAccountEventsByStreamID(ctx context.Context, arg GetMailAccountEventsByStreamIDParams) ([]MailAccountEvent, error) {
	rows, err := q.db.Query(ctx, getMailAccountEventsByStreamID, arg.StreamID, arg.StreamVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailAccountEvent
	for rows.Next() {
		var i MailAccountEvent
		if err := rows.Scan(
			&i.ID,
			&i.StreamID,
			&i.StreamVersion,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailAccountStreamVersion = `-- name: GetMailAccountStreamVersion :one
SELECT COALESCE(MAX(stream_version), 0)::int FROM mail_account_event WHERE stream_id = $1
`

func (q *Queries) GetMailAccountStreamVersion(ctx context.Context, streamID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMailAccountStreamVersion, streamID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertMailAccountEvent = `-- name: InsertMailAccountEvent :exec
INSERT INTO mail_account_event (stream_id, stream_version, event_type, event_data, created_at)
 VALUES ($1, $2, $3, $4, NOW())
`

type InsertMailAccountEventParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
}

func (q *Queries) InsertMailAccountEvent(ctx context.Context, arg InsertMailAccountEventParams) error {
	_, err := q.db.Exec(ctx, insertMailAccountEvent,
		arg.StreamID,
		arg.StreamVersion,
		arg.EventType,
		arg.EventData,
	)
	return err
}
