// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mail_rule_event.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getMailRuleEventsByStreamID = `-- name: GetMailRuleEventsByStreamID :many
SELECT id, stream_id, stream_version, event_type, event_data, created_at FROM mail_rule_event
 WHERE stream_id = $1 AND stream_version >= $2
 ORDER BY stream_version ASC
`

type GetMailRuleEventsByStreamIDParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
}

func (q *Queries) GetMailRuleEventsByStreamID(ctx context.Context, arg GetMailRuleEventsByStreamIDParams) ([]MailRuleEvent, error) {
	rows, err := q.db.Query(ctx, getMailRuleEventsByStreamID, arg.StreamID, arg.StreamVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MailRuleEvent
	for rows.Next() {
		var i MailRuleEvent
		if err := rows.Scan(
			&i.ID,
			&i.StreamID,
			&i.StreamVersion,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMailRuleStreamVersion = `-- name: GetMailRuleStreamVersion :one
SELECT COALESCE(MAX(stream_version), 0)::int FROM mail_rule_event WHERE stream_id = $1
`

func (q *Queries) GetMailRuleStreamVersion(ctx context.Context, streamID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMailRuleStreamVersion, streamID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertMailRuleEvent = `-- name: InsertMailRuleEvent :exec
INSERT INTO mail_rule_event (stream_id, stream_version, event_type, event_data, created_at)
 VALUES ($1, $2, $3, $4, NOW())
`

type InsertMailRuleEventParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
}

func (q *Queries) InsertMailRuleEvent(ctx context.Context, arg InsertMailRuleEventParams) error {
	_, err := q.db.Exec(ctx, insertMailRuleEvent,
		arg.StreamID,
		arg.StreamVersion,
		arg.EventType,
		arg.EventData,
	)
	return err
}
