// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type UserAccount struct {
	ID           uuid.UUID  `db:"id"`
	Name         string     `db:"name"`
	PasswordHash string     `db:"password_hash"`
	PasswordSalt string     `db:"password_salt"`
	MfaSecret    *string    `db:"mfa_secret"`
	MfaEnabled   bool       `db:"mfa_enabled"`
	MfaEnabledAt *time.Time `db:"mfa_enabled_at"`
	ArchivedAt   *time.Time `db:"archived_at"`
	CreatedAt    time.Time  `db:"created_at"`
	UpdatedAt    time.Time  `db:"updated_at"`
}
