// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createUserAccount = `-- name: CreateUserAccount :one
INSERT INTO user_account (name) VALUES ($1) RETURNING id, name, password_hash, password_salt, mfa_secret, mfa_enabled, mfa_enabled_at, archived_at, created_at, updated_at
`

func (q *Queries) CreateUserAccount(ctx context.Context, name string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, createUserAccount, name)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.MfaEnabledAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByID = `-- name: GetUserAccountByID :one
SELECT id, name, password_hash, password_salt, mfa_secret, mfa_enabled, mfa_enabled_at, archived_at, created_at, updated_at FROM user_account WHERE id = $1
`

func (q *Queries) GetUserAccountByID(ctx context.Context, id uuid.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.MfaEnabledAt,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserAccounts = `-- name: ListUserAccounts :many
SELECT id, name, password_hash, password_salt, mfa_secret, mfa_enabled, mfa_enabled_at, archived_at, created_at, updated_at from user_account ORDER BY name
`

func (q *Queries) ListUserAccounts(ctx context.Context) ([]UserAccount, error) {
	rows, err := q.db.Query(ctx, listUserAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAccount
	for rows.Next() {
		var i UserAccount
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PasswordHash,
			&i.PasswordSalt,
			&i.MfaSecret,
			&i.MfaEnabled,
			&i.MfaEnabledAt,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
