// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_account_access_token.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getAccessTokenByID = `-- name: GetAccessTokenByID :one
SELECT id, user_account_id, label, token_hash, expires_at, revoked_at, created_at FROM user_account_access_token_projection
WHERE id = $1 AND user_account_id = $2
`

type GetAccessTokenByIDParams struct {
	ID            uuid.UUID `db:"id"`
	UserAccountID uuid.UUID `db:"user_account_id"`
}

func (q *Queries) GetAccessTokenByID(ctx context.Context, arg GetAccessTokenByIDParams) (UserAccountAccessTokenProjection, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByID, arg.ID, arg.UserAccountID)
	var i UserAccountAccessTokenProjection
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.Label,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveAccessTokenByHash = `-- name: GetActiveAccessTokenByHash :one
SELECT ua.id, ua.name, ua.password_hash, ua.password_salt, ua.is_admin, ua.mfa_secret, ua.mfa_enabled, ua.mfa_enabled_at, ua.archived_at, ua.last_logged_in_at, ua.created_at, ua.updated_at
FROM user_account_access_token_projection t
JOIN user_account_projection ua ON ua.id = t.user_account_id
WHERE t.token_hash = $1
  AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > now())
  AND ua.archived_at IS NULL
`

type GetActiveAccessTokenByHashRow struct {
	UserAccountProjection UserAccountProjection `db:"user_account_projection"`
}

// Auth hot path: resolve a presented token to its owning account in a single
// round-trip, excluding revoked/expired tokens and archived accounts.
func (q *Queries) GetActiveAccessTokenByHash(ctx context.Context, tokenHash []byte) (GetActiveAccessTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveAccessTokenByHash, tokenHash)
	var i GetActiveAccessTokenByHashRow
	err := row.Scan(
		&i.UserAccountProjection.ID,
		&i.UserAccountProjection.Name,
		&i.UserAccountProjection.PasswordHash,
		&i.UserAccountProjection.PasswordSalt,
		&i.UserAccountProjection.IsAdmin,
		&i.UserAccountProjection.MfaSecret,
		&i.UserAccountProjection.MfaEnabled,
		&i.UserAccountProjection.MfaEnabledAt,
		&i.UserAccountProjection.ArchivedAt,
		&i.UserAccountProjection.LastLoggedInAt,
		&i.UserAccountProjection.CreatedAt,
		&i.UserAccountProjection.UpdatedAt,
	)
	return i, err
}

const insertAccessTokenProjection = `-- name: InsertAccessTokenProjection :exec

INSERT INTO user_account_access_token_projection
  (id, user_account_id, label, token_hash, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAccessTokenProjectionParams struct {
	ID            uuid.UUID  `db:"id"`
	UserAccountID uuid.UUID  `db:"user_account_id"`
	Label         *string    `db:"label"`
	TokenHash     []byte     `db:"token_hash"`
	ExpiresAt     *time.Time `db:"expires_at"`
	CreatedAt     time.Time  `db:"created_at"`
}

// ============================================================================
// Personal Access Token Projection Writes (called inside event handler TX)
// ============================================================================
func (q *Queries) InsertAccessTokenProjection(ctx context.Context, arg InsertAccessTokenProjectionParams) error {
	_, err := q.db.Exec(ctx, insertAccessTokenProjection,
		arg.ID,
		arg.UserAccountID,
		arg.Label,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listAccessTokensForUser = `-- name: ListAccessTokensForUser :many

SELECT id, user_account_id, label, token_hash, expires_at, revoked_at, created_at FROM user_account_access_token_projection
WHERE user_account_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

// ============================================================================
// Personal Access Token Read Queries
// ============================================================================
// Active (non-revoked) tokens for the settings list. Expired tokens are still
// returned so the owner can see and clean them up; the auth path filters expiry
// separately.
func (q *Queries) ListAccessTokensForUser(ctx context.Context, userAccountID uuid.UUID) ([]UserAccountAccessTokenProjection, error) {
	rows, err := q.db.Query(ctx, listAccessTokensForUser, userAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAccountAccessTokenProjection
	for rows.Next() {
		var i UserAccountAccessTokenProjection
		if err := rows.Scan(
			&i.ID,
			&i.UserAccountID,
			&i.Label,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessTokenProjection = `-- name: RevokeAccessTokenProjection :exec
UPDATE user_account_access_token_projection
SET revoked_at = $1
WHERE id = $2 AND revoked_at IS NULL
`

type RevokeAccessTokenProjectionParams struct {
	RevokedAt *time.Time `db:"revoked_at"`
	ID        uuid.UUID  `db:"id"`
}

func (q *Queries) RevokeAccessTokenProjection(ctx context.Context, arg RevokeAccessTokenProjectionParams) error {
	_, err := q.db.Exec(ctx, revokeAccessTokenProjection, arg.RevokedAt, arg.ID)
	return err
}
