// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_account.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUnusedMFARecoveryCodes = `-- name: CountUnusedMFARecoveryCodes :one
SELECT COUNT(*)::int FROM user_account_mfa_recovery_code
WHERE user_account_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedMFARecoveryCodes(ctx context.Context, userAccountID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnusedMFARecoveryCodes, userAccountID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAllMFARecoveryCodesProjection = `-- name: DeleteAllMFARecoveryCodesProjection :exec
DELETE FROM user_account_mfa_recovery_code
WHERE user_account_id = $1
`

func (q *Queries) DeleteAllMFARecoveryCodesProjection(ctx context.Context, userAccountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllMFARecoveryCodesProjection, userAccountID)
	return err
}

const deleteUserAccountEmailProjection = `-- name: DeleteUserAccountEmailProjection :exec
DELETE FROM user_account_email WHERE id = $1
`

func (q *Queries) DeleteUserAccountEmailProjection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserAccountEmailProjection, id)
	return err
}

const getEmailByID = `-- name: GetEmailByID :one
SELECT id, user_account_id, email, verified_at, is_primary, created_at FROM user_account_email
WHERE id = $1 AND user_account_id = $2
`

type GetEmailByIDParams struct {
	ID            uuid.UUID `db:"id"`
	UserAccountID uuid.UUID `db:"user_account_id"`
}

func (q *Queries) GetEmailByID(ctx context.Context, arg GetEmailByIDParams) (UserAccountEmail, error) {
	row := q.db.QueryRow(ctx, getEmailByID, arg.ID, arg.UserAccountID)
	var i UserAccountEmail
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.Email,
		&i.VerifiedAt,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailsForUser = `-- name: GetEmailsForUser :many
SELECT id, user_account_id, email, verified_at, is_primary, created_at FROM user_account_email
WHERE user_account_id = $1
ORDER BY is_primary DESC, created_at
`

func (q *Queries) GetEmailsForUser(ctx context.Context, userAccountID uuid.UUID) ([]UserAccountEmail, error) {
	rows, err := q.db.Query(ctx, getEmailsForUser, userAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAccountEmail
	for rows.Next() {
		var i UserAccountEmail
		if err := rows.Scan(
			&i.ID,
			&i.UserAccountID,
			&i.Email,
			&i.VerifiedAt,
			&i.IsPrimary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrimaryEmailForUser = `-- name: GetPrimaryEmailForUser :one
SELECT id, user_account_id, email, verified_at, is_primary, created_at FROM user_account_email
WHERE user_account_id = $1 AND is_primary = true
`

func (q *Queries) GetPrimaryEmailForUser(ctx context.Context, userAccountID uuid.UUID) (UserAccountEmail, error) {
	row := q.db.QueryRow(ctx, getPrimaryEmailForUser, userAccountID)
	var i UserAccountEmail
	err := row.Scan(
		&i.ID,
		&i.UserAccountID,
		&i.Email,
		&i.VerifiedAt,
		&i.IsPrimary,
		&i.CreatedAt,
	)
	return i, err
}

const getUnusedMFARecoveryCodes = `-- name: GetUnusedMFARecoveryCodes :many
SELECT id, user_account_id, code_hash, code_salt, used_at, created_at FROM user_account_mfa_recovery_code
WHERE user_account_id = $1 AND used_at IS NULL
`

func (q *Queries) GetUnusedMFARecoveryCodes(ctx context.Context, userAccountID uuid.UUID) ([]UserAccountMfaRecoveryCode, error) {
	rows, err := q.db.Query(ctx, getUnusedMFARecoveryCodes, userAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAccountMfaRecoveryCode
	for rows.Next() {
		var i UserAccountMfaRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserAccountID,
			&i.CodeHash,
			&i.CodeSalt,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAccountByEmail = `-- name: GetUserAccountByEmail :one
SELECT ua.id, ua.name, ua.password_hash, ua.password_salt, ua.mfa_secret, ua.mfa_enabled, ua.mfa_enabled_at, ua.archived_at, ua.last_logged_in_at, ua.created_at, ua.updated_at FROM user_account ua
JOIN user_account_email ue ON ue.user_account_id = ua.id
WHERE ue.email = $1 AND ua.archived_at IS NULL
`

func (q *Queries) GetUserAccountByEmail(ctx context.Context, email string) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByEmail, email)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.MfaEnabledAt,
		&i.ArchivedAt,
		&i.LastLoggedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAccountByID = `-- name: GetUserAccountByID :one

SELECT id, name, password_hash, password_salt, mfa_secret, mfa_enabled, mfa_enabled_at, archived_at, last_logged_in_at, created_at, updated_at FROM user_account WHERE id = $1
`

// ============================================================================
// Read Queries (for handlers, outside TX)
// ============================================================================
func (q *Queries) GetUserAccountByID(ctx context.Context, id uuid.UUID) (UserAccount, error) {
	row := q.db.QueryRow(ctx, getUserAccountByID, id)
	var i UserAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PasswordHash,
		&i.PasswordSalt,
		&i.MfaSecret,
		&i.MfaEnabled,
		&i.MfaEnabledAt,
		&i.ArchivedAt,
		&i.LastLoggedInAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMFARecoveryCodeProjection = `-- name: InsertMFARecoveryCodeProjection :exec

INSERT INTO user_account_mfa_recovery_code (id, user_account_id, code_hash, code_salt)
VALUES ($1, $2, $3, $4)
`

type InsertMFARecoveryCodeProjectionParams struct {
	ID            uuid.UUID `db:"id"`
	UserAccountID uuid.UUID `db:"user_account_id"`
	CodeHash      []byte    `db:"code_hash"`
	CodeSalt      []byte    `db:"code_salt"`
}

// ============================================================================
// MFA Recovery Code Projection Writes
// ============================================================================
func (q *Queries) InsertMFARecoveryCodeProjection(ctx context.Context, arg InsertMFARecoveryCodeProjectionParams) error {
	_, err := q.db.Exec(ctx, insertMFARecoveryCodeProjection,
		arg.ID,
		arg.UserAccountID,
		arg.CodeHash,
		arg.CodeSalt,
	)
	return err
}

const insertUserAccountEmailProjection = `-- name: InsertUserAccountEmailProjection :exec

INSERT INTO user_account_email (id, user_account_id, email, is_primary, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserAccountEmailProjectionParams struct {
	ID            uuid.UUID `db:"id"`
	UserAccountID uuid.UUID `db:"user_account_id"`
	Email         string    `db:"email"`
	IsPrimary     bool      `db:"is_primary"`
	CreatedAt     time.Time `db:"created_at"`
}

// ============================================================================
// User Email Projection Writes
// ============================================================================
func (q *Queries) InsertUserAccountEmailProjection(ctx context.Context, arg InsertUserAccountEmailProjectionParams) error {
	_, err := q.db.Exec(ctx, insertUserAccountEmailProjection,
		arg.ID,
		arg.UserAccountID,
		arg.Email,
		arg.IsPrimary,
		arg.CreatedAt,
	)
	return err
}

const insertUserAccountProjection = `-- name: InsertUserAccountProjection :exec

INSERT INTO user_account (id, name, password_hash, password_salt, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
`

type InsertUserAccountProjectionParams struct {
	ID           uuid.UUID `db:"id"`
	Name         string    `db:"name"`
	PasswordHash []byte    `db:"password_hash"`
	PasswordSalt []byte    `db:"password_salt"`
	CreatedAt    time.Time `db:"created_at"`
}

// ============================================================================
// User Account Projection Writes (called inside event handler TX)
// ============================================================================
func (q *Queries) InsertUserAccountProjection(ctx context.Context, arg InsertUserAccountProjectionParams) error {
	_, err := q.db.Exec(ctx, insertUserAccountProjection,
		arg.ID,
		arg.Name,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.CreatedAt,
	)
	return err
}

const markMFARecoveryCodeUsedProjection = `-- name: MarkMFARecoveryCodeUsedProjection :exec
UPDATE user_account_mfa_recovery_code SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkMFARecoveryCodeUsedProjection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markMFARecoveryCodeUsedProjection, id)
	return err
}

const setUserAccountEmailPrimaryProjection = `-- name: SetUserAccountEmailPrimaryProjection :exec
UPDATE user_account_email SET is_primary = (id = $1)
WHERE user_account_id = $2
`

type SetUserAccountEmailPrimaryProjectionParams struct {
	ID            uuid.UUID `db:"id"`
	UserAccountID uuid.UUID `db:"user_account_id"`
}

func (q *Queries) SetUserAccountEmailPrimaryProjection(ctx context.Context, arg SetUserAccountEmailPrimaryProjectionParams) error {
	_, err := q.db.Exec(ctx, setUserAccountEmailPrimaryProjection, arg.ID, arg.UserAccountID)
	return err
}

const updateUserAccountEmailProjectionEmail = `-- name: UpdateUserAccountEmailProjectionEmail :exec
UPDATE user_account_email SET email = $1, verified_at = NULL
WHERE user_account_id = $2 AND is_primary = true
`

type UpdateUserAccountEmailProjectionEmailParams struct {
	Email         string    `db:"email"`
	UserAccountID uuid.UUID `db:"user_account_id"`
}

func (q *Queries) UpdateUserAccountEmailProjectionEmail(ctx context.Context, arg UpdateUserAccountEmailProjectionEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountEmailProjectionEmail, arg.Email, arg.UserAccountID)
	return err
}

const updateUserAccountEmailProjectionVerified = `-- name: UpdateUserAccountEmailProjectionVerified :exec
UPDATE user_account_email SET verified_at = $1
WHERE user_account_id = $2 AND is_primary = true
`

type UpdateUserAccountEmailProjectionVerifiedParams struct {
	VerifiedAt    *time.Time `db:"verified_at"`
	UserAccountID uuid.UUID  `db:"user_account_id"`
}

func (q *Queries) UpdateUserAccountEmailProjectionVerified(ctx context.Context, arg UpdateUserAccountEmailProjectionVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountEmailProjectionVerified, arg.VerifiedAt, arg.UserAccountID)
	return err
}

const updateUserAccountProjectionArchived = `-- name: UpdateUserAccountProjectionArchived :exec
UPDATE user_account SET archived_at = $1, updated_at = $1 WHERE id = $2
`

type UpdateUserAccountProjectionArchivedParams struct {
	ArchivedAt *time.Time `db:"archived_at"`
	ID         uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateUserAccountProjectionArchived(ctx context.Context, arg UpdateUserAccountProjectionArchivedParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountProjectionArchived, arg.ArchivedAt, arg.ID)
	return err
}

const updateUserAccountProjectionLoggedIn = `-- name: UpdateUserAccountProjectionLoggedIn :exec
UPDATE user_account SET last_logged_in_at = $1 WHERE id = $2
`

type UpdateUserAccountProjectionLoggedInParams struct {
	LastLoggedInAt *time.Time `db:"last_logged_in_at"`
	ID             uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateUserAccountProjectionLoggedIn(ctx context.Context, arg UpdateUserAccountProjectionLoggedInParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountProjectionLoggedIn, arg.LastLoggedInAt, arg.ID)
	return err
}

const updateUserAccountProjectionMFADisabled = `-- name: UpdateUserAccountProjectionMFADisabled :exec
UPDATE user_account SET mfa_enabled = false, mfa_secret = NULL, mfa_enabled_at = NULL, updated_at = $1 WHERE id = $2
`

type UpdateUserAccountProjectionMFADisabledParams struct {
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateUserAccountProjectionMFADisabled(ctx context.Context, arg UpdateUserAccountProjectionMFADisabledParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountProjectionMFADisabled, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserAccountProjectionMFAEnabled = `-- name: UpdateUserAccountProjectionMFAEnabled :exec
UPDATE user_account SET mfa_enabled = true, mfa_enabled_at = $1, updated_at = $1 WHERE id = $2
`

type UpdateUserAccountProjectionMFAEnabledParams struct {
	MfaEnabledAt *time.Time `db:"mfa_enabled_at"`
	ID           uuid.UUID  `db:"id"`
}

func (q *Queries) UpdateUserAccountProjectionMFAEnabled(ctx context.Context, arg UpdateUserAccountProjectionMFAEnabledParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountProjectionMFAEnabled, arg.MfaEnabledAt, arg.ID)
	return err
}

const updateUserAccountProjectionMFASecret = `-- name: UpdateUserAccountProjectionMFASecret :exec
UPDATE user_account SET mfa_secret = $1, updated_at = $2 WHERE id = $3
`

type UpdateUserAccountProjectionMFASecretParams struct {
	MfaSecret *string   `db:"mfa_secret"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateUserAccountProjectionMFASecret(ctx context.Context, arg UpdateUserAccountProjectionMFASecretParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountProjectionMFASecret, arg.MfaSecret, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserAccountProjectionName = `-- name: UpdateUserAccountProjectionName :exec
UPDATE user_account SET name = $1, updated_at = $2 WHERE id = $3
`

type UpdateUserAccountProjectionNameParams struct {
	Name      string    `db:"name"`
	UpdatedAt time.Time `db:"updated_at"`
	ID        uuid.UUID `db:"id"`
}

func (q *Queries) UpdateUserAccountProjectionName(ctx context.Context, arg UpdateUserAccountProjectionNameParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountProjectionName, arg.Name, arg.UpdatedAt, arg.ID)
	return err
}

const updateUserAccountProjectionPassword = `-- name: UpdateUserAccountProjectionPassword :exec
UPDATE user_account SET password_hash = $1, password_salt = $2, updated_at = $3 WHERE id = $4
`

type UpdateUserAccountProjectionPasswordParams struct {
	PasswordHash []byte    `db:"password_hash"`
	PasswordSalt []byte    `db:"password_salt"`
	UpdatedAt    time.Time `db:"updated_at"`
	ID           uuid.UUID `db:"id"`
}

func (q *Queries) UpdateUserAccountProjectionPassword(ctx context.Context, arg UpdateUserAccountProjectionPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserAccountProjectionPassword,
		arg.PasswordHash,
		arg.PasswordSalt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
