// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_account_event.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getUserAccountEventsByStreamID = `-- name: GetUserAccountEventsByStreamID :many
SELECT id, stream_id, stream_version, event_type, event_data, created_at FROM user_account_event
 WHERE stream_id = $1 AND stream_version >= $2
 ORDER BY stream_version ASC
`

type GetUserAccountEventsByStreamIDParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
}

func (q *Queries) GetUserAccountEventsByStreamID(ctx context.Context, arg GetUserAccountEventsByStreamIDParams) ([]UserAccountEvent, error) {
	rows, err := q.db.Query(ctx, getUserAccountEventsByStreamID, arg.StreamID, arg.StreamVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserAccountEvent
	for rows.Next() {
		var i UserAccountEvent
		if err := rows.Scan(
			&i.ID,
			&i.StreamID,
			&i.StreamVersion,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAccountStreamVersion = `-- name: GetUserAccountStreamVersion :one
SELECT COALESCE(MAX(stream_version), 0)::int FROM user_account_event WHERE stream_id = $1
`

func (q *Queries) GetUserAccountStreamVersion(ctx context.Context, streamID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUserAccountStreamVersion, streamID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const insertUserAccountEvent = `-- name: InsertUserAccountEvent :exec
INSERT INTO user_account_event (stream_id, stream_version, event_type, event_data, created_at)
 VALUES ($1, $2, $3, $4, NOW())
`

type InsertUserAccountEventParams struct {
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
}

func (q *Queries) InsertUserAccountEvent(ctx context.Context, arg InsertUserAccountEventParams) error {
	_, err := q.db.Exec(ctx, insertUserAccountEvent,
		arg.StreamID,
		arg.StreamVersion,
		arg.EventType,
		arg.EventData,
	)
	return err
}
