// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type DateiPermissionType string

const (
	DateiPermissionTypeOwner     DateiPermissionType = "owner"
	DateiPermissionTypeReadWrite DateiPermissionType = "read_write"
	DateiPermissionTypeReadOnly  DateiPermissionType = "read_only"
)

func (e *DateiPermissionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DateiPermissionType(s)
	case string:
		*e = DateiPermissionType(s)
	default:
		return fmt.Errorf("unsupported scan type for DateiPermissionType: %T", src)
	}
	return nil
}

type NullDateiPermissionType struct {
	DateiPermissionType DateiPermissionType
	Valid               bool // Valid is true if DateiPermissionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDateiPermissionType) Scan(value interface{}) error {
	if value == nil {
		ns.DateiPermissionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DateiPermissionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDateiPermissionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DateiPermissionType), nil
}

type PublicLinkPermissionType string

const (
	PublicLinkPermissionTypeReadOnly  PublicLinkPermissionType = "read_only"
	PublicLinkPermissionTypeReadWrite PublicLinkPermissionType = "read_write"
)

func (e *PublicLinkPermissionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PublicLinkPermissionType(s)
	case string:
		*e = PublicLinkPermissionType(s)
	default:
		return fmt.Errorf("unsupported scan type for PublicLinkPermissionType: %T", src)
	}
	return nil
}

type NullPublicLinkPermissionType struct {
	PublicLinkPermissionType PublicLinkPermissionType
	Valid                    bool // Valid is true if PublicLinkPermissionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPublicLinkPermissionType) Scan(value interface{}) error {
	if value == nil {
		ns.PublicLinkPermissionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PublicLinkPermissionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPublicLinkPermissionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PublicLinkPermissionType), nil
}

type UserGroupRole string

const (
	UserGroupRoleAdmin  UserGroupRole = "admin"
	UserGroupRoleMember UserGroupRole = "member"
)

func (e *UserGroupRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserGroupRole(s)
	case string:
		*e = UserGroupRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserGroupRole: %T", src)
	}
	return nil
}

type NullUserGroupRole struct {
	UserGroupRole UserGroupRole
	Valid         bool // Valid is true if UserGroupRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserGroupRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserGroupRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserGroupRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserGroupRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserGroupRole), nil
}

type DateiAnnotation struct {
	ID        uuid.UUID `db:"id"`
	DateiID   uuid.UUID `db:"datei_id"`
	Key       string    `db:"key"`
	Value     string    `db:"value"`
	CreatedAt time.Time `db:"created_at"`
	UpdatedAt time.Time `db:"updated_at"`
}

type DateiComment struct {
	ID            uuid.UUID `db:"id"`
	DateiID       uuid.UUID `db:"datei_id"`
	UserAccountID uuid.UUID `db:"user_account_id"`
	Content       string    `db:"content"`
	CreatedAt     time.Time `db:"created_at"`
	UpdatedAt     time.Time `db:"updated_at"`
}

type DateiLabel struct {
	DateiID uuid.UUID `db:"datei_id"`
	LabelID uuid.UUID `db:"label_id"`
}

type DateiPermission struct {
	ID             uuid.UUID           `db:"id"`
	DateiID        uuid.UUID           `db:"datei_id"`
	UserAccountID  *uuid.UUID          `db:"user_account_id"`
	UserGroupID    *uuid.UUID          `db:"user_group_id"`
	PermissionType DateiPermissionType `db:"permission_type"`
	IsFavorite     bool                `db:"is_favorite"`
	CreatedAt      time.Time           `db:"created_at"`
}

type DateiPermissionProjection struct {
	ID             uuid.UUID           `db:"id"`
	DateiID        uuid.UUID           `db:"datei_id"`
	UserAccountID  *uuid.UUID          `db:"user_account_id"`
	UserGroupID    *uuid.UUID          `db:"user_group_id"`
	PermissionType DateiPermissionType `db:"permission_type"`
	IsFavorite     bool                `db:"is_favorite"`
	CreatedAt      time.Time           `db:"created_at"`
}

type DateiProjection struct {
	ID            uuid.UUID   `db:"id"`
	ParentID      *uuid.UUID  `db:"parent_id"`
	IsDirectory   bool        `db:"is_directory"`
	LinkedDateiID *uuid.UUID  `db:"linked_datei_id"`
	Name          string      `db:"name"`
	S3Key         *string     `db:"s3_key"`
	Size          *int64      `db:"size"`
	Checksum      *string     `db:"checksum"`
	MimeType      *string     `db:"mime_type"`
	ContentMd     *string     `db:"content_md"`
	ContentSearch interface{} `db:"content_search"`
	CreatedAt     time.Time   `db:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at"`
	TrashedAt     *time.Time  `db:"trashed_at"`
	CreatedBy     *uuid.UUID  `db:"created_by"`
	UpdatedBy     *uuid.UUID  `db:"updated_by"`
	TrashedBy     *uuid.UUID  `db:"trashed_by"`
}

type EventStore struct {
	ID            int64     `db:"id"`
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
	EventMetadata []byte    `db:"event_metadata"`
	CreatedAt     time.Time `db:"created_at"`
}

type Label struct {
	ID              uuid.UUID `db:"id"`
	Name            string    `db:"name"`
	ForegroundColor string    `db:"foreground_color"`
	BackgroundColor string    `db:"background_color"`
	CreatedAt       time.Time `db:"created_at"`
}

type PublicLink struct {
	ID             uuid.UUID                `db:"id"`
	Token          string                   `db:"token"`
	CreatedBy      uuid.UUID                `db:"created_by"`
	PermissionType PublicLinkPermissionType `db:"permission_type"`
	ExpiresAt      *time.Time               `db:"expires_at"`
	CreatedAt      time.Time                `db:"created_at"`
}

type PublicLinkDatei struct {
	PublicLinkID uuid.UUID `db:"public_link_id"`
	DateiID      uuid.UUID `db:"datei_id"`
}

type UserAccount struct {
	ID           uuid.UUID  `db:"id"`
	Name         string     `db:"name"`
	PasswordHash string     `db:"password_hash"`
	PasswordSalt string     `db:"password_salt"`
	MfaSecret    *string    `db:"mfa_secret"`
	MfaEnabled   bool       `db:"mfa_enabled"`
	MfaEnabledAt *time.Time `db:"mfa_enabled_at"`
	ArchivedAt   *time.Time `db:"archived_at"`
	CreatedAt    time.Time  `db:"created_at"`
	UpdatedAt    time.Time  `db:"updated_at"`
}

type UserAccountMfaRecoveryCode struct {
	ID            uuid.UUID  `db:"id"`
	UserAccountID uuid.UUID  `db:"user_account_id"`
	CodeHash      string     `db:"code_hash"`
	CodeSalt      string     `db:"code_salt"`
	UsedAt        *time.Time `db:"used_at"`
	CreatedAt     time.Time  `db:"created_at"`
}

type UserEmail struct {
	ID            uuid.UUID  `db:"id"`
	UserAccountID uuid.UUID  `db:"user_account_id"`
	Email         string     `db:"email"`
	VerifiedAt    *time.Time `db:"verified_at"`
	IsPrimary     bool       `db:"is_primary"`
	CreatedAt     time.Time  `db:"created_at"`
}

type UserGroup struct {
	ID         uuid.UUID  `db:"id"`
	Name       string     `db:"name"`
	CreatedBy  uuid.UUID  `db:"created_by"`
	ArchivedAt *time.Time `db:"archived_at"`
	CreatedAt  time.Time  `db:"created_at"`
}

type UserGroupMember struct {
	UserAccountID uuid.UUID     `db:"user_account_id"`
	UserGroupID   uuid.UUID     `db:"user_group_id"`
	Role          UserGroupRole `db:"role"`
	CreatedAt     time.Time     `db:"created_at"`
}
