// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type FileEvent struct {
	ID            int64     `db:"id"`
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
	CreatedAt     time.Time `db:"created_at"`
}

type FilePermissionProjection struct {
	FileID        uuid.UUID `db:"file_id"`
	UserAccountID uuid.UUID `db:"user_account_id"`
	CreatedAt     time.Time `db:"created_at"`
}

type FileProjection struct {
	ID            uuid.UUID   `db:"id"`
	ParentID      *uuid.UUID  `db:"parent_id"`
	IsDirectory   bool        `db:"is_directory"`
	LinkedFileID  *uuid.UUID  `db:"linked_file_id"`
	Name          string      `db:"name"`
	S3Key         *string     `db:"s3_key"`
	Size          *int64      `db:"size"`
	Checksum      *string     `db:"checksum"`
	MimeType      *string     `db:"mime_type"`
	ContentMd     *string     `db:"content_md"`
	ContentSearch interface{} `db:"content_search"`
	CreatedAt     time.Time   `db:"created_at"`
	UpdatedAt     time.Time   `db:"updated_at"`
	TrashedAt     *time.Time  `db:"trashed_at"`
	CreatedBy     *uuid.UUID  `db:"created_by"`
	UpdatedBy     *uuid.UUID  `db:"updated_by"`
	TrashedBy     *uuid.UUID  `db:"trashed_by"`
}

type LinkEvent struct {
	ID            int64     `db:"id"`
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
	CreatedAt     time.Time `db:"created_at"`
}

type LinkFileProjection struct {
	LinkID  uuid.UUID `db:"link_id"`
	FileID  uuid.UUID `db:"file_id"`
	AddedAt time.Time `db:"added_at"`
}

type LinkProjection struct {
	ID        uuid.UUID  `db:"id"`
	OwnerID   uuid.UUID  `db:"owner_id"`
	Name      string     `db:"name"`
	Key       string     `db:"key"`
	Code      *string    `db:"code"`
	ExpiresAt *time.Time `db:"expires_at"`
	RevokedAt *time.Time `db:"revoked_at"`
	OpenCount int64      `db:"open_count"`
	CreatedAt time.Time  `db:"created_at"`
	UpdatedAt time.Time  `db:"updated_at"`
}

type UserAccountAccessTokenProjection struct {
	ID            uuid.UUID  `db:"id"`
	UserAccountID uuid.UUID  `db:"user_account_id"`
	Label         *string    `db:"label"`
	TokenHash     []byte     `db:"token_hash"`
	ExpiresAt     *time.Time `db:"expires_at"`
	RevokedAt     *time.Time `db:"revoked_at"`
	CreatedAt     time.Time  `db:"created_at"`
}

type UserAccountEmailProjection struct {
	ID            uuid.UUID  `db:"id"`
	UserAccountID uuid.UUID  `db:"user_account_id"`
	Email         string     `db:"email"`
	VerifiedAt    *time.Time `db:"verified_at"`
	IsPrimary     bool       `db:"is_primary"`
	CreatedAt     time.Time  `db:"created_at"`
}

type UserAccountEvent struct {
	ID            int64     `db:"id"`
	StreamID      uuid.UUID `db:"stream_id"`
	StreamVersion int32     `db:"stream_version"`
	EventType     string    `db:"event_type"`
	EventData     []byte    `db:"event_data"`
	CreatedAt     time.Time `db:"created_at"`
}

type UserAccountMfaRecoveryCodeProjection struct {
	ID            uuid.UUID  `db:"id"`
	UserAccountID uuid.UUID  `db:"user_account_id"`
	CodeHash      []byte     `db:"code_hash"`
	CodeSalt      []byte     `db:"code_salt"`
	UsedAt        *time.Time `db:"used_at"`
	CreatedAt     time.Time  `db:"created_at"`
}

type UserAccountProjection struct {
	ID             uuid.UUID  `db:"id"`
	Name           string     `db:"name"`
	PasswordHash   []byte     `db:"password_hash"`
	PasswordSalt   []byte     `db:"password_salt"`
	IsAdmin        bool       `db:"is_admin"`
	MfaSecret      *string    `db:"mfa_secret"`
	MfaEnabled     bool       `db:"mfa_enabled"`
	MfaEnabledAt   *time.Time `db:"mfa_enabled_at"`
	ArchivedAt     *time.Time `db:"archived_at"`
	LastLoggedInAt *time.Time `db:"last_logged_in_at"`
	CreatedAt      time.Time  `db:"created_at"`
	UpdatedAt      time.Time  `db:"updated_at"`
}
